### ISSUE TITLE
Add ability to specify and use negative phenotypes

### ISSUE THREAD

**Issue by julesjacobsen** [exomiser/Exomiser#101]
Seems that medical notes also contain unobserved phenotypes, e.g.

```
Patent foramen ovale
NO Patent ductus arteriosus
```

@pnrobinson Is this correct and a worthwhile thing to persue? Having been through 25 patient records there were a lot of these and currently we only positively select for phenotypes. This should help to improve our accuracy.

**Comment by damiansm** [comment]
part of team operations ticket now
