### ISSUE TITLE
Look into replacing the datamatrix with MapDB

### ISSUE THREAD

**Issue by julesjacobsen** [exomiser/Exomiser#109]
Check out this:
    http://www.mapdb.org/doc/getting-started.html

Key is geneId, value is FloatMatrix. Read these in from the dataMatrix.

**Comment by damiansm** [comment]
Did you ever do this @julesjacobsen . Know you modified the dataMatrix to make it more efficient anyway

**Comment by julesjacobsen** [comment]
Not managed to get into this in any meaningful way. Might be tricky as we'll need to transpose the data in order to read by row instead of column. Would still like to do it as it's a pain waiting to open the matrix each time.

**Comment by drseb** [comment]
I could just create a transposed matrix in the first place.

**Comment by julesjacobsen** [comment]
Resolved in version 10.0.0. Now uses an MVStore-backed DataMatrix, but can still use the old data as an in memory version. No startup time, no perceived loss in speed, minimal RAM overhead. I wish I'd done this earlier!
