### ISSUE TITLE
12 Factor Deployment of the Exomiser Web UI

### ISSUE THREAD

**Issue by holtgrewe** [exomiser/Exomiser#126]
I would like to deploy the Exomiser web UI in the Charite/BIH network. For our web services, we are currently looking towards [flynn.io](http://flynn.io) which currently offers an LXC-based implementation of the most relevant parts of Heroku. A deployment looks more or less as follows:

```
# only the first time
git clone git@... myapp
cd myapp
flynn create myapp-dev
# subsequent deployments
git push flynn master
# => deploy to http://myapp-dev.mhost.example.com
```

The key to making an application deployable in this fashion is having no configuration files per se but configuring everything through environment variables (that can be set by `flynn env set VAR=VALUE`). Of less interest here (but nice for other projects) is Flynn's ability to create MySQL/Postgres/Redis databases.

As far as I can see from the documentation, the Exomiser source code would need the following two changes to allow for a 12 factor deployment:
- Read database connection string from environment variable
- Download Exomiser data base in a pom.xml target (e.g. only active in an "Heroku" build profile)

What do you think?
- Is Charite/Berlin Institute of Health allowed to run an Exomiser web instance by the license? We could increase the maximal number of variants in a VCF file for our internal server which will be quite handy.
- Do you think this would be useful for the Sanger "demo" deployment?

**Comment by damiansm** [comment]
Is this resolved now we have moved to Monarch. Do you have Phenix(2) up and running at Charite now @drseb

**Comment by drseb** [comment]
Hi. Still working on getting the boqa-prioritizer implemented. Current status: waiting for max to find some time to help, which will probably happen in the beginning of august.

**Comment by julesjacobsen** [comment]
Closing this now as the thread has mutated and I think exomiser-web is '12-factor compliant' enough for what you asked for. Build, deploy and config are all separate. There is zero requirement for any infrastructure other than an machine of some sort running java. Configuration happens externally via command line input and/or configuration file. It's as easy to run in production as it is on a developer machine.
