### ISSUE TITLE
Can dbNSFP provide all the required variant annotations?

### ISSUE THREAD

**Issue by julesjacobsen** [exomiser/Exomiser#134]
[dbNSFP](https://sites.google.com/site/jpopgen/dbNSFP) has grown a lot since exomiser started. Currently we're parsing a lot of seperate resources and only using dbNSFP to extract SIFT, Polyphen and MutationTaster scores. There are a lot of other variant resources in there including all the frequency sets we use, so it looks like it probably can - [dbNSFP version 3.1a](https://drive.google.com/file/d/0B60wROKy6OqccXV4UXNyNkJwNUk/view?pref=2&pli=1) has:

Positions:
- hg38
- hg37

Frequencies:
- dbSNP 
- 100genomes
- ESP
- ExAC
- UK10K

Pathogenicity scores:
- CADD
- SIFT
- Polyphen
- Clinvar

the Gene annotations include the HGNC gene id to UCSC, ENSEMBL, MGI, ZFIN, MIM gene, MIM disease and MIM phenotype ids.

Using this single resource would massively simplify the data build procedure @damiansm @pnrobinson - can you remember the reasons for using the current, non-integrated set of data sources? Other than becoming completely dependent on a single source of data, and relinquishing the ability to independently update a datasource can you think of any other reason not to use this?

**Comment by pnrobinson** [comment]
Not sure about the choise of data sources anymore, but dbNSFP is probably a great option and I do not see too many reasopns not to use it. We could also use the NCBI Entrez Gene ID; I did not see it in the list but perhaps it is also there?
-Peter

Von: Jules Jacobsen [mailto:notifications@github.com]
Gesendet: Dienstag, 31. Mai 2016 14:44
An: exomiser/Exomiser <Exomiser@noreply.github.com>
Cc: Robinson, Peter <peter.robinson@charite.de>; Mention <mention@noreply.github.com>
Betreff: [exomiser/Exomiser] Can dbNSFP provide all the required variant annotations? (#134)


Looks like it probably can - dbNSFP version 3.1a has:
Positions:

  *   hg38
  *   hg37 Frequencies:
  *   dbSNP
  *   100genomes
  *   ESP
  *   ExAC
  *   UK10K Pathogenicity scores:
  *   CADD
  *   SIFT
  *   Polyphen
  *   Clinvar

the Gene annotations include the HGNC gene id to UCSC, ENSEMBL, MGI, ZFIN, MIM gene, MIM disease and MIM phenotype ids.

Using this single resource would massively simplify the data build procedure @damiansm<https://github.com/damiansm> @pnrobinson<https://github.com/pnrobinson> - can you remember the reasons for using the current, non-integrated set of data sources? Other than becoming completely dependent on a single source of data, and relinquishing the ability to independently update a datasource can you think of any other reason not to use this?

**Comment by damiansm** [comment]
Guess it only has the data for the non-syn variants though and we were
getting some info on others from other sources?

**Comment by julesjacobsen** [comment]
@damiansm hmm, good point. Will check that. 

@pnrobinson Kind of - Entrez gene id is in dbNSFP_gene file rather than variants file.

**Comment by julesjacobsen** [comment]
Yep, dbNSFP [only contains non-synonymous variants ](http://www.ncbi.nlm.nih.gov/pubmed/26555599). Bummer - Should have read the manual :(

**Comment by damiansm** [comment]
Or even just the acronym ;-)

**Comment by visze** [comment]
Do they provide ExAC for GRCh38? Because I can find only a GRCh37 ExAC release on their website

**Comment by martenj** [comment]
No still no dataset for GRCh38. Was looking for it several times since I wanted it for the ASDPex.
Am 01.06.2016 10:40 nachm. schrieb Max <notifications@github.com>:Do they provide ExAC for GRCh38? Because I can find only a GRCh37 ExAC release on their website

**Comment by julesjacobsen** [comment]
[Kaviar](http://db.systemsbiology.net/kaviar) ([ref](http://bioinformatics.oxfordjournals.org/content/27/22/3216.full)) looks like a decent contender for variant frequencies. Using Kaviar and DBNSFP togther with REMM and CADD should mean that we can use tabix directly for querying sequence datasources and people can update their data by simply replacing the files meaning we don't need to build these into the database. At worst we'll have to combine Kaviar and DBNSFP into a single tabix datasource with all the variant information in. This will get us much improved variant frequencies and a simpler data build.

**Comment by pnrobinson** [comment]
Kaviar seems a really useful resource (btw the dbSNP in Kaviar is Version 146 not 132), and I agree it would be great to explore this option. I suspect that the majority of our users would be comfortable with this, and we will also have demo versions online etc.

**Comment by visze** [comment]
What about ExAC?

**Comment by damiansm** [comment]
But ExAc is the no.1 source everyone wants - we will always need that?

**Comment by damiansm** [comment]
Looks like it does not have ExAC though?

**Comment by drseb** [comment]
> Looks like it does not have ExAC though?

But http://db.systemsbiology.net/kaviar/cgi-pub/Kaviar.pl?show=sources shows the item "63000exomes". Isn't this exac?

**Comment by julesjacobsen** [comment]
@damiansm kaviar or dbnsfp? dbnsfp has ExAC.

**Comment by damiansm** [comment]
But only for non-synonymous SNPs. We need to the frequencies for all the
other types

**Comment by julesjacobsen** [comment]
Sorry, keep forgetting that.

So going to use Kaviar, dbNSFP and ExAC

**Comment by damiansm** [comment]
Hold on - seb may be right that kaviar has Exac. It just had a daft label.

The big question is whether Kaviar is respected in the community, trusted
etc - especially if they are doing the hg38 liftover for everything.

**Comment by julesjacobsen** [comment]
Kaviar sources: http://db.systemsbiology.net/kaviar/cgi-pub/Kaviar.pl?show=sources

[63000exomes](http://exac.broadinstitute.org/) links to ExAC, so yes, it does have it.

**Comment by damiansm** [comment]
So we just need to decide if Kaviar is good. What have people heard about
it at AHSG etc. Do people use it?

**Comment by pnrobinson** [comment]
Kaviar seems to be much less well known in the community than ExAC, but it provides actually even more data (especially for the bits of the genome outside the exome). I have heard that ExAC will be providing WGS data next year. However, I think that Kaviar has sufficient "brand recognition" (e.g., Institute of Systems Biology and the authors) that we can use it without too many worries. I had been wanting to suggest this for some time now actually.

**Comment by damiansm** [comment]
Cool - lets go for it then Jules. Guess we can do some QC of the ExAC
variants to check they are all included and lifted over accurately

Cheers
Damian

**Comment by damiansm** [comment]
Appears that Kaviar don't maintain the source of the frequency data though so lose ability to do population filtering. Decided to just keep existing sources for now
