### ISSUE TITLE
Brain noises

### ISSUE THREAD

**Issue by julesjacobsen** [exomiser/Exomiser#141]
DiseaseModel and OmimPrioritiser Disease. These are almost the same. Should Disease implement Model? Can OmimPrioritiser and InheritanceModeFilter be done together as a post-filtering step? Phenotypically similar diseases should already come from HiPhive.

**Comment by pnrobinson** [comment]
Hi Jules, can we skype about all of this?

**Comment by julesjacobsen** [comment]
Hi Peter, sure - these are just some semi-nacent ideas at the moment, but would be really good to have someone else's ideas too.

**Comment by damiansm** [comment]
ok to close this now @julesjacobsen or is your brain still noisy?

**Comment by julesjacobsen** [comment]
My mind is silent. Might do this one day, might not. What is the sound of Eternity?
