### ISSUE TITLE
REGULATORY_REGION_VARIANT

### ISSUE THREAD

**Issue by pnrobinson** [exomiser/Exomiser#142]
It would be useful to know which regulatory region is meant.
1. Promoter of a gene (by location)
2. Particular element (e.g., http://pressto.binf.ku.dk/about.php#h_enhancers_description_long)

Actually, the label REGULATORY_REGION_VARIANT as we are using it is slightly wrong, because also 5'UTR and 3'UTRs are regulatory regions as well. In fact, there are regulatory regions in the coding sequence, so essentially the entire genome can be regarded as a regulatory region in one way or another. I would love to see us make this more specific, and users would be able to interpret the variants much more easily.

**Comment by damiansm** [comment]
Related to #143 We need to a better job of helping people decide what to do about the Genomiser results

**Comment by visze** [comment]
I did some experiments on that. Based on them you can remove the Regulatory
region completely. It is enough to judge variants by remm (nearly equal
performance!). Remm also includes most of the tracks used here.

Cheers,
Max

Am 10.07.2017 16:58 schrieb "damiansm" <notifications@github.com>:

**Comment by damiansm** [comment]
Relates to #132 as Max says

**Comment by damiansm** [comment]
see  #219 for this now
