### ISSUE TITLE
Postprocess UTR mutations for visualization

### ISSUE THREAD

**Issue by pnrobinson** [exomiser/Exomiser#143]
Currently, our ReMM score provides a single numerical prediction of pathogenicity, but it is "black box" and difficult for clinicians to interpret. We can make Genomiser much more user friendly by proving a visualization or other aides.
For instance, a mutation in the 5' UTR can be an upsteam ORF, a Kozak sequence mutation, a mutation in a known secondary structure element, a mutation in an RNA binding or indeed a DNA binding element. These are all different mechanisms and optimally (some day) we will show a widget that will display the distribution of known mutations across these classes, and will predict into which class the current variant falls. This is probably tricky to implement, but we could at least precalculate upstream ORFs etc and store them in a database table and use this for display?

**Comment by damiansm** [comment]
Totally agree - Genomiser is powerful but when using it in the wild is hard to know what to do with the high-scoring variants. Even a link to Ensembl regulatory build could be useful

**Comment by damiansm** [comment]
see  #219 for this now
