### ISSUE TITLE
de.charite.compbio.exomiser.core.prioritisers.PhenixPriority$PhenixException: Please supply some HPO terms. PhenIX is unable to prioritise genes without these.

### ISSUE THREAD

**Issue by visze** [exomiser/Exomiser#144]
Exomiser web (tested on the sanger website) throws an Exception if you put in a Syndrom as phenotype and if you choose PheniX.

I tested following:

- Pfeiffer Sydrome + PheniX => ERROR!
- Pfeiffer Sydrome + HiPhive => works
- HPO-Terms + PheniX => works
- HPO-Terms + HiPhive => works

Error message:

```
type Exception report

message Request processing failed; nested exception is de.charite.compbio.exomiser.core.prioritisers.PhenixPriority$PhenixException: Please supply some HPO terms. PhenIX is unable to prioritise genes without these.

description The server encountered an internal error that prevented it from fulfilling this request.

exception

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is de.charite.compbio.exomiser.core.prioritisers.PhenixPriority$PhenixException: Please supply some HPO terms. PhenIX is unable to prioritise genes without these.
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
	org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:728)

root cause

de.charite.compbio.exomiser.core.prioritisers.PhenixPriority$PhenixException: Please supply some HPO terms. PhenIX is unable to prioritise genes without these.
	de.charite.compbio.exomiser.core.prioritisers.PhenixPriority.<init>(PhenixPriority.java:131)
	de.charite.compbio.exomiser.core.prioritisers.PriorityFactory.getPhenixPrioritiser(PriorityFactory.java:90)
	de.charite.compbio.exomiser.core.prioritisers.PriorityFactory.makePrioritisers(PriorityFactory.java:62)
	de.charite.compbio.exomiser.core.Exomiser.analyse(Exomiser.java:72)
	de.charite.compbio.exomiser.web.controller.SubmitJobController.submit(SubmitJobController.java:122)
	sun.reflect.GeneratedMethodAccessor194.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:601)
	org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
	org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:781)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:721)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:83)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:943)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
	org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
```

**Comment by julesjacobsen** [comment]
This is an issue with the version running at Sanger and not present in later (7+) versions. The Sanger instance is being shutdown next month and it's a pain to update do I'm going to leave it for now. OK?

**Comment by julesjacobsen** [comment]
OK, no reply - I'm closing this.

**Comment by pnrobinson** [comment]
I think it would be OK to supply the root term if the user does not supply any HPO term. This would in effect just prioritize variants, which might also be useful.

**Comment by drseb** [comment]
If it is no longer an issue with later versions it can be closed. Would be interesting to know how this is solved in version 7+!

**Comment by julesjacobsen** [comment]
Currently the web version will use the phenotypes from a disease name, or the input phenotypes. The CLI version will do the same. 

Both versions will throw an exception and refuse to run if there are no disease id or phenotype terms used. How do you want it to work? Fail or use the root term. I think the failure option isn't a bad one as the root term is pretty meaningless. If you don't want to run any prioritisers and just prioritise variants there is the 'none' option, or in the case of the newver yaml config, don't specify anything.

With regards the pure variant prioritising this will be a new more scaleable feature using streams which will allow for full annotation of entire genomes with constant RAM usage.

**Comment by visze** [comment]
I think the root makes no sense. Maybe it would be nice to use it only for
filtering and annotating without phenotypes. But this can be a special
option so that we are sure that the user realy wants to do that.

But this discussion changed to another topic. The actual issue is a Bug in
the version on the Sanger Website and it is fixed in later versions. Maybe
we switch this discussion to another issue.

Am 08.11.2016 17:44 schrieb "Jules Jacobsen" <notifications@github.com>:

**Comment by drseb** [comment]
I think the root makes some sense, but maybe it is really better to make a separate issue!?

**Comment by julesjacobsen** [comment]
OK - so if you're happy this is no longer an issue, please close this and open a separate issue for how Phenix or even the system should behave without input phenotypes.
