### ISSUE TITLE
Sanger Demo: Unknown error (502) when using from Crete

### ISSUE THREAD

**Issue by drseb** [exomiser/Exomiser#145]
Hi,

I have used `Pfeiffer.vcf` and entered two HPO terms (`Abn. of the hip bone`, `Short nose`). I left all other settings as they were when loading the page (http://www.sanger.ac.uk/resources/software/exomiser/submit/). The upload takes a while, as I am in Crete at the moment. It seems the upload finishes normally (i.e. the percentage counter goes up to 100%). 

The setting I described seems to be working for @visze who is in Berlin at the moment.

The result is:
```
Unknown error (502)
Your request for "/resources/software/exomiser/submit/submit" failed. The reason is:

An error occurred
```

The questions are:

- Can I get a more detailed error message?
- Is the problem on my site or on the sanger site?
- I have to give a teaching course in a few hours - so this is urgent. Any quick fixes?

Note: We still have the PhenIX-instance at Charité that seems to working - anyway, it would be way more professional to be able to show a working Exomiser version.

**Comment by julesjacobsen** [comment]
502 is a server communication error. Probably happened due to poor connectivity from where you are.
