### ISSUE TITLE
Removal of Uberpheno Prioritiser

### ISSUE THREAD

**Issue by julesjacobsen** [exomiser/Exomiser#150]
Uberpheno is unused, un-maintained and not actually available for people to run. This is dead-wood and I'd like to remove it.

**Comment by julesjacobsen** [comment]
@drseb @pnrobinson @damiansm Anyone object?

**Comment by drseb** [comment]
I think it can be removed. I added it for testing purposes long time ago. I mean, I still believe it will work better than owlsim because of the p-value on top of SemSim, but this would have to be tested.

**Comment by julesjacobsen** [comment]
OK, well if you still need it you can copy it over from any tag >=[7.2.3](https://github.com/exomiser/Exomiser/tree/7.2.3)

**Comment by drseb** [comment]
perfect

**Comment by julesjacobsen** [comment]
commit 8676f3bae761f24d9bf15fc314f26ba01f91f6df
