### ISSUE TITLE
Polyphen Score Model Choice

### ISSUE THREAD

**Issue by stolpeo** [exomiser/Exomiser#153]
As far as I can see from my Exomiser 7.2.1 results (run with PhenIX or hiPHIVE as priorization method), it uses the PolyPhen score from the model that was trained with HumVar. But the other trained model (HumDiv) aims at mendelian diseases and makes more sense to me in this context. Maybe I got something wrong here, I just would like to learn why you picked the HumVar score over the HumDiv score!

> Two pairs of datasets were used to train and test PolyPhen-2 prediction models. The first pair,
HumDiv, was compiled from all damaging alleles with known effects on the molecular function
causing human Mendelian diseases, present in the UniProtKB database, together with differences
between human proteins and their closely related mammalian homologs, assumed to be
non-damaging. The second pair, HumVar, consisted of all human disease-causing mutations from
UniProtKB, together with common human nsSNPs (MAF>1%) without annotated involvement in
disease, which were treated as non-damaging.

http://genetics.bwh.harvard.edu/pph2/dokuwiki/overview

**Comment by pnrobinson** [comment]
Thanks for this comment. We did not compare the performance of these two options, and this would be interesting to do in the future. The intuition behind the choice was basically that we do not really know what the characteristics of mutations in new disease genes are and thus it seemed to be more conservative to go with the broader version of polyphen. The final Exomiser score also uses SIFT and MutationTastter and some heuristics, so it is hard for me to guess what the effect would be of the alternative polyphen dataset. In addition, there are newer pathogenicity prediction methods appearing recentlly with apparently better performance, so we may also want to test just what the influence is.
