### ISSUE TITLE
GeneIdentifier class

### ISSUE THREAD

**Issue by damiansm** [exomiser/Exomiser#156]
- Requirement for using Ensembl transcripts for Jannovar

Will probably create a GeneIdentifier class which will be a container for the current gene symbol and gene id – these are almost always referenced together and cannot be passed as a single entity. Ideally geneId will change from and Integer to a string which can contain a curie ENTREZ:122345 or HGNC:12345, or ENSG…. This is all good apart from that it will break the FloatMatrix lookup which uses Integers. This might be relatively easy to fix, it might not. Need to check. The disadvantage of having this is that we then need to check what namespace the identifier belongs to. So in all it might just be a bit too much of a pain to make it worth doing anything other than using the current setup, but combining them as a tuple. i.e. stick with Entrez ids.

**Comment by visze** [comment]
Jannovar 0.18 will provide entrez gene-ids for every transcript database (ensemble, ensemble curated, refseq, refseq curated, ccds, ucsc). So you do not need the "hack" in exomiser anymore.

Then we can change exomiser so that the user can set their favourite transcript database. I think this is in eager expectation from the users.

**Comment by julesjacobsen** [comment]
Interesting - how is this data exposed? Can you point me to some code examples/ unit tests to see how this works?

**Comment by julesjacobsen** [comment]
Linked with #162.

It's implemented and working (commits 4975814a1fbb5f07b22997c238e988aaaa98629d and 6c4d2b6bdfa6d5a3fbc1b37cb72b6123155d8721), but requires a bit of cleaning up. Will do this in conjunction with issue #155.
