### ISSUE TITLE
User-specified data e.g. local frequencies

### ISSUE THREAD

**Issue by damiansm** [exomiser/Exomiser#157]
- Look into getting the GEL frequency data as a tabix file and we can see how this can be incorporated as a user-definable local database (requires core and spring-boot-autoconfigure changes).
- Need to make this generic so any frequency db can be added but at moment frequency sources coded in an ENUM and have one LOCAL
- Could go further to make all external sources the responsibility of the user to download (and license) and load into a flatfile-based system or db that Exomiser reads e.g. takes care of OMIM issue

**Comment by julesjacobsen** [comment]
Will these be SNVs only, or indels or both?

**Comment by damiansm** [comment]
Should be both

**Comment by julesjacobsen** [comment]
Should be sorted now. Tabix file needs to be in this format: 

```
##Chromosome names: 1-22, X, Y, M
##Positions should be 1-based.
##REF/ALT deletions should have a '.' character in their place.
##Frequency column should be a percentage value i.e. range 0.0 - 100.0
##Multiple alternative alleles should be split so that each occurs on its own line.
#CHR	POS	REF	ALT	FREQ(%)
10	123256215	T	G	0.001

```
To enable local frequencies in exomiser, add the tabix file location with ```exomiser.local-frequency-path=``` in the ```application.properties``` file.

For an anlysis, add ```LOCAL``` to the ```frequencySources:``` in the yml input file.

**Comment by julesjacobsen** [comment]
- [ ] Need to check that UCSC, REFSEQ and Ensembl all work with the chromosome numberings.
- [ ] Check indels in CADD
