### ISSUE TITLE
Website/ftp site move to Monarch

### ISSUE THREAD

**Issue by damiansm** [exomiser/Exomiser#158]
- [x] Need to provision an FTP server from OHSU so we can put the data there.
- [x] Binary releases for exomiser-cli will go on GitHub (https://github.com/exomiser/Exomiser/releases) and the new FTP site (as is currently the case)
- [x] Need to update the current exomiser page (https://monarchinitiative.org/page/exomes) with the stuff on Sanger (http://www.sanger.ac.uk/science/tools/exomiser)

**Comment by julesjacobsen** [comment]
Can probably host data from http://data.monarchinitiative.org/

**Comment by julesjacobsen** [comment]
Added Sanger main page stuff to the README.md (commit b5c31147a23458776c16efc3143b2f34af9fd193)

**Comment by julesjacobsen** [comment]
Data now hosted here: http://data.monarchinitiative.org/exomiser/
