### ISSUE TITLE
chanching source path to org.monarchinitiative.exomiser

### ISSUE THREAD

**Issue by visze** [exomiser/Exomiser#164]
I though I was over this but now I have to write something because the frustration increases every time I look at my exomiser stuff.

You changed all source folders from `de.charite.compbio.exomiser` to `org.monarchinitiative.exomiser` and this breaks everything on every other developments. On my side I had some modifications done for 7.2.1 that I needed. Now I want to bumb them to 8.0 (or prepare it for it) but the source changes crashes everything. I do not have a clue where the modifications etc are made because everything is marked as different! Some work of mine is now wasted..

So please: Do not do such things without telling anyone! This change of the source folders does not have any functionality. It only causes a lot of troubles...

**Comment by drseb** [comment]
Ok, so if I get this right I can start my with my boqa integration again from scratch?! If that is true: Is this how collaborative software dev is supposed to work?

**Comment by damiansm** [comment]
Apologies guys. We are losing track of who is in what meeting when
decisions are made and who is working on what. This whole being spread over
3 countries and time-zones now is not helping. This change came from a
meeting we had with Peter, Melissa etc when we decided we need to start
making Exomiser code and hosting as institute-neutral as possible to try
and stop everyone's translation office scuppering every move we make to
license it how we want and interact with companies. We basically lost
almost $1m of potential funding from Appistry as we could never get all the
institutes to agree.

Jules probably has a clever git or IDE-based solution but none of the
underlying structure under org.monarchinitiative has changed so you should
just be able to move all your code into a new pull of the code, do a global
replace of
de.charite.compbio.exomiser to org.monarchinitiative and everthing will be
back to where you started.

There is no need for anyone to throw away code.
