### ISSUE TITLE
I had this problem with the test  !!! 

### ISSUE THREAD

**Issue by Abdul59** [exomiser/Exomiser#179]
I had faced the same error !!!

I am using OS 10.12.2  12 GB RAM and I installed the exomiser 7.2.1
unzipped the files using
`7z t exomiser 7.2.1`
and the command I used :
`java -Xms2g -Xmx4g -jar exomiser-cli-7.2.1.jar --analysis NA19722_601952_AUTOSOMAL_RECESSIVE_POMP_13_29233225_5UTR_38.yml
`
Any suggestions !?

WARNING: Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'connection' defined in class de.charite.compbio.exomiser.cli.config.DataSourceConfig: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public java.sql.Connection de.charite.compbio.exomiser.cli.config.DataSourceConfig.connection()] threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class de.charite.compbio.exomiser.cli.config.DataSourceConfig: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public javax.sql.DataSource de.charite.compbio.exomiser.cli.config.DataSourceConfig.dataSource()] threw exception; nested exception is java.lang.RuntimeException: Fail-fast during pool initialization
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:601)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1113)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1008)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:505)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:229)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:725)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
	at de.charite.compbio.exomiser.cli.Main.setUpApplicationContext(Main.java:117)
	at de.charite.compbio.exomiser.cli.Main.setup(Main.java:90)
	at de.charite.compbio.exomiser.cli.Main.run(Main.java:78)
	at de.charite.compbio.exomiser.cli.Main.main(Main.java:74)
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public java.sql.Connection de.charite.compbio.exomiser.cli.config.DataSourceConfig.connection()] threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class de.charite.compbio.exomiser.cli.config.DataSourceConfig: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public javax.sql.DataSource de.charite.compbio.exomiser.cli.config.DataSourceConfig.dataSource()] threw exception; nested exception is java.lang.RuntimeException: Fail-fast during pool initialization
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:188)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:590)
	... 16 more

**Comment by visze** [comment]
I guess it is a problem with the data folder you need for running exomiser.  You have to download the distribution and the data zip. and extract it both in the same location. So then you will have a folder `exomiser-cli-7.2.1` which should include the jar file `exomiser-cli-7.2.1.jar ` and a folder called `data`.

Sorry the mac installation seems to be incomplete in the online manual `http://exomiser.github.io/Exomiser/manual/7/installation/`

**Comment by julesjacobsen** [comment]
I assume this is OK now @Abdul59 ? Re-open if not.

**Comment by abdul1983** [comment]
unfortunately I am stuck !!! sorry for not following up 

what I have noticed the files in the data directory are empty ?! it could the problem from the 7z  ?? 
what you think ? 


`Abdulelahs-iMAC:data AbdulBenIssa$ ls -l
total 17960
-rw-r--r--  1 AbdulBenIssa  staff        0 Jan  5  2016 InDels.tsv.gz
-rw-r--r--  1 AbdulBenIssa  staff        0 Jan  5  2016 InDels.tsv.gz.tbi
-rw-r--r--  1 AbdulBenIssa  staff      140 Jan  5  2016 Pfeiffer-quartet.ped
-rw-r--r--  1 AbdulBenIssa  staff  9188882 Jan  5  2016 Pfeiffer.vcf
-rw-r--r--  1 AbdulBenIssa  staff        0 Jan  5  2016 remmData.tsv.gz
-rw-r--r--  1 AbdulBenIssa  staff        0 Jan  5  2016 remmData.tsv.gz.tbi
-rw-r--r--  1 AbdulBenIssa  staff        0 Jan  5  2016 whole_genome_SNVs.tsv.gz
-rw-r--r--  1 AbdulBenIssa  staff        0 Jan  5  2016 whole_genome_SNVs.tsv.gz.tbi
Abdulelahs-iMAC:data AbdulBenIssa$ 
`

**Comment by julesjacobsen** [comment]
You need to download the data too:

https://github.com/exomiser/Exomiser#download-and-installation

**Comment by abdul1983** [comment]
I did but when I extract both files there is nothing. the version am downloading is exomiser-cli-7.2.1-data.zip and exomiser-cli-7.2.1-distribution.zip and I unzipped the files 7z e  exomiser-cli-7.2.1 

 some of the file are empty like you see !! 

-rw-r--r--   1 AbdulBenIssa  staff      3274954 Nov 25  2015 1.out
-rw-r--r--   1 AbdulBenIssa  staff     53356690 Nov 25  2015 10.out
-rw-r--r--   1 AbdulBenIssa  staff     47034899 Nov 25  2015 10_symmetric.out
-rw-r--r--   1 AbdulBenIssa  staff     51666776 Nov 25  2015 11.out
-rw-r--r--   1 AbdulBenIssa  staff     46672153 Nov 25  2015 11_symmetric.out
-rw-r--r--   1 AbdulBenIssa  staff     50087422 Nov 25  2015 12.out
-rw-r--r--   1 AbdulBenIssa  staff     46347924 Nov 25  2015 12_symmetric.out
-rw-r--r--   1 AbdulBenIssa  staff     48697610 Nov 25  2015 13.out
-rw-r--r--   1 AbdulBenIssa  staff     46098565 Nov 25  2015 13_symmetric.out
-rw-r--r--   1 AbdulBenIssa  staff     47371650 Nov 25  2015 14.out
-rw-r--r--   1 AbdulBenIssa  staff     45779368 Nov 25  2015 14_symmetric.out
-rw-r--r--   1 AbdulBenIssa  staff     46097279 Nov 25  2015 15.out
-rw-r--r--   1 AbdulBenIssa  staff     45520677 Nov 25  2015 15_symmetric.out
-rw-r--r--   1 AbdulBenIssa  staff     44962203 Nov 25  2015 16.out
-rw-r--r--   1 AbdulBenIssa  staff     45246799 Nov 25  2015 16_symmetric.out
-rw-r--r--   1 AbdulBenIssa  staff     43899773 Nov 25  2015 17.out
-rw-r--r--   1 AbdulBenIssa  staff     45025162 Nov 25  2015 17_symmetric.out
-rw-r--r--   1 AbdulBenIssa  staff     42919395 Nov 25  2015 18.out
-rw-r--r--   1 AbdulBenIssa  staff     44786007 Nov 25  2015 18_symmetric.out
-rw-r--r--   1 AbdulBenIssa  staff     41951267 Nov 25  2015 19.out
-rw-r--r--   1 AbdulBenIssa  staff     44581777 Nov 25  2015 19_symmetric.out
-rw-r--r--   1 AbdulBenIssa  staff      6919852 Nov 25  2015 1_symmetric.out
-rw-r--r--   1 AbdulBenIssa  staff     43735361 Nov 25  2015 2.out
-rw-r--r--   1 AbdulBenIssa  staff     41163514 Nov 25  2015 20.out
-rw-r--r--   1 AbdulBenIssa  staff     44434192 Nov 25  2015 20_symmetric.out
-rw-r--r--   1 AbdulBenIssa  staff     40113089 Nov 25  2015 2_symmetric.out
-rw-r--r--   1 AbdulBenIssa  staff     63212511 Nov 25  2015 3.out
-rw-r--r--   1 AbdulBenIssa  staff     47126576 Nov 25  2015 3_symmetric.out
-rw-r--r--   1 AbdulBenIssa  staff     64794286 Nov 25  2015 4.out
-rw-r--r--   1 AbdulBenIssa  staff     48396319 Nov 25  2015 4_symmetric.out
-rw-r--r--   1 AbdulBenIssa  staff     63246868 Nov 25  2015 5.out
-rw-r--r--   1 AbdulBenIssa  staff     48732382 Nov 25  2015 5_symmetric.out
-rw-r--r--   1 AbdulBenIssa  staff     61414501 Nov 25  2015 6.out
-rw-r--r--   1 AbdulBenIssa  staff     48624322 Nov 25  2015 6_symmetric.out
-rw-r--r--   1 AbdulBenIssa  staff     59044005 Nov 25  2015 7.out
-rw-r--r--   1 AbdulBenIssa  staff     48226992 Nov 25  2015 7_symmetric.out
-rw-r--r--   1 AbdulBenIssa  staff     57092405 Nov 25  2015 8.out
-rw-r--r--   1 AbdulBenIssa  staff     47802810 Nov 25  2015 8_symmetric.out
-rw-r--r--   1 AbdulBenIssa  staff     55060937 Nov 25  2015 9.out
-rw-r--r--   1 AbdulBenIssa  staff     47426271 Nov 25  2015 9_symmetric.out
-rw-r--r--   1 AbdulBenIssa  staff      3226993 Nov 25  2015 ALL_SOURCES_ALL_FREQUENCIES_genes_to_phenotype.txt
-rw-r--r--@  1 AbdulBenIssa  staff        79062 Jan  5  2016 HikariCP-java6-2.2.5.jar
-rw-r--r--   1 AbdulBenIssa  staff            0 Nov 25  2015 InDels.tsv.gz
-rw-r--r--   1 AbdulBenIssa  staff            0 Nov 25  2015 InDels.tsv.gz.tbi
-rw-r--r--   1 AbdulBenIssa  staff          785 Jan  5  2016 LICENSE.txt
-rw-r--r--   1 AbdulBenIssa  staff      8258566 Nov 25  2015 NA19722_252900_AR_SGSH_1_NONSYNONYMOUS.vcf
-rw-r--r--   1 AbdulBenIssa  staff         4744 Jan  5  2016 NA19722_252900_AR_SGSH_1_NONSYNONYMOUS.yml
-rw-r--r--   1 AbdulBenIssa  staff    135721098 Nov 25  2015 NA19722_601952_AUTOSOMAL_RECESSIVE_POMP_13_29233225_5UTR_38.vcf.gz
-rw-r--r--   1 AbdulBenIssa  staff         4503 Jan  5  2016 NA19722_601952_AUTOSOMAL_RECESSIVE_POMP_13_29233225_5UTR_38.yml
-rw-r--r--   1 AbdulBenIssa  staff          140 Nov 25  2015 Pfeiffer-quartet.ped
-rw-r--r--   1 AbdulBenIssa  staff    130643891 Nov 25  2015 Pfeiffer-quartet.vcf
-rw-r--r--   1 AbdulBenIssa  staff      9188882 Nov 25  2015 Pfeiffer.vcf
-rw-r--r--   1 AbdulBenIssa  staff         9058 Jan  5  2016 README.md
-rw-r--r--@  1 AbdulBenIssa  staff      1933743 Jan  5  2016 ant-1.8.2.jar
-rw-r--r--@  1 AbdulBenIssa  staff        12322 Jan  5  2016 ant-launcher-1.8.2.jar
-rw-r--r--@  1 AbdulBenIssa  staff       302034 Jan  5  2016 antlr4-runtime-4.5.1-1.jar
-rw-r--r--@  1 AbdulBenIssa  staff         4467 Jan  5  2016 aopalliance-1.0.jar
-rw-r--r--   1 AbdulBenIssa  staff         2005 Jan  5  2016 application.properties
-rw-r--r--   1 AbdulBenIssa  staff            0 Jan 25 13:11 caddDao.tsv.gz
-rw-r--r--   1 AbdulBenIssa  staff            0 Jan 25 13:11 caddDao.tsv.gz.tbi
-rw-r--r--@  1 AbdulBenIssa  staff        41123 Jan  5  2016 commons-cli-1.2.jar
-rw-r--r--@  1 AbdulBenIssa  staff       241367 Jan  5  2016 commons-compress-1.4.1.jar
-rw-r--r--@  1 AbdulBenIssa  staff        36888 Jan  5  2016 commons-csv-1.1.jar
-rw-r--r--@  1 AbdulBenIssa  staff       185140 Jan  5  2016 commons-io-2.4.jar
-rw-r--r--@  1 AbdulBenIssa  staff       267634 Jan  5  2016 commons-jexl-2.1.1.jar
-rw-r--r--@  1 AbdulBenIssa  staff        62050 Jan  5  2016 commons-logging-1.1.3.jar
-rw-r--r--@  1 AbdulBenIssa  staff       280983 Jan  5  2016 commons-net-3.3.jar
drwxr-xr-x  10 AbdulBenIssa  staff          340 Jan  5  2016 data
-rw-r--r--@  1 AbdulBenIssa  staff      9020232 Jan  5  2016 ehcache-2.9.0.jar
-rw-r--r--   1 AbdulBenIssa  staff         2634 Jan  5  2016 ehcache.xml
-rw-r--r--   1 AbdulBenIssa  staff        77632 Jan  5  2016 exomiser-cli-7.2.1.jar
-rw-r--r--@  1 AbdulBenIssa  staff       404375 Jan  5  2016 exomiser-core-7.2.1.jar
-rw-r--r--   1 AbdulBenIssa  staff  32954705920 Nov 25  2015 exomiser.h2.db
-rw-r--r--@  1 AbdulBenIssa  staff      6969675 Jan  5  2016 groovy-all-2.4.3.jar
-rw-r--r--@  1 AbdulBenIssa  staff      2308517 Jan  5  2016 guava-19.0.jar
-rw-r--r--@  1 AbdulBenIssa  staff      1605870 Jan  5  2016 h2-1.3.174.jar
-rw-r--r--@  1 AbdulBenIssa  staff        45024 Jan  5  2016 hamcrest-core-1.3.jar
-rw-r--r--   1 AbdulBenIssa  staff      3490930 Nov 25  2015 hp.obo
-rw-r--r--@  1 AbdulBenIssa  staff      1291561 Jan  5  2016 htsjdk-1.143.jar
-rw-r--r--@  1 AbdulBenIssa  staff        96879 Jan  5  2016 ini4j-0.5.1.jar
-rw-r--r--@  1 AbdulBenIssa  staff        38604 Jan  5  2016 jackson-annotations-2.4.1.jar
-rw-r--r--@  1 AbdulBenIssa  staff       225306 Jan  5  2016 jackson-core-2.4.1.jar
-rw-r--r--@  1 AbdulBenIssa  staff      1074275 Jan  5  2016 jackson-databind-2.4.1.jar
-rw-r--r--@  1 AbdulBenIssa  staff       324650 Jan  5  2016 jackson-dataformat-yaml-2.4.1.jar
-rw-r--r--@  1 AbdulBenIssa  staff         6328 Jan  5  2016 jackson-datatype-jdk7-2.4.1.jar
-rw-r--r--@  1 AbdulBenIssa  staff        37424 Jan  5  2016 jama-1.0.3.jar
-rw-r--r--@  1 AbdulBenIssa  staff       279382 Jan  5  2016 jannovar-core-0.16.jar
-rw-r--r--@  1 AbdulBenIssa  staff       198058 Jan  5  2016 jannovar-hgvs-0.16.jar
-rw-r--r--@  1 AbdulBenIssa  staff        32554 Jan  5  2016 jannovar-htsjdk-0.16.jar
-rw-r--r--@  1 AbdulBenIssa  staff        34807 Jan  5  2016 jannovar-inheritance-checker-0.16.jar
-rw-r--r--@  1 AbdulBenIssa  staff       714194 Jan  5  2016 javassist-3.18.1-GA.jar
-rw-r--r--@  1 AbdulBenIssa  staff       220513 Jan  5  2016 javautil-0.0.1.jar
-rw-r--r--@  1 AbdulBenIssa  staff      7487233 Jan  5  2016 jblas-1.2.3.jar
-rw-r--r--@  1 AbdulBenIssa  staff       245039 Jan  5  2016 junit-4.11.jar
drwxr-xr-x  58 AbdulBenIssa  staff         1972 Jan  5  2016 lib
-rw-r--r--@  1 AbdulBenIssa  staff       280928 Jan  5  2016 logback-classic-1.1.3.jar
-rw-r--r--@  1 AbdulBenIssa  staff       455041 Jan  5  2016 logback-core-1.1.3.jar
drwxr-xr-x   3 AbdulBenIssa  staff          102 Feb  4 20:20 logs
-rw-r--r--@  1 AbdulBenIssa  staff      1581066 Jan  5  2016 mockito-all-1.9.5.jar
-rw-r--r--@  1 AbdulBenIssa  staff      1721619 Jan  5  2016 netty-all-4.0.20.Final.jar
-rw-r--r--@  1 AbdulBenIssa  staff       227997 Jan  5  2016 ognl-3.0.6.jar
-rw-r--r--@  1 AbdulBenIssa  staff       576497 Jan  5  2016 ontologizer-0.0.1-SNAPSHOT.jar
-rw-r--r--@  1 AbdulBenIssa  staff       703689 Jan  5  2016 pgjdbc-ng-0.4.jar
drwxr-xr-x   2 AbdulBenIssa  staff           68 Nov 25  2015 phenix
-rw-r--r--   1 AbdulBenIssa  staff     27680860 Nov 25  2015 phenotype_annotation.tab
-rw-r--r--   1 AbdulBenIssa  staff            0 Jan 25 13:10 placeholder.tsv.gz
-rw-r--r--   1 AbdulBenIssa  staff            0 Jan 25 13:10 placeholder.tsv.gz.tbi
-rw-r--r--@  1 AbdulBenIssa  staff       578765 Jan  5  2016 prefuse-beta-20071021.jar
-rw-r--r--   1 AbdulBenIssa  staff  13459209012 Nov 25  2015 remmData.tsv.gz
-rw-r--r--   1 AbdulBenIssa  staff      2675517 Nov 25  2015 remmData.tsv.gz.tbi
-rw-r--r--   1 AbdulBenIssa  staff    558364613 Nov 25  2015 rw_string_9_05.gz
-rw-r--r--   1 AbdulBenIssa  staff        58293 Nov 25  2015 rw_string_9_05_id2index.gz
-rw-r--r--@  1 AbdulBenIssa  staff        29257 Jan  5  2016 slf4j-api-1.7.7.jar
-rw-r--r--@  1 AbdulBenIssa  staff       269295 Jan  5  2016 snakeyaml-1.15.jar
-rw-r--r--@  1 AbdulBenIssa  staff       990264 Jan  5  2016 snappy-java-1.0.3-rc3.jar
-rw-r--r--@  1 AbdulBenIssa  staff       359023 Jan  5  2016 spring-aop-4.1.1.RELEASE.jar
-rw-r--r--@  1 AbdulBenIssa  staff       703685 Jan  5  2016 spring-beans-4.1.1.RELEASE.jar
-rw-r--r--@  1 AbdulBenIssa  staff      1026617 Jan  5  2016 spring-context-4.1.1.RELEASE.jar
-rw-r--r--@  1 AbdulBenIssa  staff       177246 Jan  5  2016 spring-context-support-4.1.1.RELEASE.jar
-rw-r--r--@  1 AbdulBenIssa  staff      1004360 Jan  5  2016 spring-core-4.1.1.RELEASE.jar
-rw-r--r--@  1 AbdulBenIssa  staff       249660 Jan  5  2016 spring-expression-4.1.1.RELEASE.jar
-rw-r--r--@  1 AbdulBenIssa  staff       428320 Jan  5  2016 spring-jdbc-4.1.1.RELEASE.jar
-rw-r--r--@  1 AbdulBenIssa  staff       501832 Jan  5  2016 spring-test-4.1.1.RELEASE.jar
-rw-r--r--@  1 AbdulBenIssa  staff       252352 Jan  5  2016 spring-tx-4.1.1.RELEASE.jar
-rw-r--r--   1 AbdulBenIssa  staff         1436 Jan  5  2016 template.settings
-rw-r--r--   1 AbdulBenIssa  staff          287 Jan  5  2016 test-analysis-batch.txt
-rw-r--r--   1 AbdulBenIssa  staff         3809 Jan  5  2016 test-analysis-exome.yml
-rw-r--r--   1 AbdulBenIssa  staff         4215 Jan  5  2016 test-analysis-genome.yml
-rw-r--r--   1 AbdulBenIssa  staff           83 Jan  5  2016 test-batchFiles.txt
-rw-r--r--   1 AbdulBenIssa  staff         1510 Jan  5  2016 test-hiphive.settings
-rw-r--r--   1 AbdulBenIssa  staff         1511 Jan  5  2016 test-multisample.settings
-rw-r--r--   1 AbdulBenIssa  staff         1508 Jan  5  2016 test-phenix.settings
-rw-r--r--   1 AbdulBenIssa  staff         1506 Jan  5  2016 test-phive.settings
-rw-r--r--   1 AbdulBenIssa  staff         1481 Jan  5  2016 test-walker.settings
-rw-r--r--   1 AbdulBenIssa  staff         1475 Jan  5  2016 test.settings
-rw-r--r--@  1 AbdulBenIssa  staff       789626 Jan  5  2016 thymeleaf-2.1.3.RELEASE.jar
-rw-r--r--   1 AbdulBenIssa  staff     35232325 Nov 25  2015 ucsc_hg19.ser
-rw-r--r--@  1 AbdulBenIssa  staff       132548 Jan  5  2016 unbescape-1.0.jar
-rw-r--r--   1 AbdulBenIssa  staff            0 Nov 25  2015 whole_genome_SNVs.tsv.gz
-rw-r--r--   1 AbdulBenIssa  staff            0 Nov 25  2015 whole_genome_SNVs.tsv.gz.tbi

**Comment by julesjacobsen** [comment]
Some of the files are meant to be empty. They are optional files you need to get - the CADD tabix files (whole_genome_SNVs.gz, InDels.tsv.gz).

You might want to try setting the ```dataDir``` variable in the application.properties file to point to the directory containing the files you unzipped from the exomiser-cli-7.2.1-data.zip file. e.g.

```
dataDir=/home/AbdulBenIssa/exomiser-cli-7.2.1/data
```
By default this will be blank as exomiser assumes that the data directory is in the same directory as the exomiser-cli-7.2.1.jar file, if everything has been unzipped correctly this will be the case.
