### ISSUE TITLE
Oddity in AR filtering

### ISSUE THREAD

**Issue by damiansm** [exomiser/Exomiser#185]
Diagnostic case fails AR filtering when ran Genomiser:

8	65528447	T	TA	1209.0	PASS	0/1:0/1	0	frameshift_variant	CYP7B1:uc003xvj.2:exon3:c.650dup:p.(Leu217Phefs*4)	CYP7B1	.	.	.	.	.	.	0.0	.	.	.	.	.	0.95	0.47601098	0.95	0.59493154
8	65509264	G	A	1187.0	PASS	0/1:0/1	0	missense_variant	CYP7B1:uc003xvj.2:exon6:c.1456C>T:p.(Arg486Cys)	CYP7B1	.	1.0	1.0	0.0	.	rs116171274	0.118343	0.0599	0.1163	0.0227	0.030537	.	0.011729	0.015314	0.118343	0.006197	.	0.84766847	0.47601098	0.95	0.59493154

Pedigree has 2 affected sibs and only passes AD filter and pheno-match is to an AR condition so gets halved and scores low

**Comment by damiansm** [comment]
If run in FULL mode on a VCF containing these 2 variants and a pedigree with 2 affected sibs then can see they fail the Inheritance filter
analysis:
    vcf: test.vcf
    ped: test.ped
    modeOfInheritance: AUTOSOMAL_RECESSIVE
    analysisMode: FULL
    geneScoreMode: RAW_SCORE
    hpoIds: ['HP:0007256','HP:0001257']
    frequencySources: [
        THOUSAND_GENOMES,
        ESP_AFRICAN_AMERICAN, ESP_EUROPEAN_AMERICAN, ESP_ALL,
        EXAC_AFRICAN_INC_AFRICAN_AMERICAN, EXAC_AMERICAN,
        EXAC_SOUTH_ASIAN, EXAC_EAST_ASIAN,
        EXAC_FINNISH, EXAC_NON_FINNISH_EUROPEAN,
        EXAC_OTHER
        ]
    pathogenicitySources: [POLYPHEN, MUTATION_TASTER, SIFT, REMM]
    steps: [
                hiPhivePrioritiser: {},
        priorityScoreFilter: {priorityType: HIPHIVE_PRIORITY, minPriorityScore: 0.501},
        regulatoryFeatureFilter: {},
        frequencyFilter: {maxFrequency: 5.0},
        pathogenicityFilter: {keepNonPathogenic: true},
        inheritanceFilter: {},
        omimPrioritiser: {},
    ]
outputOptions:
    outputPassVariantsOnly: false
    numGenes: 0
    outputPrefix: results/LP2000261-DNA_E06_genomiser_AUTOSOMAL_RECESSIVE
    outputFormats: [TSV-GENE, TSV-VARIANT, HTML]

FAM1	LP2000261-DNA_E06	0	0	2	2
FAM1	LP2000261-DNA_F02	0	0	1	2

**Comment by damiansm** [comment]
Running it as a single sample query with just the first row in the ped file works fine and passes the filter. Does Jannovar handle multi-affected properly?

**Comment by damiansm** [comment]
Max has submitted a bug report to Jannovar

**Comment by visze** [comment]
bug is solved in the actual jannovar development version. See pull request https://github.com/charite/jannovar/pull/322

**Comment by julesjacobsen** [comment]
Nice one. Any idea when this will make it into the 0.21 release?

**Comment by visze** [comment]
now!

**Comment by damiansm** [comment]
Confirmed fixed in latest dev version
