### ISSUE TITLE
hg38 switch

### ISSUE THREAD

**Issue by julesjacobsen** [exomiser/Exomiser#187]
Allow users to use either hg37 or hg37 coordinates.

**Comment by damiansm** [comment]
Consider using Gnomad as an Exac replacement when we do this as contains all - ? if on 38 yet

**Comment by julesjacobsen** [comment]
Yes, gnomAD looks promising. Didn't realise it was ready. Will check it out.

**Comment by damiansm** [comment]
yes paper came out and has a browser. looks good

**Comment by julesjacobsen** [comment]
Bummer - according to their [FAQ](http://gnomad.broadinstitute.org/faq) they are using hg37. Otherwise it looks pretty much perfect as it combines ExAC, ESP and 1000 genomes data with a bunch more.

**Comment by mellybelly** [comment]
@cmungall @TomConlin we should be updating Exomiser and SciGraph/Dipper at same time?

**Comment by pnrobinson** [comment]
Hi everybody,
can we speak about integrating this
https://www.ncbi.nlm.nih.gov/pubmed/27964746
into the hg38 Genomiser?

**Comment by TomConlin** [comment]
@mellybelly ideally sure why not. 
but until we have dipper/scigraph building reliably at will I am reluctant to hold the Exomiser up.

**Comment by damiansm** [comment]
Dahlia@GEL has converted Gnomad and UK10k to hg38 so we may as well use that - I can take care of that for the Exomiser build at least

**Comment by mellybelly** [comment]
Can we use this conversion to inform dipper, maybe good to have @julesjacobsen learn dipper more, perhaps good for other contexts later? @TomConlin ?

**Comment by oleraj** [comment]
Will you have gnomAD for hg19 for those of us who haven't switched to hg38 yet?  It seems at the beginning of this issue that the idea was to provide a flag to choose either hg19 or hg38, so I'm wondering whether this gnomAD feature would be available for hg19 or just for hg38.

**Comment by damiansm** [comment]
Quick list of requirements for b38 release of Exomiser. Please add to it

- [] abilility to flag in yml that VCF is b38 and for code to switch accordingly
- [] b38 version of gnomAD exome and genome MAF datasets to replace 1000g and ExAC - available from GEL now
- [] b38 version of ESP MAF dataset
- [] b38 version of pathogenicty data - available from dbNSFP
- [] b38 version of ReMM file
- [] b38 versions of Jannovar serialised files

**Comment by mellybelly** [comment]
tagging @kshefchek for coordination

**Comment by damiansm** [comment]
@pnrobinson and @visze and @drseb Do you know how we can go about generating a new ReMM score file for b38? Does someone want to start looking into that now as can imagine it could take a while if we are regenerating everything
