### ISSUE TITLE
inheritance-mode options fail silently

### ISSUE THREAD

**Issue by jhl667** [exomiser/Exomiser#189]
Feeding 'x' instead of 'X' to this option results in the parameter being set as "UNINITIALIZED".  It would be helpful for an error to be thrown in this situation.

**Comment by julesjacobsen** [comment]
Yep, this is not ideal. Will add a fix to the upcoming release.

**Comment by julesjacobsen** [comment]
What version are you running? How are you launching the job? Are you using the command-line argument ```-I``` / ```--inheritance-mode``` or using an analysis file with the ```--analysis``` option?

**Comment by jhl667** [comment]
Sorry Jules, I missed your question above.  I was using the most recent version (7.2.3) and the -I option.  Thanks for looking in to this!
