### ISSUE TITLE
Update Jannovar to 0.21

### ISSUE THREAD

**Issue by julesjacobsen** [exomiser/Exomiser#192]
When this is released.

Check: https://github.com/charite/jannovar/releases/latest

Will contain fix for #185

**Comment by visze** [comment]
jannovar v0.21 released!

**Comment by julesjacobsen** [comment]
@visze @holtgrewe - updating from Jannovar 0.20 ->0.21 I get failing tests in exomiser due to a change in the expected variant effect on a test variant. Previously 10-123353298-G-C (1-based, chr-pos-ref-alt variant context) was marked as a ```missense_variant``` ```FGFR2:uc021pzz.1:c.34C>G:p.(Leu12Val)```, but now has been 'down-graded' to a ```synonymous_variant``` ```FGFR2:uc021pzz.1:c.34G>G:p.(=)``` 

```
Expected:
chr10\t123353298\tG\tC\t2.2\tPASS\t0/1\t0\tmissense_variant\tFGFR2:uc021pzz.1:c.34C>G:p.(Leu12Val)\tFGFR2

Actual:
chr10\t123353298\tG\tC\t2.2\tPASS\t0/1\t0\tsynonymous_variant\tFGFR2:uc021pzz.1:c.34G>G:p.(=)\tFGFR2
```
Why might this be happening?

**Comment by holtgrewe** [comment]
Previously, we made the reference base override the transcript base.

In the case of inconsistencies between transcript and reference, we now take the transcript base as this makes things consistent with Mutalyzer etc. In the VCF annotation, this should also trigger a warning.

**Comment by julesjacobsen** [comment]
So that's what `Making the behaviour of overriding transcripts configurable at least in the code, using default to not do this any more` means in the release notes? Looks like I've got a crappy example variant then and should fix this.

So to change back to the original default I should do this?
```java
AnnotationBuilderDispatcher dispatcher = new AnnotationBuilderDispatcher(tmFGFR2, genomeVariant, new AnnotationBuilderOptions(true, true));
```
Doing this still doesn't change the annotation though.

And the warning is the ```WARNING_REF_DOES_NOT_MATCH_TRANSCRIPT``` message in Annotation::getMessages() ?
