### ISSUE TITLE
exomiser website

### ISSUE THREAD

**Issue by visze** [exomiser/Exomiser#193]
Hi,

the exomiser online "demo" version on the sanger website is not available anymore. Will there be any new online version e.g. on the monarch website?

Since I get a lot of request where exomiser is we should publish a press release about it (how you can install it, will there be a future online version etc.) so that the community will not forget exomiser because it is not available (web version) anymore.

**Comment by julesjacobsen** [comment]
No. Yes. Good idea!

This is one of the things I need to do - thanks for reminding me, Max. Who's been asking exactly? 

Closing this here as it duplicates issue #180.
