### ISSUE TITLE
Why remove "SPLICE_REGION_VARIANT" by default?

### ISSUE THREAD

**Issue by geocarvalho** [exomiser/Exomiser#197]
Hello, I would like to know why in the default approach, variants with "SPLICE_REGION_VARIANT" flag are removed and "SPLICE_ACCEPTOR_VARIANT" and "SPLICE_DONOR_VARIANT" still there. I mean, what is the meaning of "SPLICE_REGION_VARIANT" in this case, it has more things than just "SPLICE_ACCEPTOR_VARIANT" and "SPLICE_DONOR_VARIANT" there that aren't important?

Sorry if it's an idiot question,
Cheers.

**Comment by pnrobinson** [comment]
Splice region variant is from Sequence Ontology
http://www.sequenceontology.org/miso/current_svn/term/SO:0001630
It is broader than the Splice Accetpro (-1,-2) and sp;lice donor (+1,+2).
Currently the Exomiser prioritises the +1,+2, and -2, -1 variants. The remaining variants are more difficult to reliably assess. This is on our to do list.
