### ISSUE TITLE
Genomiser memory usage

### ISSUE THREAD

**Issue by hirokomatsui** [exomiser/Exomiser#199]
Thank you for providing the great tool.
I'm trying to run Genomiser for 3 WGS (3 siblings, 2 affected by a Mendelian disease). It finished by Momory error when I set the maximum memory as 8GB. Now I'm trying to do with 60GB.
Is there any efficient way to run the tool, such as filtering input VCF, restrict the genomic region, etc.?

**Comment by pnrobinson** [comment]
Have a look at the test-analysis-genome.yml file in the Exomiser distribution.
Probably you want
 analysisMode: PASS_ONLY 
and if that is not enough uncomment (and adjust)
 #intervalFilter: {interval: 'chr10:123256200-123256300'},

Let us know if that helps!

**Comment by hirokomatsui** [comment]
Great, I'll try that. Thanks!

**Comment by julesjacobsen** [comment]
@hirokomatsui, were you able to run your analysis using @pnrobinson suggestions?

**Comment by hirokomatsui** [comment]
Yes, I ran that on the limited region of our interest, and finished successfully.
Thank you for your help!

**Comment by julesjacobsen** [comment]
Cool, glad you got it sorted.
