### ISSUE TITLE
Analysis file hiPhivePrioritiser usage unclear

### ISSUE THREAD

**Issue by garrett-stevens** [exomiser/Exomiser#201]
In looking through the [entry on the hiPhivePrioritiser](http://exomiser.github.io/Exomiser/manual/7/analysis_file_config/#hiphiveprioritiser) in the manual, it discusses the usage of the runParams option to the prioritiser. However, in the example Genomiser YAML analysis file it has this (commented out) line:
```yaml
hiPhivePrioritiser: {diseaseId: 'OMIM:101600', candidateGeneSymbol: FGFR2, runParams: 'human,mouse,fish,ppi'}
```
What are those two additional options (`diseaseId` and `candidateGeneSymbol`)? I couldn't find any documentation on how to use them. I am guessing they are equivalent to providing `--disease-id` and `--candidate-gene` options in the CLI interface. Does that mean the `diseaseId` is converted to HPO terms internally? How does it interact with HPO terms that are specified? How does a candidate gene differ from specifying seed genes to the `exomeWalkerPrioritiser`?

Thanks for any clarification you can give.

**Comment by julesjacobsen** [comment]
They are for benchmarking and will remove any candidate model hits with either this disease id or gene symbol. Don't use it for real diagnosis. This is why it's not mentioned in the manual, although I should probably clarify this. They are, as you suspect the equivalent of using  ```--disease-id``` and ```--candidate-gene``` options in the CLI interface.

This code here explains how the switches are used in the CLI interface:

https://github.com/exomiser/Exomiser/blob/master/exomiser-core/src/main/java/de/charite/compbio/exomiser/core/prioritisers/PriorityFactoryImpl.java#L54-L85

In English, if the HPO terms are not specified then the diseaseId will be used to populate the HPO ids. The diseaseId and candidateGeneSymbol are then used to provide the parameters required by the hiPhivePrioritiser for benchmarking.

The YAML file is purely declarative so if you don't specify the HPO terms in the hpoIds field then no HPO terms will be used in the analysis. Similarly, if you don't explicitly specify the ```diseaseId``` and ```candidateGeneSymbol``` ```hiPhivePrioritiser``` they won't be used. Hopefully this is clearer as you get less unexpected behaviour as happens with the CLI.
