### ISSUE TITLE
HPO terms for multiple affected individuals

### ISSUE THREAD

**Issue by garrett-stevens** [exomiser/Exomiser#202]
When supplying HPO terms in a multi-individual pedigree analysis, is it assumed that the terms apply to just the proband (the first sample in the VCF, as per the release note instructions) or do they apply to any sample marked as "affected" in the PED file? I ask because this could potentially affect which terms I use. Thanks.

**Comment by julesjacobsen** [comment]
It's assumed they are for the proband.
