### ISSUE TITLE
gnomAD replacement of ExAC and 1000g freq data

### ISSUE THREAD

**Issue by damiansm** [exomiser/Exomiser#211]
- Note has 2 new populations relative to ExAC
- Is also divided into exome and genome build which can't be combined easily so will have a lot more new FrequencySources
- Not sure whether to filter out non-PASS variants in the gnomAD downloads. Some of RF fails were in previous ExAc build and GEL is using all for annotation at moment but not yet using gnomAD for filtering
- b38 versions available from Dalia at Gel

**Comment by holtgrewe** [comment]
Hi, what's the road map for the 9.0 release?
