### ISSUE TITLE
ACMG blacklist

### ISSUE THREAD

**Issue by damiansm** [exomiser/Exomiser#216]
Incorporate the 57 gene ACMG blacklist

**Comment by julesjacobsen** [comment]
Blacklist? Where's that?

I've found the secondary findings list:

http://www.nature.com/gim/journal/v19/n2/fig_tab/gim2016190a_ft.html

**Comment by damiansm** [comment]
duplicated

**Comment by your-highness** [comment]
Sorry for commenting on that closed issue but my question relates to this topic:

Is there a way in `exomiser-web`  to analyse these 59 medically actionable genes only (https://www.ncbi.nlm.nih.gov/pubmed/27854360)? A checkbox would be the way to go.

Thanks in advance!

**Comment by damiansm** [comment]
Illumina source for these:

Blacklisted genes are not included for some filters to reduce the noise level. These are 56 pseudogenes, HLA genes, and others that have a high degree of variants called in healthy individuals:
 
COL4A2-AS2, CRIPAK, FCGBP, GOLGA6L2, GOLGA8N, HLA-A, HLA-B, HLA-C, HLA-DMA, HLA-DMB, HLA-DOA, HLA-DOB, HLA-DPA1, HLA-DPB1, HLA-DPB2, HLA-DQA1, HLA-DQA2, HLA-DQB1, HLA-DQB1-AS1, HLA-DQB2, HLA-DRA, HLA-DRB1, HLA-DRB5, HLA-DRB6, HLA-E, HLA-F, HLA-F-AS1, HLA-G, HLA-H, HLA-J, HLA-L, HTT, KRTAP4-7, KRTAP4-8, KRTAP9-6, LILRA6, LILRB3, LINC02081, LRRC37A2, MUC12, MUC16, MUC17, MUC19, MUC2, MUC20, MUC21, MUC3A, MUC4, MUC6, PDE4DIP, PRAMEF2, PRAMEF9, SIRPA, TBC1D3I, UGT1A7, USP17L1

**Comment by damiansm** [comment]
Ignore above - this is a duplicated closed ticket and Jules has already added to the right place!
