### ISSUE TITLE
Invalid Exomiser 8.0 data file

### ISSUE THREAD

**Issue by garrett-stevens** [exomiser/Exomiser#221]
I've having some trouble with the new Exomiser 8.0 data file. I've tried this three times just to be sure it wasn't a problem with my download. Here's what I'm experiencing:

I can download the distribution and data files just fine, but when I run the checksum validation I get:
```bash
$ sha256sum -c exomiser-cli-8.0.0.sha256
exomiser-cli-8.0.0-distribution.zip: OK
exomiser-cli-8.0.0-data.zip: FAILED
```

And if I just ignore that and try to unzip the data file I get this error:
```bash
$ unzip exomiser-cli-8.0.0-data.zip
Archive:  exomiser-cli-8.0.0-data.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of exomiser-cli-8.0.0-data.zip or
        exomiser-cli-8.0.0-data.zip.zip, and cannot find exomiser-cli-8.0.0-data.zip.ZIP, period.
```

Thanks for for any help, and I'm excited to start using this new version!

**Comment by visze** [comment]
Same problem for me!

```
sha256sum -c exomiser-cli-8.0.0.sha256 
exomiser-cli-8.0.0-distribution.zip: OK
exomiser-cli-8.0.0-data.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
```

```
unzip exomiser-cli-8.0.0-data.zip 
Archive:  exomiser-cli-8.0.0-data.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of exomiser-cli-8.0.0-data.zip or
        exomiser-cli-8.0.0-data.zip.zip, and cannot find exomiser-cli-8.0.0-data.zip.ZIP, period.
```

**Comment by damiansm** [comment]
Lets see what Jules says when he comes in. I tested his file yesterday
before he copied it across and all was fine.

Cheers
Damian

**Comment by julesjacobsen** [comment]
Sorry, looks like the upload to the server got corrupted. 
```
sha256sum -c exomiser-cli-8.0.0.sha256
exomiser-cli-8.0.0-distribution.zip: OK
exomiser-cli-8.0.0-data.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
```

re-uploading the data now, but its incredibly slow. Will let you all know when it's done.

**Comment by julesjacobsen** [comment]
Should be OK now - please close this if you've managed to successfully run the ```examples/test-analysis-exome.yml```

**Comment by garrett-stevens** [comment]
Ok, I successfully ran the `examples/test-analysis-exome.yml`. 👍

Just a note, I had to change the incantation suggested in the [README](https://github.com/exomiser/Exomiser/blob/release-8.0.0/exomiser-cli/README.md) from java `-Xms2g -Xmx2g -jar` to `java -Xms2g -Xmx3g -jar` to get it to run without a memory error.

Thanks for everything!

**Comment by julesjacobsen** [comment]
No probs. Thanks for finding the error in the memory setup - this is also fixed now.
