### ISSUE TITLE
Update PhenIX score distributions

### ISSUE THREAD

**Issue by julesjacobsen** [exomiser/Exomiser#230]
https://github.com/Phenomics/ontolib/issues/8

Need to coordinate with phenodigm build to use same HPO version.

**Comment by damiansm** [comment]
We now have the new files to put back in next release and db versions

**Comment by drseb** [comment]
This looks cool. Really cool, right?

**Comment by damiansm** [comment]
Yep - given me something to think about as for ages hiPhive was giving better results so the advice was clear cut. Shows the importance of us keeping files up to date ;-)

**Comment by pnrobinson** [comment]
awesome!

**Comment by damiansm** [comment]
Good news now is both are performing really well on this set. I will do a larger experiment on all GEL cases and let you know. Drilling down into the detail the results are pretty similar between hiPhive and Phenix now in terms of ranks. Phenix loses 3/37 of the top hiPhive hits (ranked 2nd or 4th instead) but gains an extra 5 top hits where hiPhive had ranked the causative gene second

**Comment by damiansm** [comment]
On whole pilot see similar pattern:

Exomiser top,0.66866,0.59259 (224/335) 
Exomiser top 3,0.79701,0.27385 (267/335)  
Exomiser top 5,0.83582,0.17599 (280/335) 

vs for new hiPhive dbs - rerun and out of 335 as well
Exomiser top,0.67164,0.60976 (225/335) +1 rel to phenix
Exomiser top 3,0.77910,0.26497
Exomiser top 5,0.82090,0.16954 (275/335) -5 rel to phenix

**Comment by aiqubo** [comment]
How I Update PhenIX myself? 
We found that none of these genes were on this ALL_SOURCES_ALL_FREQUENCIES_genes_to_phenotype list,as follow
COPA
DCLRE1B
INO80
MAP3K14
UNC93B1
BACH2
DNASE2
RASGRP1
RIPK1
SPPL2A
CARMIL2
CD46
CD70
MYSM1
TICAM1
TLR3
