### ISSUE TITLE
Typo in Pfeiffer-quartet ped

### ISSUE THREAD

**Issue by andrewSharo** [exomiser/Exomiser#231]
I believe the ped file found at https://github.com/exomiser/Exomiser/blob/master/exomiser-cli/src/main/resources/vcf/Pfeiffer-quartet.ped has a typo.  It appears the final row, with patient ID ISDBM322017 has the same mother and father, ISDBM322016.  I believe the 4th column, 4th row should read ISDBM322018 instead of ISDBM322016.  Link to ped file format info: http://www.helsinki.fi/~tsjuntun/autogscan/pedigreefile.html

**Comment by visze** [comment]
Hi Andrew,

you are right! thx for finding this issue. I created a Pull request (#233)

**Comment by julesjacobsen** [comment]
Thank you for the fix @andrewSharo  - this will be included in release 9.0.0 coming very soon.
