### ISSUE TITLE
Mitochondrial inheritance

### ISSUE THREAD

**Issue by damiansm** [exomiser/Exomiser#235]
Jannovar 0.24 will have Peter's mitochondrial inheritance fix incorporated hopefully. Remember to bundle in with release 9.0.0. Tested on GEL positive samples and works as expected and get phenotype matches to appropriate genes from Leigh syndrome.

Remaining issues is for hg19 dbNSFP used the UCSC version of the MT assembl and Ensembl one is different - therefore end up with no path data and a default of 0.6 if using the same version of assembly Ensembl uses e.g. for GEL sample. Not sure how to fix but fixed in hg38

**Comment by damiansm** [comment]
Still waiting on Jannovar so will do a 9.0.1 release when done

**Comment by julesjacobsen** [comment]
Fixed in Release [9.0.1](https://github.com/exomiser/Exomiser/tree/9.0.1)
