### ISSUE TITLE
Allow multiple modes of inheritance

### ISSUE THREAD

**Issue by damiansm** [exomiser/Exomiser#240]
Currently if want to run a sample through all possible modes of inheritance have to do as 5 separate runs with all the slow variant annotation and filtering steps even though caching speeds things up after the first run in a batch.

Refactor code to allow multiple modes of inheritance to be applied at the gene filtering stage with a separate output file as usual

**Comment by julesjacobsen** [comment]
See also #208

**Comment by julesjacobsen** [comment]
More things to do...
- [ ] Enable MOI dependent frequency filtering (will require changes to lots of things)
- [ ] Implement GeneScore Comparator
- [ ] Change Analysis. modeOfInheritance -> Analysis .inheritanceModes 
- [ ] Change OmimPrioritiser to work with multiple MOI by pulling out MOI dependent scoring code into GeneScorer

**Comment by julesjacobsen** [comment]
This is pretty much done. Still a couple of minor issues:

- [ ] Finalise default MOI max MAF cut-offs
- [ ] Remove obsolete OMIM score from genes.tsv or make it work for each individual MOI output
- [ ] Update yaml examples with new inheritanceModes using the default values
- [ ] Update AnalysisParser to convert old scripts to use new inheritanceModes
