### ISSUE TITLE
Interactome INSIDER

### ISSUE THREAD

**Issue by damiansm** [exomiser/Exomiser#251]
Consider using this type of info - see attached.

Tomasz has already done following:
[nmeth.4540.pdf](https://github.com/exomiser/Exomiser/files/1780494/nmeth.4540.pdf)

I downloaded protein-protein interface regions from their website and processed their genomic track slightly. I think the updates make the data more usable and useful (at least for me).

Both the raw downloads and the processed files are on apocrita here:

/data/WHRI-Phenogenomics/resources/organisms/human/INSIDER/

**Comment by julesjacobsen** [comment]
Looks interesting - what are those weird curly things? ;)

Not quite sure where this would fit in with the current PPI stuff as that is based on a random walk. Unless we use the INSIDER data to create a markov 'map' instead of pure random walk?

**Comment by damiansm** [comment]
duplicated
