### ISSUE TITLE
mode of inheritance filtering issues

### ISSUE THREAD

**Issue by broderF** [exomiser/Exomiser#252]
Im using Exomiser with the analysis_mode = FULL and modeOfInheritance = AUTOSOMAL_RECESSIVE.

If i understand it correctly every variant should be annotated with the filter 'inheritance' if the genotype doesnt match the mode of inheritance right?

But in my result list i get some variants for example with this genotype: 1/1:1/1:1/1:1/1:1/1:1/1:1/1:1/1, while there are only 3 affected persons. 

edit: 
with the same config expect different MAF (1,5):
The first run i got an variant annotated with the filters freq;inheritance. The freq of this variant was about 2. In the second run, this variant passes all filters. 

My complete config: 

```
## Exomiser Analysis Template.
# These are all the possible options for running exomiser. Use this as a template for
# your own set-up.
---
analysis:
    vcf: somevcf
    ped: someped
    proband: Indiv1
    # AUTOSOMAL_DOMINANT, AUTOSOMAL_RECESSIVE, X_RECESSIVE or UNDEFINED
    modeOfInheritance: AUTOSOMAL_RECESSIVE
    #FULL, SPARSE or PASS_ONLY
    analysisMode: FULL
    hpoIds: []
    #Possible frequencySources:
    #Thousand Genomes project http://www.1000genomes.org/
    #   THOUSAND_GENOMES,
    #ESP project http://evs.gs.washington.edu/EVS/
    #   ESP_AFRICAN_AMERICAN, ESP_EUROPEAN_AMERICAN, ESP_ALL,
    #ExAC project http://exac.broadinstitute.org/about
    #   EXAC_AFRICAN_INC_AFRICAN_AMERICAN, EXAC_AMERICAN,
    #   EXAC_SOUTH_ASIAN, EXAC_EAST_ASIAN,
    #   EXAC_FINNISH, EXAC_NON_FINNISH_EUROPEAN,
    #   EXAC_OTHER
    frequencySources: [
        THOUSAND_GENOMES,
        ESP_AFRICAN_AMERICAN, ESP_EUROPEAN_AMERICAN, ESP_ALL,
        EXAC_AFRICAN_INC_AFRICAN_AMERICAN, EXAC_AMERICAN,
        EXAC_SOUTH_ASIAN, EXAC_EAST_ASIAN,
        EXAC_FINNISH, EXAC_NON_FINNISH_EUROPEAN,
        EXAC_OTHER
        ]
    #Possible pathogenicitySources: POLYPHEN, MUTATION_TASTER, SIFT, CADD, REMM
    #*WARNING* if you enable CADD, ensure that you have downloaded and installed the CADD tabix files
    #and updated their location in the application.properties. Exomiser will not run without this. 
    pathogenicitySources: [POLYPHEN, MUTATION_TASTER, SIFT]
    #this is the standard exomiser order.
    #all steps are optional
    steps: [ 
        #intervalFilter: {interval: 'chr10:123256200-123256300'}, 
        #geneIdFilter: {geneIds: [12345, 34567, 98765]},
        #failedVariantFilter: {},
        #qualityFilter: {minQuality: 50.0},
        variantEffectFilter: {remove: [UPSTREAM_GENE_VARIANT,
            INTERGENIC_VARIANT,
            REGULATORY_REGION_VARIANT,
            CODING_TRANSCRIPT_INTRON_VARIANT,
            NON_CODING_TRANSCRIPT_INTRON_VARIANT,
            SYNONYMOUS_VARIANT,
            DOWNSTREAM_GENE_VARIANT,
            SPLICE_REGION_VARIANT]},
        #knownVariantFilter: {}, #removes variants represented in the database
        frequencyFilter: {maxFrequency: 1.0},
        pathogenicityFilter: {keepNonPathogenic: true},
        #inheritanceFilter and omimPrioritiser should always run AFTER all other filters have completed
        #they will analyse genes according to the specified modeOfInheritance above- UNDEFINED will not be analysed.
        inheritanceFilter: {},
        #omimPrioritiser isn't mandatory.
        omimPrioritiser: {},
        #priorityScoreFilter: {minPriorityScore: 0.4},
        #Other prioritisers: Only combine omimPrioritiser with one of these.
        #Don't include any if you only want to filter the variants.
        hiPhivePrioritiser: {},
        # or run hiPhive in benchmarking mode: 
        #hiPhivePrioritiser: {runParams: 'mouse'},
        #phivePrioritiser: {}
        #phenixPrioritiser: {}
        #exomeWalkerPrioritiser: {seedGeneIds: [11111, 22222, 33333]}
    ]
outputOptions:
    outputPassVariantsOnly: false
    #numGenes options: 0 = all or specify a limit e.g. 500 for the first 500 results  
    numGenes: 0
    #outputPrefix options: specify the path/filename without an extension and this will be added
    # according to the outputFormats option. If unspecified this will default to the following: 
    # {exomiserDir}/results/input-vcf-name-exomiser-results.html
    # alternatively, specify a fully qualifed path only. e.g. /users/jules/exomes/analysis    
    outputPrefix: analysis_6/results
    #out-format options: HTML, TSV-GENE, TSV-VARIANT, VCF (default: HTML)
    outputFormats: [TSV-GENE, TSV-VARIANT, VCF, HTML]
```

**Comment by julesjacobsen** [comment]
Why are you running it using ```analysisMode: FULL```? This will return everything in your input file, but the variant where all the genotypes are the same should have failed the inheritance mode filter so you'll see that variant will have at least ```'inheritance'``` present in the FILTER column of the VCF or TSV file to indicate it failed the ```inheritanceFilter```. The ones with ```PASS``` have passed the filters you assigned.

**Comment by broderF** [comment]
Yes i just want to play a bit with the data, for example looking for the variants, which didnt pass the variantEffectFilter but every other filter..

Edited Example:
I used the same config in 2 analysis with frequencyFilter: {maxFrequency: 1.0} and frequencyFilter: {maxFrequency: 5.0}.

In the first case (1%) i got a variant with the filter annotation 'freq;inheritance'. In the second case the variant filter for the same variant was annotated with PASS, which is right because the variant should pass the inheritance filter. So in the first case the filter annotation should only be 'freq' i think?

Original Example:
Tried it for version 9.0.1 and 10.0 and its solved in the newest version

**Comment by julesjacobsen** [comment]
OK. In the FULL case we'll include every failed filter. If you just want to see the first failed filter in the FILTER column run SPARSE. But be warned this mode is going to vanish in the next release.

What's wrong with multiple failed filters mentioned in the filter field? This is part of the VCF spec.

**Comment by broderF** [comment]
Sorry if i didnt make that clear. I would like to have filter annotations with multiple failed filters. 

But in this case for me it doesnt make sense, that the filter annotations changes from 'freq;inheritance' to 'PASS' just by increases the allel freq.

**Comment by julesjacobsen** [comment]
You're running it in FULL mode which means each step is run on each variant irrespective of whether or not it passed the previous step. The inheritance filter implementation is such that it is only run on the variants which have passed all other filter steps. So if it failed the frequency it will by default fail the inheritance mode filter. Does this clarify things?

**Comment by broderF** [comment]
So in FULL mode every filter step is executed for every variant irrespective of whether or not it passed the previous filter except the inheritance filter?

**Comment by julesjacobsen** [comment]
Not quite - every filter step is executed for every variant irrespective of whether or not it passed the previous filter. The inheritance filter will simply fail a variant as it didn't pass the other filters.

**Comment by broderF** [comment]
Ok thank you for your answer. What is the reason the inheritance filter fails if the variant didnt't pass for example the frequency filter? And is this unique for the inheritance filter?

**Comment by julesjacobsen** [comment]
Yes, it's unique to the inheritance mode filter. It's basically an optimisation as calculating the inheritance modes for a large set of variants can massively increase CPU and RAM usage and we're not using the results anyway.
