### ISSUE TITLE
Jannovar builds required for every release of phenotype db

### ISSUE THREAD

**Issue by damiansm** [exomiser/Exomiser#253]
Note this is really a Jannovar issue but putting here for now. There are 2 issues:

(i) Jannovar fails to generate a .ser file with the latest Ensembl releases as the cdna file contains versioned Ensembl IDs and the other files don't
(ii) Jannovar uses the latest version of the HGNC file download to assign other IDs including the critical entrezGene IDs to each ENSG based entry in the .ser file. The ENSG ID used for a gene can vary between latest HGNC and the version of Ensembl downloaded leading to no entrezId when running Exomiser and no phenotype matching at ll

The temp solution used in the 1802_variant db builds was:
rm data/hg19/ensembl
rm data/hg38/ensembl
java -Xms4g -Xmx8g -jar jannovar-cli-0.24.jar download -s default_sources.ini -d hg19/ensembl
cd data/hg19/ensembl
perl convert_hgnc_to_b37_ensembl_gene_ids.pl
java -Xms4g -Xmx8g -jar jannovar-cli-0.24.jar download -s default_sources.ini -d hg19/ensembl
java -Xms4g -Xmx8g -jar jannovar-cli-0.24.jar download -s default_sources.ini -d hg38/ensembl
cd data/hg38/ensembl
perl convert_hgnc_to_b38_ensembl_gene_ids.pl
java -Xms4g -Xmx8g -jar jannovar-cli-0.24.jar download -s default_sources.ini -d hg38/ensembl

where the sources in default_sources.ini where changed to:

[hg19/ensembl]
....
gtf=ftp://ftp.ensembl.org/pub/grch37/current/gtf/homo_sapiens/Homo_sapiens.GRCh37.87.gtf.gz
cdna=ftp://ftp.ensembl.org/pub/grch37/current/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh37.cdna.all.fa.gz

[hg38/ensembl]
....
gtf=ftp://ftp.ensembl.org/pub/release-91/gtf/homo_sapiens/Homo_sapiens.GRCh38.91.gtf.gz
cdna=ftp://ftp.ensembl.org/pub/release-91/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz

and logic in perl script is
```perl
use strict;
use warnings;

system("gunzip Homo_sapiens.GRCh37.cdna.all.fa.gz");
open(IN,"Homo_sapiens.GRCh37.cdna.all.fa");
open(OUT,">Homo_sapiens.GRCh37.cdna.all.fa_fixed");

while (my $line = <IN>){
    $line =~ s/\.\d//g;
    print OUT $line;
}
close IN;
close OUT;
system("mv Homo_sapiens.GRCh37.cdna.all.fa_fixed Homo_sapiens.GRCh37.cdna.all.fa");
system("gzip Homo_sapiens.GRCh37.cdna.all.fa");

system("gunzip Homo_sapiens.GRCh37.87.gtf.gz");
my %b37_symbol_to_id;
open(IN,"Homo_sapiens.GRCh37.87.gtf");
while (my $line = <IN>){
    chop $line;
    my @line = split(/\t/,$line);
    next if $line[2] ne 'gene';
    next if $line[0] =~ /PATCH/;
    my $info = $line[8];
    
    $info =~ s/\"//g;
    $info =~ s/\;//g;
    my @info = split(/ /,$info);
    my $gene_id = $info[1];
    my $gene_symbol = $info[5];
    $b37_symbol_to_id{$gene_symbol}{$gene_id} = 1;
    #print "BEFORE $gene_symbol\t$gene_id\n";
}
close IN;
system("gzip Homo_sapiens.GRCh37.87.gtf");

open(IN,"hgnc_complete_set.txt");
open(OUT,">hgnc_complete_set_fixed.txt");
while (my $line= <IN>){
    #chop $line;
    my @line = split(/\t/,$line);
    my $gene_symbol = $line[1];
    my $gene_id = $line[19];
    if ($b37_symbol_to_id{$gene_symbol} && !$b37_symbol_to_id{$gene_symbol}{$gene_id}){# && $gene_id ne $b37_symbol_to_id{$gene_symbol}){
        foreach my $new_id (keys %{$b37_symbol_to_id{$gene_symbol}}){
            print "$gene_symbol\t$gene_id\t$new_id\n";#.$b37_symbol_to_id{$gene_symbol}{$new_id}."\n";
            $line[19] = $new_id;#$b37_symbol_to_id{$gene_symbol}{$new_id};
        }
    }
    print OUT join("\t",@line);
}
close IN;
close OUT;
system("mv hgnc_complete_set_fixed.txt hgnc_complete_set.txt");
```

**Comment by pnrobinson** [comment]
@damiansm I will add this to the Jannovar tracker, it should be easy to fix.

**Comment by damiansm** [comment]
Also we need to build jannovar files and phenotype db at same time as entrezGene IDs for a gene can change e.g. UPK3B changed from 80761 to 105375355 so miss pheno hits when using latest jannovar files with my phenotype db build from a couple of weeks ago. Also symbols can change but should be less of an issue as Exomiser just uses jannovar as a single truth set

**Comment by damiansm** [comment]
Also Jules has to convert the files to the new protobuf format for an (optional) speed performance. This is now done and tested for the 1810_variant dbs.

**Comment by damiansm** [comment]
See https://github.com/charite/jannovar/issues/399#issuecomment-462312273. Manuel should have fixed (i) and (ii) above

**Comment by damiansm** [comment]
Tested on whole Gel test set and all all fine apart from one example involving KTM2B where there the entrezGene link to 9757 was lost and therefore got no phenotype score etc. Manuel has a fix and will push soon.

**Comment by julesjacobsen** [comment]
Awaiting resolution of Jannovar issue https://github.com/charite/jannovar/issues/399 and pull request https://github.com/charite/jannovar/pull/433

**Comment by damiansm** [comment]
Tested Manuels new fix and addresses all issues now
