### ISSUE TITLE
Replace OutputOptions.outputPassVariantsOnly option with outputContributingVariantsOnly

### ISSUE THREAD

**Issue by julesjacobsen** [exomiser/Exomiser#256]
The current output options make little sense in relation to the  modes and the contributing variants, plus produce confusing output.

(```FULL```  + ```outputPassVariantsOnly: true```) is a really CPU, IO and memory-intensive way of running ```PASS_ONLY```.

The output files from (```PASS_ONLY``` + ```outputPassVariantsOnly: true```)  == (```PASS_ONLY``` + ```outputPassVariantsOnly: false```). 

What's more relevant are the contributing variants, so enabling this instead of pass only variants makes more sense:

(```FULL```  + ```outputContributingVariantsOnly: true```) == (```PASS_ONLY``` + ```outputContributingVariantsOnly: true```)

So contributing variants are a subset of pass only which is a subset of full.

Need to decide whether the ```outputContributingVariantsOnly``` default is true or false. It's the least confusing output option, but if someone runs ```FULL``` or ```PASS_ONLY``` and the default is ```outputContributingVariantsOnly: true``` there will be no difference in the output.

**Comment by damiansm** [comment]
This was fixed in release 11.0.0
