### ISSUE TITLE
exomiser does not output gnomAD and 1KG frequency annotations

### ISSUE THREAD

**Issue by seru71** [exomiser/Exomiser#258]
Hi,

After downloading exomiser 10.0.1 and 1802_hg19 dataset, I ran the NA19722_601952_AUTOSOMAL_RECESSIVE_POMP_13_29233225_5UTR_38 example. Everything went fine, except that in the output several variant frequency annotations were missing. Here is the header for _AD.variants.tsv file:

#CHROM  POS     REF     ALT     QUAL    FILTER  GENOTYPE        COVERAGE        FUNCTIONAL_CLASS        HGVS    EXOMISER_GENE   CADD(>0.483)    POLYPHEN(>0.956|>0.446) MUTATIONTASTER(>0.94)   SIFT(<0.06)
     REMM    DBSNP_ID        MAX_FREQUENCY   DBSNP_FREQUENCY EVS_EA_FREQUENCY        EVS_AA_FREQUENCY        EXAC_AFR_FREQ   EXAC_AMR_FREQ   EXAC_EAS_FREQ   EXAC_FIN_FREQ   EXAC_NFE_FREQ   EXAC_SAS_FREQ
   EXAC_OTH_FREQ   EXOMISER_VARIANT_SCORE  EXOMISER_GENE_PHENO_SCORE       EXOMISER_GENE_VARIANT_SCORE     EXOMISER_GENE_COMBINED_SCORE    CONTRIBUTING_VARIANT

GNOMAD, 1KG, UK10K are specified in the YAML file, but missing from the output. Should I download these frequency databases separately? 

Cheers,

**Comment by julesjacobsen** [comment]
> GNOMAD, 1KG, UK10K are specified in the YAML file, but missing from the output. Should I download these frequency databases separately?

No, you don't need to do that, they are part of the existing distribution. You can see them in the HTML output.

Given the inflexibility of TSV we're considering a new JSON output in the upcoming release which will contain the newer data sources.

**Comment by julesjacobsen** [comment]
Correct, TSV doesn't contain all the data. How are you trying to use this? Is it part of an informatics pipeline or for display to clinicians? As I said previously we're looking at JSON as this is more amenable to having data added without breaking other people's parsers. What would be your preference?

**Comment by seru71** [comment]
I have been trying it out attracted by the possibility of annotating variants with the REMM score. Looked at the tsv first, because it was easier to filter the variants there.

JSON is great for programmatic use, but not so convenient to manipulate using Unix shell. Having both would be awesome.

**Comment by julesjacobsen** [comment]
Do you *just* want the REMM score for a variant? If so [tabix](http://www.htslib.org/doc/tabix.html) would be a better choice than running the whole of exomiser. Running exomiser just to annotate variants isn't really what it was designed to do as it will take a lot of time and RAM to do this.

**Comment by visze** [comment]
Maybe for annotating variants without prioritization jannovar might be a
better choice.

Jannovar can annotate several other sources like dbNSFP. ReMM directly is
not implemented yet but, if needed, I can easily add this function. Becaus
ReMM just needs the position in the genome it is always the fastest to use
directly tabix (without any alt allele comparison which will be needed if
you use CADD for example).



Jules Jacobsen <notifications@github.com> schrieb am Fr., 20. Apr. 2018,
17:01:

**Comment by DGMichael** [comment]
Json would be a great output format for us.

**Comment by seru71** [comment]
@julesjacobsen annotating with REMM wasn't the sole purpose. Also wanted to try it out on a few undiagnosed WGS samples where we're looking for some new clues. 

I agree that using it to annotate variants with one score is an overkill. For annotation I have been using mostly Annovar, so I could easily convert REMM db into an Annovar annotation file. Using Exomiser I killed two birds with one stone:)

**Comment by julesjacobsen** [comment]
@seru71 Cool, that's exactly the right use-case!
@DGMichael good to hear.

**Comment by julesjacobsen** [comment]
This is now possible with the new TSV_VARIANT output file:

| #RANK | ID | GENE\_SYMBOL | ENTREZ\_GENE\_ID | MOI | P-VALUE | EXOMISER\_GENE\_COMBINED\_SCORE | EXOMISER\_GENE\_PHENO\_SCORE | EXOMISER\_GENE\_VARIANT\_SCORE | EXOMISER\_VARIANT\_SCORE | CONTRIBUTING\_VARIANT | WHITELIST\_VARIANT | VCF\_ID | RS\_ID | CONTIG | START | END | REF | ALT | CHANGE\_LENGTH | QUAL | FILTER | GENOTYPE | FUNCTIONAL\_CLASS | HGVS | EXOMISER\_ACMG\_CLASSIFICATION | EXOMISER\_ACMG\_EVIDENCE | EXOMISER\_ACMG\_DISEASE\_ID | EXOMISER\_ACMG\_DISEASE\_NAME | CLINVAR\_VARIATION\_ID | CLINVAR\_PRIMARY\_INTERPRETATION | CLINVAR\_STAR\_RATING | GENE\_CONSTRAINT\_LOEUF | GENE\_CONSTRAINT\_LOEUF\_LOWER | GENE\_CONSTRAINT\_LOEUF\_UPPER | MAX\_FREQ\_SOURCE | MAX\_FREQ | ALL\_FREQ | MAX\_PATH\_SOURCE | MAX\_PATH | ALL\_PATH |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 1 | 13-29233225-TC-T\_AR | POMP | 51371 | AR | 0.0000 | 0.9981 | 0.9960 | 1.0000 | 1.0000 | 1 | 1 | null | rs112368783 | 13 | 29233225 | 29233226 | TC | T | -1 | 100.0000 | PASS | 1\|1 | upstream\_gene\_variant | POMP:ENST00000380842.4:: | UNCERTAIN\_SIGNIFICANCE | PP4,PP5 | OMIM:601952 | Keratosis linearis with ichthyosis congenita and sclerosing keratoderma | 116 | PATHOGENIC | 1 | 0.6348 | 0.36 | 1.192 | GNOMAD\_G\_NFE | 0.012968486 | GNOMAD\_G\_NFE=0.012968486 | REMM | 0.993 | REMM=0.993 |
