### ISSUE TITLE
--help doesn't not work

### ISSUE THREAD

**Issue by FedikZe** [exomiser/Exomiser#264]
Dear all,
Please could you help me? I need to show help options. I would like to automate all processes in my pipeline, but *.yml file is not good option for me. I would like to use command line definition. Is it possible to do that? And if it is, could you please send me manual for that? Thank you.

**Comment by julesjacobsen** [comment]
You can use the --analysis option and use a template yaml file with placeholders to fill in the relevant input and output fields.

**Comment by FedikZe** [comment]
Ok, that is possible. Thank you. But could please for me copy the what do you after command java -jar exomiser{version}_cli.jar? I have some problem with installation or I do not know. Help doesn't work and if I would like to run exomiser, I have to be in exomiser folder.
Thank you and best

**Comment by julesjacobsen** [comment]
Add `--spring.config.location=/full/path/to/your/exomiser/install/directory` as the last argument.

**Comment by julesjacobsen** [comment]
Thread is dead.
