### ISSUE TITLE
genomiser noncoding prioritization

### ISSUE THREAD

**Issue by PedroBarbosa** [exomiser/Exomiser#268]
Hello,

I'm trying to get predictions in non coding regions using genomiser, but as a lot of filters are applied, many few variants are actually kept for furhter analysis. Even when I set analysis mode to FULL, not many variants appear to be scored. I also tried to increase the MAFs of the inheritanceModes (as well as leave them entirely empty), and do not provide hpoIds. Basically, I want to be as lenient as possible. Is there a way to skip all these operations and just get predictions within those regions ? 

Is it acceptable just to look for the ReMM probabilities file, and extrapolate a pathogenicity likelihood based on that? Which threshold you consider valid , 0.5 ?

Thanks in advance,
PedroBarbosa

**Comment by visze** [comment]
Hi Pedro

I will try to answer your second question (ReMM score):

In Genomiser we use a ReMM score cutoff of 0.5. In general this is really low but the most power comes from the phenotypes, resulting in small sets of genes and therefore also a smaller sets of variants.

Of course you can directly use only the ReMM score. But on a complete Genome (probably after an allele frequency filter with gnomAD + removing coding regions) a cutoff 0.5 is really low and you will be left with thousands of variants. Here I would recommend to use 0.984 (max F1-score) or 0.969 (max F2-score). This will generate smaller numbers of variants with high confidence.

**Comment by PedroBarbosa** [comment]
Thank you for the suggestions, will give it a try. Indeed, I see now there's plenty of high confidence non-coding positions in the genome, I'll see how that goes.

Best,
Pedro
