### ISSUE TITLE
Dealing with HP IDs from old releases

### ISSUE THREAD

**Issue by damiansm** [exomiser/Exomiser#270]
HPO terms can get made obsolete and become alt_ids for a diff term in newer releases: @pnrobinson @drseb Is it always guaranteed if you have a term in an older version of HPO that it will be present in the newer release as either a genuine ID or as an obsolete ID and for the latter, do these always become alt_ids of another term?

Currently we build our Exomiser phenotype db off only the non-obsolete terms so people using data collected using an older version could miss matches e.g. the 13/4/17 release used by GEL has 12358 IDs inc 132 obsolete terms and all these are in the Feb 2018 version of HPO which contains 13427 IDs inc 186 obsolete and 49 13/4/17 IDs have now become obsolete and would be ignored if used by the latest Exomiser

Possible solutions:
(1) match the Exomiser database to the version of HPO used for data collection - not very viable except for special cases
(2) include an alt_id lookup table to convert input HPO terms where appropriate
(3) include the obsolete IDs in the Exomiser database but would be hard as the relationships are removed

**Comment by pnrobinson** [comment]
The obsoleted term ids **always** become alt ids of other terms. There is a function in phenol that runs like this

TermId obsoleteId = ...

TermId currentId = ontology.getPrimaryId(obsoleteId)


We should probably use this as a part of the data ingest procedure.
---

The information in this email, including attachments, may be confidential and is intended solely for the addressee(s). If you believe you received this email by mistake, please notify the sender by return email as soon as possible.

**Comment by damiansm** [comment]
Great - was hoping that was an absolute rule. @julesjacobsen Lets brainstorm how to make Exomiser more backwards-compatible with old HPO versions. Guess only 1-2% of IDs are obsolete and they don't increase too fast so will not affect analysis too much but still .... I think we just need an alt_ids lookup table in the db that gets checked when we read in patient HPOs and converts if necessary

**Comment by damiansm** [comment]
This is the version we used for the 1811 build

**Comment by julesjacobsen** [comment]
Will do this:
- [ ] Add current version to 1811_phenotype.zip
- [ ] Update phenotype-data to add file on next build
- [ ] Add checks to user input to convert obsolete to latest terms

**Comment by damiansm** [comment]
Dev now has commit to test for this conversion

**Comment by julesjacobsen** [comment]
I've implemented this by parsing the HPO each time on start-up. This isn't necessarily the best solution. It's backwards compatible-ish as the new HPO can easily be added to an old data-release. But it might be better to store the data in the database in a new table/tables. At least as it is currently implemented it should work.

**Comment by julesjacobsen** [comment]
Mostly committed in  c00c8075ae62676bfe1e97deed16cdc53f5801ac. This requires a new phenotype database build and does not rely on loading an HPO file each time.

Basically added an alt_ids table as you first suggested and the user is warned when an obsolete term is replaced by a current one.

**Comment by damiansm** [comment]
Tested this on some real cases and works perfectly

**Comment by PabloBotas** [comment]
Hi! Trying to avoid opening a new issue here.
What about new HPO terms? I assume there is very little to be done there, but where can we find the HPO release each Exomiser release is using?
