### ISSUE TITLE
Multisample vcf issue

### ISSUE THREAD

**Issue by OskarSchnappauf** [exomiser/Exomiser#271]
Dear exomiser team,

I have some trouble processing multi-vcfs with the new exomiser/10.0.1 release. Single sample vcfs work fine, but somehow the multi don't work. I generate my multi-vcfs with the GATK GenotypeGVCFs tool.
Unfortunately I can't figure out what exactly the issue is. Please find attached one of my logs. I would highly appreciate if you could have a look. Thank you so much!
Oskar
[slurm-4480686.txt](https://github.com/exomiser/Exomiser/files/2153352/slurm-4480686.txt)

**Comment by julesjacobsen** [comment]
it looks like you have an integer as your proband identifier - this should be a string. 

e.g.
```yaml
    proband: 2
```
should be
```yaml
    proband: '2'
```

**Comment by OskarSchnappauf** [comment]
Hi Jules,

thanks so much! I was trying for days to figure out what's the problem. That means, when the sample name is a number, i.e. 1234 then you need to add the '1234'. If not, then just the sample name. Is that correct?

**Comment by julesjacobsen** [comment]
@OskarSchnappauf yes - to make it consistent you could wrap any sample identifier in the ```'```s. So long as it matches the proband's sample identifier in the VCF file.

e.g. 

```yaml
proband: '2'
#or
proband: 'SAMPLE0002'
```

**Comment by julesjacobsen** [comment]
@OskarSchnappauf can you close this if you're sorted now, please.

**Comment by OskarSchnappauf** [comment]
Dear exomiser team,

thank you so much for your quick support and help. Everything is running smoothly now!
Oskar

**Comment by julesjacobsen** [comment]
Excellent. You're welcome!
