### ISSUE TITLE
ClinPred

### ISSUE THREAD

**Issue by damiansm** [exomiser/Exomiser#272]
When scores are publically available investigate performance - incorporates freq into score so woudl be a good replacement for us

One possibility would be to not incorporate freq into the default score calculations i.e. LOF that passes filters is always 1. For missense use ClinPred

**Comment by julesjacobsen** [comment]
**ClinPred: Prediction Tool to Identify Disease-Relevant Nonsynonymous Single-Nucleotide Variants**
https://doi.org/10.1016/j.ajhg.2018.08.005

Missense only variants, similar to REVEL

> In summary, we have developed an ensemble classifier for predicting disease relevance of missense SNVs, using a combination of two different machine learning algorithms and incorporating several popular pathogenicity predictors, along with population allele frequencies, as component features. Our classifier is specifically designed to predict pathogenicity of variants that are causative for Mendelian disease.

ClinPred data: https://sites.google.com/site/clinpred/

**Comment by damiansm** [comment]
The TEST pathogenicity scores should work now – I’ve added the latest build (exomiser-cli-12.0.0-SNAPSHOT) to  /data/WHRI-Phenogenomics/projects/Jules/ along with a compatible ClinPred file.
 
To get it working you’ll need to:
1. Have a bgzipped tabix-indexed file to hand in the format defined below.
2. Add exomiser.hg19.test-pathogenicity-score-path=full/path/to/ClinPred.txt.gz to the application.properties file
3. Add TEST to the pathogenicityScources: [] in the analysis.yml file
 
Then run as usual.
 
Test file format must be:
 
* The file should be defined as tab-delimited lines in 'VCF-lite' format with the corresponding requirements e.g.:
*
* #CHR   POS REF ALT SCORE
* 10      123279555       G       A       0.947294473648071
* 10      123279555       G       C       0.993917524814606
* 10      123279555       G       T       0.980554223060608
*
* Where:
* CHR - Chromosomes must be in the form [1-22,X,Y,M].
* POS - Positions must be 1-based.
* ALT - alternate allele column must only contain one allele per line.
* SCORE - Scores must be normalised to the range 0.0-1.0 such that 0.0 is considered benign and 1.0 pathogenic.
*
* Files can be created using the command 'tabix -b 2 -c # -s 1'
 
Currently the new scores can be seen in the HTML and JSON output.

**Comment by damiansm** [comment]
Tested now. See future ML issue for next steps
