### ISSUE TITLE
Avoiding the usual suspect genes

### ISSUE THREAD

**Issue by damiansm** [exomiser/Exomiser#274]
Genome Med paper  that describes the classical genes that are enriched for variants and to be treated with caution for genuine size-reason e.g. TTN and mis-aligned e.g. MUC16

**Comment by your-highness** [comment]
Also `ESRRA`, `KCNJ11`, `HLA-*` und `MUC-*` are recurrent usual suspects.

Sometimes even variants are usual suspects, _e.g._ `NOTCH2` `1:120572547T>C` or `1:120572572C>T`

**Comment by LeahBrooksbank** [comment]
@damiansm do you have the link to the paper please? I have also experienced this problem (mostly MUC, HLA and TTN) and want to discuss it in my thesis, however it only seems to be discussed very briefly (if at all) in any of the literature that I have found thus far. 

Thank you in advance!
