### ISSUE TITLE
Potental issues with annotating overlapping genes

### ISSUE THREAD

**Issue by damiansm** [exomiser/Exomiser#294]
195-1 | In  tiering variants gets annotated to AC092143.1 and TUBB3 (overlapping  Ensembl genes) and latter results in a tier 2 diagnosis on latest ID  panel. For Exomiser gets former only and this has no phenotype matches  at all. Probably if annotated to TUBB3 would have been a top candidate
-- | --

**Comment by damiansm** [comment]
Delve into code that is selecting from multiple Jannovar annotations based on most damaging. Do these two both get equally damaging? Add extra logic to select the one that "looks" more like an HGNC gene symbol and likely to have a phenotype match

**Comment by damiansm** [comment]
Can no longer find this example in latest test set so either resolved or wait until problem emerges again

**Comment by holtgrewe** [comment]
@damiansm Yes, this is the annotation in the VCF file. When using Jannovar as a library, you should select the most pathogenic variant for each gene, which is available from the API. In fact, all predictions for all transcripts are made for each variant.

**Comment by damiansm** [comment]
Put this back on the 13.0.0 roadmap. It comes up everytime during ISO accreditation so it is annoying!

**Comment by julesjacobsen** [comment]
I think the way to deal with this is to group the annotations by gene, then pick the most deleterious for the gene in hand.

**Comment by damiansm** [comment]
Yes - if there is a way of doing that and then adding the variant
potentially multiple times to several gene (most deleterious annotation PER
gene) that would definitely work

**Comment by damiansm** [comment]
Tested a RC that now produces multiple variantEvaluations for a variant is it is present in transcripts from multiple genes. These then get independently scored an appear in the output.

Fixes the above issues and benchmarking on the Gel cases shows minimal impact on recall and precision of known diagnoses by Exomiser and Genomiser.

For Exomiser runs you get a few extra rows of results due to this. However, for Genomiser there are a lot of extra annotations as many variants can be in within two different gene structures considering introns as well.

This will impact on performance for Genomiser and generate a lot of extra output. To be investigated further

**Comment by damiansm** [comment]
I think we fixed and tested. the issue with intronic variants being assigned to multiple genes and the explosion in Genomiser results?

To be confirmed but if true the branch with this fix is ready to be merged into the next release
