### ISSUE TITLE
M-CAP

### ISSUE THREAD

**Issue by julesjacobsen** [exomiser/Exomiser#303]
http://bejerano.stanford.edu/mcap/

https://www.nature.com/articles/ng.3703

Method | Authors' Recommended Pathogenicity threshold | Misclassified known pathogenic variants
-- | -- | --
SIFT | < 0.05 | 38%
Polyphen-2 | > 0.8 | 31%
CADD | > 20 | 26%
METAL-R | > 0.5 | 27%
M-CAP | > 0.025 | 5%

**Comment by damiansm** [comment]
Incorporated into db and tested now. See future ML issue for next steps
