### ISSUE TITLE
1811_hg19_transcripts_refseq.ser does not look like a Jannovar database

### ISSUE THREAD

**Issue by pnrobinson** [exomiser/Exomiser#305]
I am getting the following error when using the latest Exomiser release (the same code is working fine with the 1802 release).
```
Deserializing JannovarData from /home/robinp/data/exomiserdata/1811_hg19/1811_hg19_transcripts_refseq.ser
Exception in thread "main" de.charite.compbio.jannovar.UncheckedJannovarException: /home/robinp/data/exomiserdata/1811_hg19/1811_hg19_transcripts_refseq.ser does not look like a Jannovar database, magic number incorrect!
```

**Comment by pnrobinson** [comment]
The class JannovarDataSerializer checks the first four bytes of the serialized file. They should be JVDB.
If we try this
```
$ less 1802_hg19_transcripts_ensembl.ser 
"1802_hg19_transcripts_ensembl.ser" may be a binary file.  See it anyway? 
JVDB<96>2Ȥ^<BD>(<A0>@[FAd(<83>XgAen<FF>o<BD><CF........
```
However, if we try this
```
$ less 1811_hg38_transcripts_ensembl.ser 
"1811_hg38_transcripts_ensembl.ser" may be a binary file.  See it anyway? 
JTPB^_<8B>^H^@^@....
```

This is weird --

**Comment by julesjacobsen** [comment]
You're using the wrong deserialiser. The original Jannovar data took too long time to deserialise, so I changed to protobuf, hence the different magic number. You want to use this class: /exomiser-core/src/main/java/org/monarchinitiative/exomiser/core/genome/jannovar/JannovarDataProtoSerialiser.java

**Comment by pnrobinson** [comment]
Thanks! I did not realise this but it works like a charm.
