### ISSUE TITLE
dbNSFP3.5

### ISSUE THREAD

**Issue by MartaRus** [exomiser/Exomiser#306]
Hi everyone!
I have a problem with the dbNSFP 3.5 version! I downloaded and processed the database with the following script in order to sort for Hg19 coordinates:
> head -n1 dbNSFP3.5a_variant.chr1 > h
> cat dbNSFP3.5a_variant.chr* \| grep -v   ^#chr \| awk '$8 != "."' \| sort -k8,8 -k9,9n - \| cat h - \| bgzip -c   > dbNSFP_hg19.gz
> tabix -s 8 -b 9 -e 9 dbNSFP_hg19.gz

It seems work but it annotate (with snpEff) only a few variants and I don't know why :( 
The same vcf annotates with the older version of dbNSFP (2.9) give me a very different result
here an example for GERP annotation only on Chr22:
$ grep GERP soloChr22_2.9.vcf | wc -l
254
$ grep GERP soloChr22_3.5.vcf | wc -l
2

any idea?
thank you in advance!

**Comment by julesjacobsen** [comment]
Sorry, why is this an Exomiser issue?
