### ISSUE TITLE
Exclude non-causative associations from Exomiser?

### ISSUE THREAD

**Issue by damiansm** [exomiser/Exomiser#307]
During review of some of our 100KGP candidates based on "known" disease genes it has come to light that a number are based on Orphanet evidence only and further exploration shows they involve disease-gene relationships that are not a straightforwad germline mutation cases disease e.g.

- HLA-DRB1: Major susceptibility factor in Diffuse cutaneous systemic sclerosis etc
- SEC24C: Modifying germline mutation in 22q11.2 deletion syndrome
- CLIP2: Role in the phenotype of Williams syndrome

Orphanet marks disease causing mutations as "Disease-causing germline mutation(s) in ..." Should we attempt to remove such disease2gene relationships to make Exomiser results more clear cut or highlight the d2g association instead.

Morbidmap now tells us about similar relationships as well

**Comment by cmungall** [comment]
cc @tomconlon @kshefchek @mattbrush, let's make sure we are in sync with dipper here

Note that ORDO does include the relationship type, see for example https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_567 (look under related-from)

I forget if Exomiser parses the Orphanet XML or gets this some other way, but you should definitely use the relationship type. Seems safest to restrict to germline mutation causative

Williams deletes multiple genes but that isn't apparent in the omim or orpha data

https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_904

Can we incorporate some of @drseb's work from a while back here?

For morbidmap, remind me, exomiser uses the NCBI mim2gene file?

**Comment by damiansm** [comment]
So in the Exomiser db we have a disease table that stores disease_id|omim_gene_id|diseasename|gene_id|type|inheritance where type is:

'D', default, a Mendelian disease => 4783/6051 omim entries
'N', non-disease => 130/6051 omim entries
'S', susceptibility to multifactorial disorders => 495/6051 omim entries
'?' an unconfirmed or possibly spurious mapping => 643/6051 omim entries
'C', a chromosome deletion or duplication syndrome => 0/6051 omim entries

http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/lastSuccessfulBuild/artifact/annotation/diseases_to_genes.txt is used to produce orphanet.pg which stores the orphanet disease ID to entrezGeneID mappings and gets loaded into our disease table but we leave type, omim_gene_id and inheritance blank

https://omim.org/static/omim/data/mim2gene.txt and morbidmap are used to create omim.pg  which is loaded into the disease table with all fields properly populated.

Questions to resolve:
1. How do we get this info from Orphanet
2. Do we use the gene type in any of our Exomiser queries? If not we probably should!

**Comment by julesjacobsen** [comment]
Ah, no we don't use these. Shall we filter for D only?

**Comment by damiansm** [comment]
Lets first get the Orphanet data into the same level of annotation in the database and then investigate how best to either filter or better flag in the results

**Comment by damiansm** [comment]
Final plan to resolve:

1. Reintroduce parsing of Orphanet files to extract the type of disease2gene relationship and populate Exomiser disease table type column with this info for all Orphanet diseases as well i.e.

 - extract orphanet diseaseID to entrezGene ID from disease2genes.txt file as usual
- add in the extra info on type by parsing http://www.orphadata.org/data/xml/en_product6.xml to extract the type

<Disorder id="11711">
      <OrphaNumber>85414</OrphaNumber>
      <Name lang="en">Systemic-onset juvenile idiopathic arthritis</Name>
      <DisorderGeneAssociationList count="4">
        <DisorderGeneAssociation>
          <SourceOfValidation>26598658[PMID]</SourceOfValidation>
          <Gene id="16202">
            <OrphaNumber>122427</OrphaNumber>
            <Name lang="en">major histocompatibility complex, class II, DR beta 1</Name>
            <Symbol>HLA-DRB1</Symbol>
            <SynonymList count="0">
            </SynonymList>
            <ExternalReferenceList count="6">
              <ExternalReference id="56818">
                <Source>Ensembl</Source>
                <Reference>ENSG00000196126</Reference>
              </ExternalReference>
              <ExternalReference id="37478">
                <Source>Genatlas</Source>
                <Reference>HLA-DRB1</Reference>
              </ExternalReference>
              <ExternalReference id="30196">
                <Source>HGNC</Source>
                <Reference>4948</Reference>
              </ExternalReference>
              <ExternalReference id="30195">
                <Source>OMIM</Source>
                <Reference>142857</Reference>
              </ExternalReference>
              <ExternalReference id="56819">
                <Source>Reactome</Source>
                <Reference>P04229</Reference>
              </ExternalReference>
              <ExternalReference id="33220">
                <Source>SwissProt</Source>
                <Reference>P04229</Reference>
              </ExternalReference>
            </ExternalReferenceList>
            <LocusList count="1">
              <Locus id="22701">
              </Locus>
            </LocusList>
          </Gene>
          <DisorderGeneAssociationType id="17961">
            <Name lang="en">Major susceptibility factor in</Name>
          </DisorderGeneAssociationType>
          <DisorderGeneAssociationStatus id="17997">
            <Name lang="en">Not yet assessed</Name>
          </DisorderGeneAssociationStatus>
        </DisorderGeneAssociation>





2. Test whether restricting the Exomiser query to type=D improves performance and is sensible. From conversations with the clinicians it should be.

**Comment by cmungall** [comment]
Are we still treating ORPHA diseases and OMIMs as disjoint sets? When do we want to experiment with merging using MONDO equivalencies?

Are we all reusing the same code to parse the xml? I realize the dipper code is python and less useful, but I think we have a shared java library in phenol?

**Comment by pnrobinson** [comment]
@cmungall I am still a little worried about depending on MONDO at this point. How sure are we that the cross references are correct? It seems to me that a substantial amount of TLC is still required.

**Comment by cmungall** [comment]
Yep, we could start with high confidence sets but there are other issues such as differences in annotations between orphanet and hpoa, this would be the bigger deal...

**Comment by damiansm** [comment]
At moment I still keep OMIM and Orphanet separate as Exomiser is being used in production by various people and don't know what the status is on the annotation merge i.e. is everyone happy it improves things or not? Easiest thing would be for me to create a new issue to test this on several hundred real cases and see if we do better or worse

**Comment by damiansm** [comment]
Back to the main issue I now have code to extract the disease2gene relationships for Orphanet as well.

```
String type = "?";
                if (null != diseaseGeneTypeMap.get(key)){
                    if (diseaseGeneTypeMap.get(key).startsWith("Disease-causing germline mutation")){
                        type = "D";
                    }
                    else if (diseaseGeneTypeMap.get(key).startsWith("Major susceptibility factor")){
                        type = "S";
                    }
                    /* other types in Orphanet that we are just leaving as ? for now
                    Disease-causing somatic mutation
                    Biomarker tested in
                    Candidate gene tested in
                    Modifying germline mutation in
                    Part of a fusion gene in
                    Role in the phenotype of*/
                }
```
Currenly my logic is as above but do we want to give those other Orphanet statuses a different Exomiser type code. Main one I am not sure about are the somatic mutations

**Comment by damiansm** [comment]
Tested performance on solved cases with a very strict setting on only using type='D' from OMIM and Orphanet (currently Disease-causing germline mutation only). 

No change in overall performance.
- Could see a number of samples where we had got rid of highest scoring evidence that was based on "Candidate genes" in Orphanet and this improved things in one case.
- See one example where we lost a really good Orphanet hit that is classified as "Role in the phenotype of". These seem to be cases where several genes are deleted or duplicated. Maybe these should get type = 'C' and be included in the query?

Decisions
1. Should we create addition ENUM types for the other Orphanet categories
2. Should we widen query from 'D' only to C/Role in phenotype of and/or Candidate genes.

As part of the clinical review of candidate Exomiser candidates the clinicians spent a lot of time removing spurious candidates based on somatic mutations, modifiers and susceptibility factors so in a diagnostic setting definitely seems best to exclude those.

**Comment by damiansm** [comment]
The official Oprhanet definitions:
Disease -
causing germline mutation(s) in
:
A gene mutation in a germ cell that is sufficient to produce 
the disorder and that can be passed on to offspring.

Disease
-
causing  germline  mutation(s)  (gain  of  function)  in:
A  gen
e  mutation  in  a  germ  cell  that 
provides a new function of the corresponding protein that is sufficient to produce the disorder and that can 
be passed on to offspring.

Disease
-
causing germline mutation(s) (loss of function) in:
A gene mutation in a germ cel
l that impairs 
the  function  of  the  corresponding  protein  a
nd
that  is  sufficient  to  produce  the  disorder  and  that  can  be 
passed on to offspring.

Disease
-
causing somatic mutation(s) in:
A gene mutation in a somatic cell that is sufficient to produce 
the diso
rder but that cannot be passed on to offspring.

Major susceptibility factor in:
A gene mutation in a germ cell that predisposes to the development of a 
disorder, and that is necessary but not sufficient to develop the disorder.

Modifying germline mutation 
in:
A gene mutation in a germ cell that modifies the clinical presentation 
of the disorder and that can be passed on to offspring.

Part of a fusion gene in:
A 
coding 
or regulatory DNA sequence from a gene 
that has fused with a
nother 
coding 
and/or regulatory 
DNA sequence
from a different gene.

Role in the phenotype of:
A gene
included in a chromosomal rearrangement, and proved to have a major 
influenc
e in the phenotype of 
the
chromosomal rearrangement.

Biomarker  tested  in: 
A  gene  in  which  a  v
ariation  is  used  to  monitor  disease  activity  and/or  patient 
outcome. 

Candidate gene tested in:
A gene in which a mutation is suspected, but not yet proven, to be responsible 
for a disorder, and that is tested for in a clinical setting

**Comment by damiansm** [comment]
Final db change for Orphanet disease gene associations:

- Disease-causing germline mutations and Candidate gene tested added as type 'D'
- Role in the phenotype added as type 'C'
- Major susceptibility factor as type 'S'

Tested a version of the database where only include type D and C association and performance is good and removes a lot of spurious phenotype evidence we were getting.

TODO: in 12.0.0 development branch DefaultDiseaseDao add 'AND (TYPE = 'D' OR TYPE = 'C') and check we get the same results

**Comment by julesjacobsen** [comment]
Ah, this is a bit of a problem - you've assigned the 'Role in the phenotype' to 'C' which is mapped to ```org.monarchinitiative.exomiser.core.prioritisers.model.Disease.DiseaseType.CNV``` so this will cause all OMIM CNV diseases to be retrieved as well and get them confused.

The mappings are:

```java
DISEASE("disease", "D"),
NON_DISEASE("non-disease", "N"),
SUSCEPTIBILITY("susceptibility", "S"),
UNCONFIRMED("unconfirmed", "?"),
CNV("CNV", "C");
```

I suggest we add another, say 'P' for 'role in Phenotype' and tie this firmly to the Enum in the parser and DAO code so as not to create issues.

**Comment by damiansm** [comment]
@julesjacobsen The role in phenotype category in Orphanet was referring to CNV diseases though. Their definition was "A gene included in a chromosomal rearrangement, and proved to have a major influence in the phenotype of the chromosomal rearrangement" and all the examples I saw were classic CNV syndromes.

I did notice that we had no OMIM annotations to this category so wondering if something has gone amiss somewhere in the morbidmap parsing

**Comment by julesjacobsen** [comment]
Ah, sorry, I misunderstood, based on your final  "Role in the phenotype added as type 'C'".

I'll check the morbidmap parser.

**Comment by damiansm** [comment]
Yep - it is not the most descriptive term from Orphanet. I initially read it as this is kind of a candidate but the reality seems to be it means this is the gene in the CNV that everyone believes is causing most of the phenotypes!

**Comment by julesjacobsen** [comment]
Ah, sorry, I misunderstood, based on your final  "Role in the phenotype added as type 'C'".

Looks like the reason there are no OMIM CNV is that the mim2gene file maps the MIM numbers for these to phenotype only, so they never get added to the database. Will investigate to make sure this is the case.

**Comment by damiansm** [comment]
Tested and all good now
