### ISSUE TITLE
SpliceAI

### ISSUE THREAD

**Issue by damiansm** [exomiser/Exomiser#308]
https://github.com/Illumina/SpliceAI

**Comment by damiansm** [comment]
After discussions probably best strategy is to give all spliceAI predicted variants with a maxScore(acceptorGain, acceptorLoss, donorGain, donorLoss) above a threshold (0.2 for high recall and likely pathogenic vars, 0.5 recommended setting for pathogenic vars, 0.8 for high precision pathogenic vars) a high pathogenicityScore (if consider fully LoF should be 1).

Assessing whether these variants are pathogenic really relies on the genomic context of the predicted splice acceptor or donor and size of the effect and can only be confirmed with functional assays.

We can possibly assess performance on a set of TPs from retinal cases and then select the best combination of:

- use maxScore of different methods for acceptor and donor gains and losses
- score threshold to use
- pathogenicityScore ot assign

We also need to implement the best way of obtaining the spliceAI scores: lookup from a pre-calculated table or dynamically calculate

**Comment by pnrobinson** [comment]
@damiansm can we compare this to Daniel's score?

**Comment by damiansm** [comment]
@pnrobinson absolutey! that is the plan. I am sure like most predictive methods that using multiple lines of evidence will be the best in the end.

**Comment by ShrutiMarwaha** [comment]
Hi Damian,

I was wondering if current (or future version) of exomiser uses SpliceAI? If current version does, what parameter should I be using to include it in my yaml file?

Thanks,
Shruti

**Comment by damiansm** [comment]
Hi Shruti,

Not currently integrated. We definitely have plans to incorporate this and
other splicing approaches in the future but no timeline yet

Cheers
Damian

**Comment by visze** [comment]
Hi,

CADD 1.6 integrates now spliceAI and MMSplice. See the release notes: https://cadd.gs.washington.edu/static/ReleaseNotes_CADD_v1.6.pdf

Of course a general score is not able to beat specific scores in predicting splice-predictions but the new CADD improves splice-predictions a lot.

**Comment by ShrutiMarwaha** [comment]
Thanks Damian.

**Comment by julesjacobsen** [comment]
These are available to use in Exomiser [14.0.0](https://github.com/exomiser/Exomiser/releases/tag/14.0.0)
