### ISSUE TITLE
REMM for hg38

### ISSUE THREAD

**Issue by abrusell** [exomiser/Exomiser#312]
This comment:https://github.com/exomiser/Exomiser/issues/187#issuecomment-314393658
has been moved to DONE (julesjacobsen moved this from In Progress to DONE in Release 9.0.0 on 6 Dec 2017), but I cannot find any REMM score file for hg38
How can I prioritize for non-coding regulatory regions?

**Comment by DGMichael** [comment]
Also interested in this.

**Comment by abrusell** [comment]
Are there any news on this?

**Comment by tycheleturner** [comment]
I was looking for the hg38 file as well. It looks like in the Exomiser code base the link to the ReMM scores is here https://charite.github.io/software-remm-score.html and there is a tabix (and index) file on hg19. It looks like a liftOver (https://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/liftOver) from hg19 to hg38 (http://hgdownload.cse.ucsc.edu/goldenpath/hg19/liftOver/hg19ToHg38.over.chain.gz) should work to update to hg38.

**Comment by tycheleturner** [comment]
I can confirm that the liftover approach works.

**Comment by visze** [comment]
We are working on a complete new training on GRCh38, because a simple lifover has its limitations. The plan is to release it end of this year. I will announce it and make it available at the actual ReMM webiste: https://kircherlab.bihealth.org/projects/remm-score.html

**Comment by manu-lifebit** [comment]
> We are working on a complete new training on GRCh38, because a simple lifover has its limitations. The plan is to release it end of this year. I will announce it and make it available at the actual ReMM webiste: https://kircherlab.bihealth.org/projects/remm-score.html

Is there any news on this?

**Comment by visze** [comment]
hey. actually yes! I released the ReMM score for hg38 on zenodo a while ago but forgot to change the website. Now also the website is updated. Have fun with the hg38 ReMM score!

Direct link to zenodo:

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.4768448.svg)](https://doi.org/10.5281/zenodo.4768448)

**Comment by julesjacobsen** [comment]
Brilliant! Thanks @visze
