### ISSUE TITLE
Exomiser Data Traffic

### ISSUE THREAD

**Issue by williakd17** [exomiser/Exomiser#321]
Hello,

I was wondering what the data traffic flow looks like for a given instance of Exomiser. I'm running Exomiser with the cli and have the 1811_phenotype, 1811_hg19, REMM, CADD etc. locally, however I really would like to know which databases and servers the data is being sent to (and ideally how it's being sent, i.e. variant-by-variant vs. entire vcf). Reason being, I would like to see how the input .vcf data is being exposed for security reasons. 

Thank you for your time,
Kyle

**Comment by julesjacobsen** [comment]
Hi Kyle,

The data isn't being sent anywhere. It's all run locally, unless you put the files on a network somewhere. It is designed to be run in clinical environments with no external network access.
