### ISSUE TITLE
Pathogenicity Sources in 12.0

### ISSUE THREAD

**Issue by williakd17** [exomiser/Exomiser#324]
In the CLI changes for 12.0, you added M_CAP, MPC, MVP, and PRIMATE_AI. Do you know which sources are not free for commercial use? For ones that require licencing, do you happen to know the cost? Also, how would you go about incorporating these sources into Exomiser?

**Comment by julesjacobsen** [comment]
You'll have to investigate the commercial use of these yourself. The respective licences for these scores allow for free distribution, but using them in a commercial setting requires negotiating a licence from the owner. PolyPhen2 also requires a license, if you're a commercial entity.

**Comment by williakd17** [comment]
Perfect. Thank you so much!
