### ISSUE TITLE
Data-version 1902

### ISSUE THREAD

**Issue by williakd17** [exomiser/Exomiser#325]
Do you know where I can find the most recent data-version (1902) for Exomiser? I looked in https://data.monarchinitiative.org/exomiser/latest/ , but did not see the latest version yet. Thank you for your time.

**Comment by julesjacobsen** [comment]
Sorry, I think we've got an issue with our server. Are you able to download the data at a reasonable speed from  https://data.monarchinitiative.org/exomiser/latest/ ?

**Comment by williakd17** [comment]
Yes, it shouldn't be too bad :)

**Comment by julesjacobsen** [comment]
Can you confirm please? It seems quite location dependent. In Europe we've had users with download speeds of about 55 kbps.

**Comment by williakd17** [comment]
Using the 1811_phenotype.zip, in central US I'm downloading around 75 kbps. Not ideal, but I could just download overnight.

**Comment by genmaibutter** [comment]
Hi, I'm a exomiser from Thailand. Would like to access the most recent data-version 1902.
Where can I download the data? Please give me some suggestion. Thanks.

**Comment by julesjacobsen** [comment]
@williakd17 thanks for trying - you're experiencing the issue we're facing. Apparently this might be a hardware issue and things are being done to remedy this, only I've no idea about when this will be resolved. Right now I can't upload the data, so people will have to wait. Sorry.

**Comment by Briteguy** [comment]
Are you able to host those files on GitHub in the same area that I was able to download exomiser-cli-12.0.0? Downloading from GitHub took very little time compared to my prior experiences with downloading off https://data.monarchinitiative.org/exomiser/latest/. 


This is the link. https://github.com/exomiser/Exomiser/releases/download/12.0.0/exomiser-cli-12.0.0-distribution.zip It comes off this page: https://github.com/exomiser/Exomiser/releases

**Comment by PabloBotas** [comment]
Hi! How is the data issue going? Still not possible to upload the newer version?
I'm downloading at ~800Kb/s, so pretty good :)

**Comment by williakd17** [comment]
@julesjacobsen My downloading speeds for the current data versions are also around 800Kb/s, so you should be able to upload the data.

**Comment by your-highness** [comment]
@williakd17 Where do you download the data release? Can you point me to an URL?

**Comment by edg1983** [comment]
Where is the 1902 version of exomiser data located? It is not found in the indicated URL https://data.monarchinitiative.org/exomiser/latest/
This one is still reporting exomiser version 11 with data version 1811. 
Please provide a location where to find the updated dataset. Thanks!

**Comment by bpow** [comment]
The comments here are split between two separate problems:

- variability in download rates, possibly site-dependent
- absence of 1902 data files

Absence of 1902 data files prevents use of the the most recent release versions (12.0.0 and 12.0.1, from as far back as 4 months ago). Is there a timeframe for making these files available for download?

**Comment by damiansm** [comment]
Just an update for all concerned with the latest data availability. We are still working with our colleagues to get a stable place to host the Exomiser databases with decent download rates. A related issue is we need to implement some sort of registration system as the latest database contains data that is not freely available for non-academic users.

**Comment by julesjacobsen** [comment]
Sorry about the delay, but the 12.0.1 binary and 1902 data release is now available from 
https://data.monarchinitiative.org/exomiser/latest/
