### ISSUE TITLE
Crash on duplicate gene in REST API

### ISSUE THREAD

**Issue by holtgrewe** [exomiser/Exomiser#326]
Querying the REST API with a gene list containing a duplicate returns a `HTTP 500` error message indicating `Duplicate key org.monarchinitiative.exomiser.core.prioritisers.PhenixPriority$PhenixScore@c2fb68`.

While I can fix this on the client side, it might be something to make more robust on the server side.

By the way, is there some plan to also allow POSTing? IIRC most servers and clients have stricter limits on GET than on POST requests.

**Comment by julesjacobsen** [comment]
Thanks for the feedback @holtgrewe. I'll add this as a fix in the next release. 

As for POST requests, do you need this? It's simple enough to add, only marginally less convenient to use.

**Comment by holtgrewe** [comment]
POST access would be great! (GET additioinally would be useful)

**Comment by holtgrewe** [comment]
@julesjacobsen OK, we've hit the request URI limitation with GET requests now, adding another bug.

**Comment by damiansm** [comment]
@julesjacobsen Is this done now?

**Comment by julesjacobsen** [comment]
Fixed in 12.1.0
