### ISSUE TITLE
unable to create default output directory

### ISSUE THREAD

**Issue by maojn** [exomiser/Exomiser#336]
Hi,

I installed exomiser in shared area for users. Users copied the example directory to their own area and tried:
java -Xms2g -Xmx4g -jar $EXOMISERJAR  --analysis examples/test-analysis-exome.yml
It seems to run without problem with results in the results directory under user's area alright. However, There is this output during the run :+1: 
ERROR 17547 --- [           main] o.m.exomiser.cli.config.MainConfig       : Unable to create default output directory for results /usr/local/apps/exomiser/11.0.0/results

Looks like exomiser was attempting to create the results directory under shared area which user does not have permission to. Can this error be safely ignored?

Thank you.

Jean

**Comment by julesjacobsen** [comment]
Hi Jean, if the results are being written to the user's area then yes, you can ignore the error. If you manually create this directory, the error message should vanish.

**Comment by maojn** [comment]
Thank you for your reply. User has to manually create the results directory first otherwise exomiser errors out. He still got this error message though.

**Comment by julesjacobsen** [comment]
No, I meant create this directory: ` /usr/local/apps/exomiser/11.0.0/results` which is what the program is looking for as a default output directory.

**Comment by maojn** [comment]
Oh I see. Unfortunately, that directory is under shared area and users do not have privilege to write in it.

**Comment by julesjacobsen** [comment]
I know, but having the directory there will prevent the error message being thrown. If they try to write there then a genuine error will be thrown, but this will just serve to stop those errors on start-up.

**Comment by maojn** [comment]
That works! Thank you very much!

**Comment by julesjacobsen** [comment]
No problem. Happy Exomising!
