### ISSUE TITLE
libatomic.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by pnrobinson** [exomiser/Exomiser#341]
I am installing a new computer and just tried to compile Exomiser and the compile fails with the error:
```
libatomic.so.1: cannot open shared object file: No such file or directory
```
which is related to the protobuf plugin. I then installed the package (on ubuntu, as follows):
```
sudo apt install  libatomic1
```
then I was able to compile without problems. We should add this to the documentation somewhere. (I am using open-jdk11 and the release-12.0.0 branch of Exomiser).
I am still unable to install Exomiser unless I used DskipTests=true, owing to what seems to be a concurrency issue with the tests.

<pre><font color="#EF2929"><b>ERROR</b></font>] <font color="#EF2929"><b>Errors: </b></font>
[<font color="#EF2929"><b>ERROR</b></font>] <font color="#EF2929"><b>  ExomiserAutoConfigurationTest.testAutoConfiguration:47-&gt;AbstractAutoConfigurationTest.load:53 » UnsatisfiedDependency</b></font>
[<font color="#EF2929"><b>ERROR</b></font>] <font color="#EF2929"><b>  Hg19GenomeAnalysisServiceAutoConfigurationTest.genomeAnalysisService:44-&gt;AbstractAutoConfigurationTest.load:53 » BeanCreation</b></font>
[<font color="#EF2929"><b>ERROR</b></font>] <font color="#EF2929"><b>  Hg19GenomeAnalysisServiceAutoConfigurationTest.genomeAnalysisServiceWithOptionalTestPathDao:67-&gt;AbstractAutoConfigurationTest.load:53 » BeanCreation</b></font>
[<font color="#729FCF"><b>INFO</b></font>] 
[<font color="#EF2929"><b>ERROR</b></font>] <font color="#EF2929"><b>Tests run: 44, Failures: 0, Errors: 3, Skipped: 1</b></font>
[<font color="#729FCF"><b>INFO</b></font>] 
[<font color="#729FCF"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#729FCF"><b>INFO</b></font>] <b>Reactor Summary for exomiser 12.0.0:</b>
[<font color="#729FCF"><b>INFO</b></font>] 
[<font color="#729FCF"><b>INFO</b></font>] exomiser ........................................... <font color="#8AE234"><b>SUCCESS</b></font> [  0.337 s]
[<font color="#729FCF"><b>INFO</b></font>] exomiser-core ...................................... <font color="#8AE234"><b>SUCCESS</b></font> [ 12.980 s]
[<font color="#729FCF"><b>INFO</b></font>] exomiser-spring-boot-autoconfigure ................. <font color="#EF2929"><b>FAILURE</b></font> [  4.058 s]
[<font color="#729FCF"><b>INFO</b></font>] exomiser-spring-boot-starter ....................... <font color="#FCE94F"><b>SKIPPED</b></font>
[<font color="#729FCF"><b>INFO</b></font>] exomiser-spring-boot-test .......................... <font color="#FCE94F"><b>SKIPPED</b></font>
[<font color="#729FCF"><b>INFO</b></font>] exomiser-cli ....................................... <font color="#FCE94F"><b>SKIPPED</b></font>
[<font color="#729FCF"><b>INFO</b></font>] exomiser-data-genome ............................... <font color="#FCE94F"><b>SKIPPED</b></font>
[<font color="#729FCF"><b>INFO</b></font>] exomiser-data-phenotype ............................ <font color="#FCE94F"><b>SKIPPED</b></font>
[<font color="#729FCF"><b>INFO</b></font>] exomiser-rest-prioritiser .......................... <font color="#FCE94F"><b>SKIPPED</b></font>
[<font color="#729FCF"><b>INFO</b></font>] exomiser-web ....................................... <font color="#FCE94F"><b>SKIPPED</b></font>
</pre>

**Comment by julesjacobsen** [comment]
This is a concurrency issue running tests on Linux, sorry. It's incredibly annoying and I've not managed to find the root cause. This never happens on Windows.
