### ISSUE TITLE
no main manifest attribute, in exomiser-data-phenotype-12.0.1.jar

### ISSUE THREAD

**Issue by shenjia1** [exomiser/Exomiser#343]
Hi,
I want to build the phenotype database following your "Phenotype DB build" pipeline. I compiled the source files to generate exomiser-data-phenotype-12.0.1.jar. But it didn't work. And what I need to do for generating exomiser-data-phenotype ?

Thanks,
Jia

**Comment by julesjacobsen** [comment]
The latest files are now available:

https://data.monarchinitiative.org/exomiser/latest/
