### ISSUE TITLE
Increasing .html Prioritised genes output

### ISSUE THREAD

**Issue by TimboW15** [exomiser/Exomiser#344]
Hi,

I was wondering how to increase the exomiser .html output of prioritized genes. I am doing a comparative analysis between the genes within the .tsv file and a reference list, however when certain genes come up common to both, I can't find them in the .html file because they are not high up enough in the priority list. Is it possible to increase the prioritized gene output?
Or alternatively, is it possible to get the variant information (ie chromosomal location, bp change, rs number, pathogenicity scores, etc...) from another output file exomiser produces? This would be for variants low on the priority list.

Sorry if this doesn't make sense, I am new to the field. Thanks for taking a look!

**Comment by julesjacobsen** [comment]
Dis you try looking in the variants.tsv or vcf output files?

**Comment by julesjacobsen** [comment]
You can also use JSON output and use something like [jq](https://stedolan.github.io/jq/) to process the results.
