### ISSUE TITLE
Possibility to run without database for testing purposes?

### ISSUE THREAD

**Issue by holtgrewe** [exomiser/Exomiser#347]
Would it be possible to add a mode to run Exomiser with the REST API without any supporting databases? The server would not have to perform actual prioritisations but I would like to be able to test my Ansible deployment scripts without a download of several GB of data...

**Comment by julesjacobsen** [comment]
Do you mean the prioritiser REST service?

**Comment by holtgrewe** [comment]
Yes, precisely.

**Comment by julesjacobsen** [comment]
You should be able to use the data used in the tests here:

https://github.com/exomiser/Exomiser/tree/master/exomiser-spring-boot-autoconfigure/src/test/resources/data

**Comment by julesjacobsen** [comment]
Closing due to lack of response
