### ISSUE TITLE
Ensembl to NCBI gene mapping broken for RP1

### ISSUE THREAD

**Issue by damiansm** [exomiser/Exomiser#355]
For the 1909_hg38 build the Jannovar files return and EntrezGeneID of 107984125 insteado of 6101 for RP1 so the known disease links are missed. This is because Ensembl is now mapping two NCBI links for this gene: https://www.ensembl.org/Homo_sapiens/Gene/Matches?db=core;g=ENSG00000104237;r=8:54509422-54871720

**Comment by damiansm** [comment]
@julesjacobsen Do you remember why I removed this from the 13.0.0 release roadmap? Did we just decide it was almost impossible to fix as the issue is in Ensembl? Means we miss one of the main eye disease genes which is not ideal!

**Comment by julesjacobsen** [comment]
Looks like that link only shows the 6101 NCBI gene ID no, so don't know it is was a temporary Ensembl blip or is there is something odd going on in the Jannovar code.

Jannovar has been updated recently and claims to have fixed the errors thrown on RefSeq so it might be worth investigating all this in one chunk.

**Comment by damiansm** [comment]
Running 12.0.1/12.1.0 or 13.0.0-SNAPSHOT on the 2102*dbs still seems to return the wrong 107984125 entrezGene ID. Maybe will just be fixed in the next db release if Ensembl has changed between Feb and now?

**Comment by damiansm** [comment]
Seems like has been fixed in Ensembl from release 100 (March 2020) onwards so is odd Jannovar is still giving us the old ID?

MacBook-Pro:Downloads damiansmedley$ grep ENST00000220676 Homo_sapiens.GRCh38.*.entrez
Homo_sapiens.GRCh38.100.entrez:ENSG00000104237	ENST00000220676	ENSP00000220676	6101	EntrezGene	DEPENDENT	-	-	-
Homo_sapiens.GRCh38.101.entrez:ENSG00000104237	ENST00000220676	ENSP00000220676	6101	EntrezGene	DEPENDENT	-	-	-
Homo_sapiens.GRCh38.102.entrez:ENSG00000104237	ENST00000220676	ENSP00000220676	6101	EntrezGene	DEPENDENT	-	-	-
Homo_sapiens.GRCh38.104.entrez:ENSG00000104237	ENST00000220676	ENSP00000220676	6101	EntrezGene	DEPENDENT	-	-	-
Homo_sapiens.GRCh38.99.entrez:ENSG00000104237	ENST00000220676	ENSP00000220676	6101	EntrezGene	DEPENDENT	-	-	-
Homo_sapiens.GRCh38.99.entrez:ENSG00000104237	ENST00000220676	ENSP00000220676	107984125	EntrezGene	DEPENDENT	-	-	-

**Comment by damiansm** [comment]
@julesjacobsen Actually I think this is my fault as I am still producing the gencode-basic Ensembl .ser files for the release and my default.sources.ini may not have been updated
