### ISSUE TITLE
Genomiser vs. Exomiser

### ISSUE THREAD

**Issue by Wanda-Sankey** [exomiser/Exomiser#362]
I have a question specifically related to the difference in Genomiser and Exomiser. As I understand it, Exomiser prioritizes coding regions in VCF files while Genomiser prioritizes non-coding regions. Exomiser appears to do this by (from my observation) filtering out non-coding variants based on annotated variant type using this variant affect filter: 

`variantEffectFilter: {
            remove: [
                FIVE_PRIME_UTR_EXON_VARIANT,
                FIVE_PRIME_UTR_INTRON_VARIANT,
                THREE_PRIME_UTR_EXON_VARIANT,
                THREE_PRIME_UTR_INTRON_VARIANT,
                NON_CODING_TRANSCRIPT_EXON_VARIANT,
                NON_CODING_TRANSCRIPT_INTRON_VARIANT,
                UPSTREAM_GENE_VARIANT,
                INTERGENIC_VARIANT,
                REGULATORY_REGION_VARIANT,
                CODING_TRANSCRIPT_INTRON_VARIANT,
                DOWNSTREAM_GENE_VARIANT
            ]
        }`

My question is this: could I run Exomiser where the non-coding variants would be prioritized as well if I were to remove these restrictions on the type of variants to include?

**Comment by julesjacobsen** [comment]
Genomiser will prioritise variants in both the coding and non-coding regions. However the non-coding regions can create a lot of noise so it may be useful to run both Exomiser and Genomiser on a WGS sample.

**Comment by Wanda-Sankey** [comment]
So even if comment out the aforementioned listed variants that exomiser removes, would that be the equivalent of running genomiser and exomiser?

**Comment by Wanda-Sankey** [comment]
My main concern is that I would like to have the variants ranked from both exomiser and genomiser. The only way I could think about doing this is if I modify the exomiser call to include variants analyzed with genomiser.
