### ISSUE TITLE
No phenotype matches listed when using Phenix prioritiser

### ISSUE THREAD

**Issue by oleraj** [exomiser/Exomiser#364]
Hi,

I noticed when using Phenix as a quick look for any known genes responsible for the patient's phenotype that the "Phenotype matches" section is always empty in the HTML output.  This is always present when I use hiPhive.  Any reason they don't show up for me and any way to get them to show up?

Thanks,

Andrew

**Comment by julesjacobsen** [comment]
Hi Andrew,

These two algorithms are different and computed differently. PhenIX is a much older algorithm and wasn't coded in such a way as to be able to report the best matches back to the user. In our benchmarking HiPhive using the human only (i.e. `runParams=human`) is of similar performance to PhenIX. 

Jules

**Comment by oleraj** [comment]
Great, thanks for the reply. Good to know that hiPhive with human only gives similar results.  I'll use that instead.
