### ISSUE TITLE
How is the PhenIX score calcuated?

### ISSUE THREAD

**Issue by smw1414** [exomiser/Exomiser#374]
Hi Exomiser term, 
I would like to understand the calculation of PhenIX score. I check the source code and looks like it's something to with the function "similarityMeasure.computeObjectSimilarity". But I couldn't find where this function come from. Would you shed lights on the method of similarity scoring for the given function? e.g. Jaccard or Resnik. 
Thank you very much.

**Comment by pnrobinson** [comment]
Please have a look at the original paper:
https://www.ncbi.nlm.nih.gov/pubmed/25186178
