### ISSUE TITLE
Filtered Variants showing up in PASS_ONLY mode

### ISSUE THREAD

**Issue by oleraj** [exomiser/Exomiser#375]
Hi,

I have a variant that looks like this:
```
1	218610684	.	G	A	2430.67	VQSRTrancheSNP99.90to100.00	
```
so, a fairly low quality variant (lowest VQSR tranche).  

In my .yml file I specified:
```
analysisMode: PASS_ONLY
``` 
but the variant still shows up.  Any reason for this?

I also noticed this issue that might be related: #256.  In case it is, here's my setting for outputContributingVariantsOnly:
```
outputContributingVariantsOnly: false
```

Since issue #256 was resolved, is analysisMode ignored?  

Thanks,

Andrew

**Comment by julesjacobsen** [comment]
Hi Andrew,

Ah, this is a confusing dual use of 'PASS' in the VCF context. In Exomiser the  `analysisMode: PASS_ONLY` refers to those passing the Exomiser filtering, not VCF filtering. If you want to remove VCF filtered variants (i.e. those without PASS or . in the FILTER column) you need to either remove them prior to Exomiser analysis or use the `failedVariantFilter: {}` e.g.

```yaml
    steps: [ 
        failedVariantFilter: {},
        variantEffectFilter: {
            remove: [
                FIVE_PRIME_UTR_EXON_VARIANT,
                FIVE_PRIME_UTR_INTRON_VARIANT,
                THREE_PRIME_UTR_EXON_VARIANT,
                THREE_PRIME_UTR_INTRON_VARIANT,
                NON_CODING_TRANSCRIPT_EXON_VARIANT,
                UPSTREAM_GENE_VARIANT,
                INTERGENIC_VARIANT,
                REGULATORY_REGION_VARIANT,
                CODING_TRANSCRIPT_INTRON_VARIANT,
                NON_CODING_TRANSCRIPT_INTRON_VARIANT,
                DOWNSTREAM_GENE_VARIANT
            ]
        },
        frequencyFilter: {maxFrequency: 2.0},
        pathogenicityFilter: {keepNonPathogenic: true},
```

**Comment by oleraj** [comment]
Thanks for clarifying. I added `failedVariantFilter` and it worked.
