### ISSUE TITLE
1902_phenotype.zip not complete

### ISSUE THREAD

**Issue by CeliaRodrigues** [exomiser/Exomiser#377]
Is the zip 1902_phenotype.zip complete at https://data.monarchinitiative.org/exomiser/data/  ?
The folder phenix is empty.
Thank you

**Comment by julesjacobsen** [comment]
There are 1909 and 2003 data versions available which contain the same phenix data. Why are trying to use old data releases?

**Comment by CeliaRodrigues** [comment]
I had a large run on that version and I wanted to compare results with the same data. I'll use the newest ones available then. Thank you.
