### ISSUE TITLE
which CADD files needed?

### ISSUE THREAD

**Issue by vdejager** [exomiser/Exomiser#378]
from the documentation it is not clear which type of the CADD data should be downloaded.
The download page has several options.
Which one should be used?

Description | Link (Size) | Tabix Index (Size)
-- | -- | --
All possible SNVs of GRCh37/hg19 | file (78G) | tabix index (2.6M)
All possible SNVs of GRCh37/hg19 incl. all annotations | file (248G) | tabix index (2.6M)
48M InDels to initiate a local setup | file (591M) | tabix index (1.6M)
48M InDels incl. all annotations to initiate a local setup | file (3.5G) | tabix index (2.2M)
All gnomAD SNVs (release 2.1.1) | file (2.3G) | tabix index (2.0M)
All gnomAD InDels (release 2.1.1) | file (387M) | tabix index (1.6M)

**Comment by visze** [comment]
You need the whole genome score files. Annotations are not needed. So in your table this would be `All possible SNVs of GRCh37/hg19`for SNVs and `48M InDels to initiate a local setup`for indels. Alsways together with the tabix file

**Comment by vdejager** [comment]
Thank,

Im downloading the files right now.



Op ma 8 jun. 2020 om 19:01 schreef Max <notifications@github.com>
