### ISSUE TITLE
Trying to use phenixPrioritiser instead of hiPhivePrioritiser

### ISSUE THREAD

**Issue by geocarvalho** [exomiser/Exomiser#383]
Hello, thanks to make this project available.
I have the tool working perfectly using `hiPhivePrioritiser` in my analysis `yml` file, but when I change it to `phenixPrioritiser` it prints infinity errors on the screen.
Any help?

Best regards,
George.

**Comment by julesjacobsen** [comment]
Hi George, sorry for the lack of activity here. You can move all  the `.out` files from `phenix/out` in the `phenix` directory and this ought to work.

This should be fixed in the latest release.

Regards,

Jules
