### ISSUE TITLE
NA19722_601952_AUTOSOMAL_RECESSIVE_POMP_13_29233225_5UTR_38.vcf.gz missing from distribution 12.1.0

### ISSUE THREAD

**Issue by dwuab** [exomiser/Exomiser#388]
In the distribution [12.1.0](https://data.monarchinitiative.org/exomiser/latest/exomiser-cli-12.1.0-distribution.zip), `example/NA19722_601952_AUTOSOMAL_RECESSIVE_POMP_13_29233225_5UTR_38.vcf.gz` is absent from the `example` folder, yet its existence is required by `example/NA19722_601952_AUTOSOMAL_RECESSIVE_POMP_13_29233225_5UTR_38.yml`.

**Comment by julesjacobsen** [comment]
Sorry. Yes this file was too large to keep on GitHub so was missing. This is fixed in version 13.
