### ISSUE TITLE
Possibility to enable and configure CADD in hg38 analysis

### ISSUE THREAD

**Issue by Eduardo-Auer** [exomiser/Exomiser#394]
Is it possible to enable and configure CADD in hg38 analysis? I couldn't find where and how to configure CADD files for hg38 in "application.properties".

**Comment by julesjacobsen** [comment]
Hi @Eduardo-Auer you need to mirror the `hg19.cadd` properties i.e.

```properties
exomiser.hg19.data-directory=${exomiser.data-directory}/${exomiser.hg19.data-version}_hg19
#location of CADD/REMM Tabix files - you will need these for analysis of non-coding variants.
#CADD can be downloaded from http://cadd.gs.washington.edu/download - v1.3 has been tested.
#REMM can be downloaded from https://charite.github.io/software-remm-score.html
#local frequencies are required to be normalised in the same manner as the input VCF and frequency values must be percentages.
#
#You will require the tsv.gz and tsv.gz.tbi (tabix) file pairs.
#Un-comment and add the full path to the relevant tsv.gz files if you want to enable these.
#exomiser.hg19.cadd-snv-path=${exomiser.hg19.data-directory}/whole_genome_SNVs.tsv.gz

# copy these ^^^ like this VVV

exomiser.hg38.data-directory=${exomiser.data-directory}/${exomiser.hg38.data-version}_hg38
#You will require the tsv.gz and tsv.gz.tbi (tabix) file pairs.
#Un-comment and add the full path to the relevant tsv.gz files if you want to enable these.
#exomiser.hg38.cadd-snv-path=${exomiser.hg38.data-directory}/whole_genome_SNVs.tsv.gz
#exomiser.hg38.cadd-in-del-path=${exomiser.hg38.data-directory}/InDels.tsv.gz
```

This is true of any `hg19` property.

**Comment by Eduardo-Auer** [comment]
@julesjacobsen Thank you very much! Everything worked perfectly!
I have one last question. Is the release of REMM for hg38 expected this year?

**Comment by visze** [comment]
We are working on a GRCh38 ReMM release. The plan was to release it in the end of last year but we are a bit behind our shedule. We trained a new model with features on GRCh38 and performance tests are looking good. But The final step, creating a prescored genome-wide file and making a proper release note is still missing.

**Comment by Eduardo-Auer** [comment]
@julesjacobsen Thank you for the quick response! I believe that any issue or question was solved and answered.

Best regards,
Eduardo
