### ISSUE TITLE
how to output OMIM information

### ISSUE THREAD

**Issue by JeWeizhong** [exomiser/Exomiser#396]
I want to output comment OMIM information for each column .

```shell
java -Xms2g -Xmx4g -jar exomiser-cli-12.1.0.jar --analysis examples/test-analysis-exome.yml
```
Currently results files comment CADD, EXAC, SIFT .etc information,

then how to set the  parameters to output OMIM information.

Thanks.

**Comment by julesjacobsen** [comment]
This information is also available in the `TSV_GENE` output file.
