### ISSUE TITLE
Same prediction score for most of the variants

### ISSUE THREAD

**Issue by Hmllycat** [exomiser/Exomiser#399]
When running all three of the exomiser tools(hiPHIVE, PHIVE, PHENIX), the output vcf files indicates that most of the variants have the same ExGeneSCombi score, which is abnormal.

could you please have a look on my log file?
[hiPHIVE.log](https://github.com/exomiser/Exomiser/files/6575676/hiPHIVE.log)

here is my yml file:
---
analysis:
   genomeAssembly: hg38
   vcf: /encrypted/e3001/Yang/hypothyrism/all_yml/super/super2.vcf
   hpoIds: [HP:0000821, HP:0001324, HP:0003394, HP:0000853, HP:0000821, HP:0002354, HP:0012378, HP:0000966, HP:0001254,   HP:0001609, HP:0002019, HP:0002925, HP:0003401, HP:0000958, HP:0003388, HP:0040283]
   analysisMode: PASS_ONLY
   steps: [ 
       hiPhivePrioritiser: {},
       regulatoryFeatureFilter: {}
   ]
outputOptions : 
   outputContributingVariantsOnly : false
   numGenes : 0
   outputPrefix : /encrypted/e3001/Yang/hypothyrism/all_yml/super/results/hiPHIVE/super2.exomiser
   outputFormats : [VCF]

**Comment by julesjacobsen** [comment]
What are you trying to achieve? You've not applies any variant filters  e.g. frequency or pathogenicity, so these will not be applied to any variants in the file and they will be given a default score based on the predicted variant effect only.

**Comment by julesjacobsen** [comment]
no response...
