### ISSUE TITLE
Use Exomiser Programmatically

### ISSUE THREAD

**Issue by rejwan052** [exomiser/Exomiser#403]
Need an example how to use exomiser as a library. That mean how to use **exomiser-spring-boot-starter** in spring boot application.

**Comment by julesjacobsen** [comment]
Try reading the source code for Exomiser!

https://github.com/exomiser/Exomiser/blob/13.0.0/exomiser-cli/src/main/java/org/monarchinitiative/exomiser/cli/ExomiserCommandLineRunner.java

But this depends what you want to do and what kind of application you want to write. In a nutshell you want to include the exomiser-spring-boot-starter in your pom.xml and then wire in the exomiser components that you need in your application.
