### ISSUE TITLE
The REST service has not been started successfully

### ISSUE THREAD

**Issue by ashamehta** [exomiser/Exomiser#405]
Hi, I'm using the tool, AnnotSV, which uses Exomiser, and on some of my runs, I receive this error when it comes to the Exomiser step:
```
WARNING: No Exomiser annotations available.
The REST service has not been started successfully:
java -Xmx4g -jar file/path/exomiser-rest-prioritiser-12.1.0.jar --server.port=50000 --spring.config.location=file/path/20210806-091848_exomiser_application.properties >& file/path/20210806-091848_exomiser.tmp
```
This doesn't happen all the time and I haven't been able to identify contributing factors. Does anyone know what might be causing this?

Thanks in advance,
Asha

**Comment by schmattes42** [comment]
Was there any solution to this? I am facing the same issue.

**Comment by ashamehta** [comment]
@schmattes42 The problem ended up being was that that my computer did not have enough memory to run this locally. When I run it on an HPC cluster, I never get this error.
