### ISSUE TITLE
grch37 ensembl site

### ISSUE THREAD

**Issue by Eduardo-Auer** [exomiser/Exomiser#411]
I would like to know if it is possible to link the annotation of transcripts in the new Ensembl! version (version 104 - GRCh38.p13) site. Because in hg38 analysis, the transcripts are linked to the old version site from Ensembl! (GRCh37.p13). Moreover, some transcripts are not present in this old version (for an example, ORAI1-202 or ENST00000617316.2).

**Comment by oqe** [comment]
Same issue here. 

Analysis done in "**_genomeAssembly: hg38_**" option gives analysis output html -file's transcript links in **GRCh37**, grch37.ensembl.org/Homo_sapiens/Transcript/Summary?t=ENST000....

**Comment by julesjacobsen** [comment]
Fixed in commit [3a7b1ec](https://github.com/exomiser/Exomiser/commit/3a7b1ec1001a4812427f178faf92473f2e3ae99b)
