### ISSUE TITLE
exomiser-rest-prioritiser 13.0?

### ISSUE THREAD

**Issue by holtgrewe** [exomiser/Exomiser#414]
Would it be possible to get a recent release of the `exomiser-rest-prioritiser` JAR file for the 13.0.x release?

**Comment by your-highness** [comment]
I would also be highly interested in a `exomiser-rest-prioritiser-13.1.0.jar` to use the latest functional features and the 2202 data release. 

Last version has been exomiser-rest-prioritiser-12.1.0.jar (45.8 MB) from 23 Jan 2020

**Comment by your-highness** [comment]
Any progress here? Any help needed?

**Comment by your-highness** [comment]
https://github.com/exomiser/Exomiser/releases/tag/13.2.0 now provides `exomiser-rest-prioritiser-13.2.0.jar` :smile:
