### ISSUE TITLE
Regarding the annotation scores 

### ISSUE THREAD

**Issue by azzatha** [exomiser/Exomiser#419]
Greetings, 

I have a question regarding the difference between different annotation scores in the VCF file:
```
##INFO=<ID=ExContribAltAllele,Number=A,Type=Flag,Description="Exomiser alt allele id contributing to score">
##INFO=<ID=ExGeneSCombi,Number=A,Type=Float,Description="Exomiser gene combined score">
##INFO=<ID=ExGeneSPheno,Number=A,Type=Float,Description="Exomiser gene phenotype score">
##INFO=<ID=ExGeneSVar,Number=A,Type=Float,Description="Exomiser gene variant score">
##INFO=<ID=ExGeneSymbId,Number=A,Type=String,Description="Exomiser gene id">
##INFO=<ID=ExGeneSymbol,Number=A,Type=String,Description="Exomiser gene symbol">
##INFO=<ID=ExVarEff,Number=A,Type=String,Description="Exomiser variant effect">
##INFO=<ID=ExVarHgvs,Number=A,Type=String,Description="Exomiser variant hgvs">
##INFO=<ID=ExVarScore,Number=A,Type=Float,Description="Exomiser variant score">
```
I assume that the ExGeneSCombi is the main one that considers both the variant effect and the phenotypes, is that right? if this is the case I noticed that the prediction score is high for large for a large number of variants, but the ExVarScore is quite distinct between different variants based on the input phenotypes! so, it would be useful if you can provide a bit more details explaining the difference between different annotation scores.

Thanks!

**Comment by julesjacobsen** [comment]
Hi @azzatha, yes you are correct the `ExGeneSCombi` is the Gene Combined Score which will be the same for all variants in that gene. The score is computed by combining the gene phenotype score and top variant score for that gene. The `ExVarScore` is specific for that particular variant and independent of the input phenotype.

Hope this is clear.
