### ISSUE TITLE
Supporting data unavailable 

### ISSUE THREAD

**Issue by LiviaMoura** [exomiser/Exomiser#426]
Hello,

Is there any other link that I could access the exomiser`s data?
We are trying to download it from http://data.monarchinitiative.org/exomiser/latest but there is no data there.

Bests

**Comment by LiviaMoura** [comment]
after 2 days, the website was back to normal...

**Comment by julesjacobsen** [comment]
Hi @LiviaMoura

I've recently started to add direct links to the data in the release page:
    https://github.com/exomiser/Exomiser/releases/tag/13.0.0

and also on the new discussions board:
    https://github.com/exomiser/Exomiser/discussions
