### ISSUE TITLE
Issues with batch mode

### ISSUE THREAD

**Issue by DiyaPrabhuram** [exomiser/Exomiser#427]
Hello!
 
I've been trying to run exomiser in batch mode for large sets of variants. I've tried but failed with 2000, 1000, 800, 400 and 200 variants. I even tried uncommenting and changing up the caffeine cache option in application.properties but the exomiser run just gets killed on its own without any error message.

I think it's also worth mentioning that I've used --analysis-batch before and it worked with 2 sets of 400 variants. It's just strange that it no longer works even if I go lower than 400 now. Has something like this happened before?

Any suggestions are appreciated. Thank you!

Cheers,
Diya

**Comment by julesjacobsen** [comment]
Hi @DiyaPrabhuram, the size of the job shouldn't be an issue as we routinely use the `--analysis-batch` option for running WGS samples containing ~8 million variants.

Can you provide any details on the command you used to run the batch, the setup in the application.properties and also the system you're trying to run it on?

**Comment by DiyaPrabhuram** [comment]
Just another add-on to what I mentioned earlier - Each variant is buried in a background file that already contains a large number of variants. I'm counting each file like this as one variant.

I'm running the analysis on a t2.large ec2-instance which has about 8GB RAM and 2 CPUs. 

Here's the command I'm using (400_batch.txt contains the path to each yml file generated for each variant input):

`java -Xms4g -Xmx5g -jar exomiser-cli-13.0.1.jar --analysis-batch /home/ec2-user/yml_files/400_batch.txt` 

Here's a look at the application.properties file as well (I tried increasing the cache size but that made no difference):

**#                                                                                                                                                                                                                  # The Exomiser - A tool to annotate and prioritize genomic variants                                                                                                                                                #                                                                                                                                                                                                                  # Copyright (c) 2016-2021 Queen Mary University of London.                                                                                                                                                         # Copyright (c) 2012-2016 Charité Universitätsmedizin Berlin and Genome Research Ltd.                                                                                                                              #                                                                                                                                                                                                                  # This program is free software: you can redistribute it and/or modify                                                                                                                                             # it under the terms of the GNU Affero General Public License as                                                                                                                                                   # published by the Free Software Foundation, either version 3 of the                                                                                                                                               # License, or (at your option) any later version.                                                                                                                                                                  #                                                                                                                                                                                                                  # This program is distributed in the hope that it will be useful,                                                                                                                                                  # but WITHOUT ANY WARRANTY; without even the implied warranty of                                                                                                                                                   # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                                                                                                                                                    # GNU Affero General Public License for more details.                                                                                                                                                              #                                                                                                                                                                                                                  # You should have received a copy of the GNU Affero General Public License                                                                                                                                         # along with this program.  If not, see <http://www.gnu.org/licenses/>.                                                                                                                                            #                                                                                                                                                                                                                                                                                                                                                                                                                                     ## exomiser root data directory ##                                                                                                                                                                                 # root path where data is to be downloaded and worked on it is assumed that all the files required by exomiser listed                                                                                              # in this properties file will be found in the data directory, unless specifically overridden here.                                                                                                                exomiser.data-directory=/home/ec2-user/exomiser/                                                                                                                                                                                                                                                                                                                                                                                      ## optional data sources ##                                                                                                                                                                                        # The location of these files need to be specified for each assembly in the sections below                                                                                                                         # REMM can be downloaded from https://zenodo.org/record/4768448                                                                                                                                                    # REMM is required for the genome preset.                                                                                                                                                                          remm.version=0.3.1.post1                                                                                                                                                                                           # CADD can be downloaded from http://cadd.gs.washington.edu/download                                                                                                                                               # CADD is an optional datasource                                                                                                                                                                                   cadd.version=1.4                                                                                                                                                                                                                                                                                                                                                                                                                      ### hg19 assembly ###                                                                                                                                                                                              #exomiser.hg19.data-version=2109                                                                                                                                                                                   # transcript source will default to ensembl. Can define as ucsc/ensembl/refseq                                                                                                                                     #exomiser.hg19.transcript-source=ensembl                                                                                                                                                                           # location of CADD/REMM Tabix files - you will need these for analysis of non-coding variants.                                                                                                                     # You will require the tsv.gz and tsv.gz.tbi (tabix) file pairs.                                                                                                                                                   # Un-comment and add the full path to the relevant tsv.gz files if you want to enable these.                                                                                                                       #exomiser.hg19.cadd-snv-path=${exomiser.data-directory}/cadd/${cadd.version}/hg19/whole_genome_SNVs.tsv.gz                                                                                                         #exomiser.hg19.cadd-in-del-path=${exomiser.data-directory}/cadd/${cadd.version}/hg19/InDels.tsv.gz                                                                                                                 #exomiser.hg19.remm-path=${exomiser.data-directory}/remm/ReMM.v${remm.version}.hg19.tsv.gz                                                                                                                         # local frequencies are required to be normalised in the same manner as the input VCF and frequency values must be percentages.
#exomiser.hg19.local-frequency-path=${exomiser.data-directory}/local/local_frequency_test_hg19.tsv.gz                                                                                                              #exomiser.hg19.variant-white-list-path=${exomiser.hg19.data-version}_hg19_clinvar_whitelist.tsv.gz                                                                                                                                                                                                                                                                                                                                    ### hg38 assembly ###                                                                                                                                                                                              # To enable analysis of samples called against the hg38 assembly copy the hg19 above and just replace the hg19 with hg38                                                                                           exomiser.hg38.data-version=2109                                                                                                                                                                                    exomiser.hg38.data-directory=${exomiser.data-directory}/${exomiser.hg38.data-version}_hg38                                                                                                                         #exomiser.hg38.cadd-snv-path=${exomiser.data-directory}/cadd/${cadd.version}/whole_genome_SNVs.tsv.gz                                                                                                              #exomiser.hg38.cadd-in-del-path=${exomiser.data-directory}/cadd/${cadd.version}/InDels.tsv.gz                                                                                                                      #exomiser.hg38.remm-path=${exomiser.data-directory}/remm/ReMM.v${remm.version}.hg38.tsv.gz                                                                                                                         #exomiser.hg38.local-frequency-path=${exomiser.data-directory}/local/local_frequency_test_hg38.tsv.gz                                                                                                              exomiser.hg38.variant-white-list-path=${exomiser.hg38.data-version}_hg38_clinvar_whitelist.tsv.gz                                                                                                                                                                                                                                                                                                                                     ### phenotypes ###                                                                                                                                                                                                 exomiser.phenotype.data-version=2109                                                                                                                                                                               exomiser.phenotype.data-directory=${exomiser.data-directory}/${exomiser.phenotype.data-version}_phenotype                                                                                                          # String random walk data file                                                                                                                                                                                     #exomiser.phenotype.random-walk-file-name=rw_string_10.mv                                                                                                                                                          #exomiser.phenotype.random-walk-index-file-name=rw_string_9_05_id2index.gz                                                                                                                                                                                                                                                                                                                                                            ### caching ###                                                                                                                                                                                                    # If you're running exomiser in batch mode there might be some performance benefit if you enable caching. The 'simple'                                                                                             # option will continue to store data in memory *without* limit - this means for really long-running batch jobs and/or
# whole genomes you may run out of memory.                                                                                                                                                                         # If this is likely choose the caffeine option and uncomment spring.cache.caffeine.spec and adjust the cache size                                                                                                  # to your requirements                                                                                                                                                                                             #none/simple/caffeine                                                                                                                                                                                              #spring.cache.type=simple                                                                                                                                                                                           #spring.cache.caffeine.spec=maximumSize=60000                                                                                                                                                                                                                                                                                                                                                                                          ### logging ###                                                                                                                                                                                                    #logging.file.name=logs/exomiser.log**

**Comment by DiyaPrabhuram** [comment]
Here's the application.properties file:

```
#
# The Exomiser - A tool to annotate and prioritize genomic variants
#
# Copyright (c) 2016-2021 Queen Mary University of London.
# Copyright (c) 2012-2016 Charité Universitätsmedizin Berlin and Genome Research Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

## exomiser root data directory ##
# root path where data is to be downloaded and worked on it is assumed that all the files required by exomiser listed
# in this properties file will be found in the data directory, unless specifically overridden here.
exomiser.data-directory=/home/ec2-user/exomiser/

## optional data sources ##
# The location of these files need to be specified for each assembly in the sections below
# REMM can be downloaded from https://zenodo.org/record/4768448
# REMM is required for the genome preset.
remm.version=0.3.1.post1
# CADD can be downloaded from http://cadd.gs.washington.edu/download
# CADD is an optional datasource
cadd.version=1.4

### hg19 assembly ###
#exomiser.hg19.data-version=2109
# transcript source will default to ensembl. Can define as ucsc/ensembl/refseq
#exomiser.hg19.transcript-source=ensembl
# location of CADD/REMM Tabix files - you will need these for analysis of non-coding variants.
# You will require the tsv.gz and tsv.gz.tbi (tabix) file pairs.
# Un-comment and add the full path to the relevant tsv.gz files if you want to enable these.
#exomiser.hg19.cadd-snv-path=${exomiser.data-directory}/cadd/${cadd.version}/hg19/whole_genome_SNVs.tsv.gz
#exomiser.hg19.cadd-in-del-path=${exomiser.data-directory}/cadd/${cadd.version}/hg19/InDels.tsv.gz
#exomiser.hg19.remm-path=${exomiser.data-directory}/remm/ReMM.v${remm.version}.hg19.tsv.gz
# local frequencies are required to be normalised in the same manner as the input VCF and frequency values must be percentages.
#exomiser.hg19.local-frequency-path=${exomiser.data-directory}/local/local_frequency_test_hg19.tsv.gz
#exomiser.hg19.variant-white-list-path=${exomiser.hg19.data-version}_hg19_clinvar_whitelist.tsv.gz

### hg38 assembly ###
# To enable analysis of samples called against the hg38 assembly copy the hg19 above and just replace the hg19 with hg38
exomiser.hg38.data-version=2109
exomiser.hg38.data-directory=${exomiser.data-directory}/${exomiser.hg38.data-version}_hg38
#exomiser.hg38.cadd-snv-path=${exomiser.data-directory}/cadd/${cadd.version}/whole_genome_SNVs.tsv.gz
#exomiser.hg38.cadd-in-del-path=${exomiser.data-directory}/cadd/${cadd.version}/InDels.tsv.gz
#exomiser.hg38.remm-path=${exomiser.data-directory}/remm/ReMM.v${remm.version}.hg38.tsv.gz
#exomiser.hg38.local-frequency-path=${exomiser.data-directory}/local/local_frequency_test_hg38.tsv.gz
exomiser.hg38.variant-white-list-path=${exomiser.hg38.data-version}_hg38_clinvar_whitelist.tsv.gz

### phenotypes ###
exomiser.phenotype.data-version=2109
exomiser.phenotype.data-directory=${exomiser.data-directory}/${exomiser.phenotype.data-version}_phenotype
# String random walk data file
#exomiser.phenotype.random-walk-file-name=rw_string_10.mv
#exomiser.phenotype.random-walk-index-file-name=rw_string_9_05_id2index.gz

### caching ###
# If you're running exomiser in batch mode there might be some performance benefit if you enable caching. The 'simple'
# option will continue to store data in memory *without* limit - this means for really long-running batch jobs and/or
# whole genomes you may run out of memory.
# If this is likely choose the caffeine option and uncomment spring.cache.caffeine.spec and adjust the cache size
# to your requirements
#none/simple/caffeine
#spring.cache.type=simple
#spring.cache.caffeine.spec=maximumSize=60000

### logging ###
#logging.file.name=logs/exomiser.log
```
