### ISSUE TITLE
Disabling hg19 for rest prioritiser

### ISSUE THREAD

**Issue by holtgrewe** [exomiser/Exomiser#430]
My `application.properties` looks like this:

```
exomiser.data-directory=/data
exomiser.hg38.data-version=1909
exomiser.phenotype.data-version=1909
exomiser.phenotype.random-walk-file-name=rw_string_10.mv
```

When I startup the REST prioritiser, I get the following Exception:

```
Parameter 1 of constructor in org.monarchinitiative.exomiser.rest.prioritiser.api.PrioritiserController required a single bean, but 2 were found:
        - hg19genomeAnalysisService: defined by method 'genomeAnalysisService' in org.monarchinitiative.exomiser.autoconfigure.genome.Hg19GenomeAnalysisServiceAutoConfiguration
        - hg38genomeAnalysisService: defined by method 'genomeAnalysisService' in org.monarchinitiative.exomiser.autoconfigure.genome.Hg38GenomeAnalysisServiceAutoConfiguration
```

What's the best step forward here to disable hg19?

**Comment by holtgrewe** [comment]
Pardon my ignorance, for the REST service with hg19 data should just work for GRCh38 as it's only considering genes anyway.

**Comment by julesjacobsen** [comment]
@holtgrewe did you get this sorted? It should be possible to do what you wanted with the latest release.

**Comment by holtgrewe** [comment]
Actually, I realized that the REST prioritizer just works with lists of genes and lists of hpo terms so hg19 data works for both hg19 and hg38 gene/hpo lists.

**Comment by julesjacobsen** [comment]
Yes - you don't actually need either genome build in 13.0.1. For example the following will start:

```properties
exomiser.data-directory=/data
exomiser.phenotype.data-version=1909
exomiser.phenotype.random-walk-file-name=rw_string_10.mv
```
