### ISSUE TITLE
Hard-coded gene link results

### ISSUE THREAD

**Issue by iimpulse** [exomiser/Exomiser#432]
https://github.com/exomiser/Exomiser/blob/e2987aefc45e265d712a0b90b7dbff68af4dba95/exomiser-core/src/main/resources/templates/results.html#L160

This link is hard-coded to be hg19 and not dependent on the exomiser genome assembly selection.

**Comment by julesjacobsen** [comment]
Duplicates #411

**Comment by julesjacobsen** [comment]
Fixed in commit [3a7b1ec](https://github.com/exomiser/Exomiser/commit/3a7b1ec1001a4812427f178faf92473f2e3ae99b)
