### ISSUE TITLE
Error in running exomiser web in v13.0.1

### ISSUE THREAD

**Issue by furbelows** [exomiser/Exomiser#433]
``Hi, I built exomiser on Ubuntu linux box using mvn install.

I seem to get the error below when trying to start the webserver. Any help would be greatly appreciated!

`Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-04-14 13:09:45.052 ERROR 11204 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method dataSource in org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Hikari required a single bean, but 4 were found:
	- spring.datasource-org.springframework.boot.autoconfigure.jdbc.DataSourceProperties: defined in null
	- phenotypeDataSourceProperties: defined by method 'phenotypeDataSourceProperties' in org.monarchinitiative.exomiser.autoconfigure.phenotype.PhenotypeProperties
	- hg19genomeDataSourceProperties: defined by method 'hg19genomeDataSourceProperties' in org.monarchinitiative.exomiser.autoconfigure.genome.Hg19GenomeProperties
	- hg38genomeDataSourceProperties: defined by method 'hg38genomeDataSourceProperties' in org.monarchinitiative.exomiser.autoconfigure.genome.Hg38GenomeProperties

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
`

**Comment by julesjacobsen** [comment]
Have you supplied the `application.properties` file? It can sit next to the exomiser-web.jar on the filesystem.

**Comment by julesjacobsen** [comment]
Closing due to lack o response
