### ISSUE TITLE
The frequency results shown by the exomizer are different from the database.

### ISSUE THREAD

**Issue by luceamso** [exomiser/Exomiser#434]
Hi,

Since the frequency of my vcf files and the results of exomiser are different in gnomad v2.1.1 browser, I checked in gnomad browser but couldn't find variants. I used hg19 assembly and its variants were 10-105362069-C-T. 
The frequency data showed by exomiser is as follows:
ExAC EAS: 0.0116%
gnomAD_E_EAS: 0.0058%
And the frequency of other variants is not the same in exomiser and gnomad v2.1.1 browser. For example, for the 16-86580246-TC-T of gene MTHFSD, the genome_AMR frequencies of exomiser and gnomAD v2.1.1 browsers were 0.1193% and 0.1182%, respectively.
Could you please have a look this issue?
I would appreciate it if you check #431 as well.
Thank you.

**Comment by naiarabediaga** [comment]
Hi Lucesmso, 

We can see you have closed the issue, I was wondering if you have found out why the frequencies do not match. I am having the same issue. Thank a lot !
