### ISSUE TITLE
Documentation on SV prioritization 

### ISSUE THREAD

**Issue by josephhalstead** [exomiser/Exomiser#445]
Hi,

Thankyou for making such a great tool! I'm looking at expanding our usage of Exomiser to include prioritization of SVs too.  I saw that in release 13 you've included support for this. Is there any documentation that explains how exomiser handles these variants e.g. what if it overlaps multiple genes etc?

Many Thanks,

Joseph

**Comment by julesjacobsen** [comment]
Hi Joseph - You're welcome! I'm currently producing some updated documentation for the upcoming 13.1.0 release - see https://exomiser.readthedocs.io/

To answer your specific question about overlapping multiple genes - Exomiser considers each gene independently and a variant will be featured as contributing to all the genes it overlaps.

**Comment by josephhalstead** [comment]
Perfect! I'll have a read once you make the next release

**Comment by julesjacobsen** [comment]
@josephhalstead https://github.com/exomiser/Exomiser/releases/tag/13.1.0

**Comment by josephhalstead** [comment]
Perfect
