### ISSUE TITLE
Error during analysis Exomiser 13.1.0

### ISSUE THREAD

**Issue by JirefV** [exomiser/Exomiser#448]
Hello,

I can't understand the error during the analysis. I tiped "java -Xms2g -Xmx4g -jar exomiser-cli-13.1.0.jar --analysis examples/test-analysis-exome-PT1.yml" and this is the error:
![immagine](https://user-images.githubusercontent.com/110402102/182158077-5419d149-3550-4643-9adb-a746a7a3e344.png)

**Comment by ielis** [comment]
Where is your data folder?

**Comment by ielis** [comment]
[This](https://exomiser.readthedocs.io/en/latest/installation.html#configuring-the-application-properties) can be helpful.
