### ISSUE TITLE
2022 models missing

### ISSUE THREAD

**Issue by Tintest** [exomiser/Exomiser#449]
Hello,

This is not an issue strictly speaking about Exomiser. I am sorry if I am not in the right place to make my request.

In the documentation of Exomiser, in tutorial section, it is shown to download models labeled 2202 (https://data.monarchinitiative.org/exomiser/latest/2202_hg38.zip for example). But these files are not available on the Monarch website. In addition, in Exomiser's code the model files used are labeled 2109. I have not been able to find 2202 files elsewhere.

Having used Exomiser in the past, I know that the first numbers correspond to the year and month. 

Would it be possible to have links for the February 2022 models?

In the worst case, I will settle for the 2021 models.

Thank you.

**Comment by damiansm** [comment]
Apologies for the confusion and the delay in replying as people were away
on leave. The new data release was announced slightly differently and with
new links at
https://github.com/exomiser/Exomiser/discussions/424

Let us fix the documentation to make sure everyone knows where to go now.

**Comment by Tintest** [comment]
Hello,

Thank you for your quick reply. I will download these new data ;)

Regards.

**Comment by julesjacobsen** [comment]
data.monarchinitiative.org/exomiser/latest now has the actual latest data linked.
