### ISSUE TITLE
Is there a way to disable ClinVar for testing ?

### ISSUE THREAD

**Issue by Tintest** [exomiser/Exomiser#459]
Hello,

I am working on a project for which I want to use Exomiser. For this, I want to qualify it on a true positive patient dataset from my laboratory, for which the diagnostic variants have been uploaded in ClinVar. I would like to test the performances of the tool without relying on the ClinVar data as this represents a confirmation bias.

I have commented in the ```application.properties``` file the ```exomiser.hg38.variant-white-list-path``` and ```exomiser.hg19.variant-white-list-path``` values, but the ClinVar data is still in the HTML report. Is there a way to completely disable ClinVar in Exomiser? 

Regards.

**Comment by damiansm** [comment]
Hi,

This is a bit confusing but you have done the right thing by disabling it
in the application.properties file. The data still displayed in the HTML
report is just for user information then but does not contribute to the
variant or overall scores. Basically if those two whitelist files are used
in Exomiser, any variants found in those files get a max variant score of 1
regardless of the usual sources of variant score data: allele frequency,
predicted pathogenicity etc.

Best wishes
Damian

**Comment by Tintest** [comment]
Hello,

Thank you for your prompt answer.

Regards.
