### ISSUE TITLE
Missing maven artefacts for sonumina - PhenIX dependencies.

### ISSUE THREAD

**Issue by julesjacobsen** [exomiser/Exomiser#460]
The repository http://sonumina.de/maven has vanished without trace. These jar files need adding to the local maven repository for the build to complete:

[sonumina.tar.gz](https://github.com/exomiser/Exomiser/files/9920677/sonumina.tar.gz)

These are required for PhenIX to function, however the source data for this has become very stale so we're going to remove it from the application.

**Comment by pnrobinson** [comment]
can we instead work on updating PhenIX? There is no reason it could not be run from other data available, possibly with a few minor tweaks.

**Comment by julesjacobsen** [comment]
OK, but for the time being this will have to be disabled as unless someone has these artifacts available in their maven repo, Exomiser will not build.

**Comment by sam-osia** [comment]
I'm quite new to the field. I was trying to build exomiser and have ran into this issue. Is there anyway around this at the moment?

**Comment by julesjacobsen** [comment]
@sam-osia Yes, install the artifacts I provided in the tar file to your maven repo where you're building exomiser. Alternatively, download the pre-built binary from the releases page.

**Comment by julesjacobsen** [comment]
This is now fixed on the `development` branch and set for the 13.2.0 release.
