### ISSUE TITLE
OMIM link problem (HTML Phenotypic similarity field)

### ISSUE THREAD

**Issue by josealvesferrao** [exomiser/Exomiser#465]
Hi,

First of all thank you very much for developing and maintaining such a great tool!

I having some problems in links to OMIM on Exomiser HTML. The ones included in the Known diseases field are ok, but the ones included in the Phenotypic similarity field give an error when accessing OMIM. I think the problem is just the "entry" word is missing on the link, it´s appearing as e.g. www.omim.org/618820 and should be www.omim.org/**entry/**618820

I´m using version 13.1.0 on Linux (downloaded on the 6th of october from https://data.monarchinitiative.org/exomiser/latest/exomiser-cli-13.1.0-distribution.zip).

José Ferrão

**Comment by julesjacobsen** [comment]
Thanks for the feedback @josealvesferrao! This is fixed in the 13.2.0 release.
