### ISSUE TITLE
Exomiser data versions

### ISSUE THREAD

**Issue by awab-ahmed** [exomiser/Exomiser#467]
Where can I find details about the versions of the different databases in older versions of exomiser data. I can only find info for version 2209 here: https://github.com/exomiser/Exomiser/discussions/452. Thanks.

**Comment by julesjacobsen** [comment]
Sorry, I've not got them catalogued, we only started publishing them on release. They would have been prepared using the latest data versions at the time of release, so you should be able to work it out, but I guess that's not really going to help you.
