### ISSUE TITLE
gene pheno scores

### ISSUE THREAD

**Issue by naamaeb** [exomiser/Exomiser#468]
Hi,

Where can I find more information regarding the calculation of the:
EXOMISER_GENE_PHENO_SCORE
EXOMISER_GENE_VARIANT_SCORE
?

I have a pathogenic variant in the GLA gene (causes Fabri) and I'm running the exome with 2 general hpo terms of kidney pathology (HP:0012210 - Abnormal renal morphology and HP:0012211 abnormal renal physiology), which cover one of the disease phenotypes.

These are the scores I get for the gene:
EXOMISER_GENE_COMBINED_SCORE - 0.0000
EXOMISER_GENE_PHENO_SCORE - 0.9124
EXOMISER_GENE_VARIANT_SCORE - 0.0000

(I can only see these when running in FULL mode).
I'm trying to understand why exomiser scores these so low.

Thanks.

**Comment by julesjacobsen** [comment]
Have you looked at the FILTER column in the TSV_VARIANT file for this variant? It will tell you why it failed the filtering and has a variant score of zero.

**Comment by naamaeb** [comment]
Yes, the FILTER column says 'filter'... so not much info there.

**Comment by julesjacobsen** [comment]
That means it failed the VCF filtering before being run through Exomiser. You'll want to check why this variant failed the filtering criteria of the calling pipeline. If you're certain it's ok, you can manually set the filter to PASS in the VCF file and Exomiser will include it as a candidate in the analysis.
