### ISSUE TITLE
Adding local variant frequency database

### ISSUE THREAD

**Issue by patrickrshea** [exomiser/Exomiser#472]
I am trying to add a local variant frequency database to perform MAF filtering in Exomiser.  In response to my question on the Discussion page about blacklisting variants, I was advised to create a list of variant frequencies and point application.properties to the file path and set LOCAL in the list of frequency databases.  Can the format for this file be a simple tab-delimited text file with VariantID and MAF or does it have to be in some sort of database format?  I looked through the documentation and did not find any information on the specifications for this file format and the hg19_variants.mv.db file, which I believe contains the files for the 1KG and gnomAD MAFs, appears to be in some type of database format. However I can't tell exactly which one.

**Comment by damiansm** [comment]
Hi,

You need to prepare a tab-delimited file with the chromosome, position,
ref, alt and percentage allele frequency, make sure it is sorted by
chromosome and position and then create a tabix index of it. If you then
specify the path to it in application.properties and state LOCAL as a
frequency source in the yml configs

Best wishes
Damian

**Comment by patrickrshea** [comment]
Ok great, that's perfectly clear now.  Thanks so much for your help and taking the time to respond to my questions.
