### ISSUE TITLE
Empty inheritanceModes leads to empty output tables

### ISSUE THREAD

**Issue by genetikzentrum** [exomiser/Exomiser#481]
We noticed that when `inheritanceModes` is empty, Exomiser generates "empty" `.genes.tsv`, `.variants.tsv` and `.vcf.gz` files. Empty in the sense that the header rows exist but there is no variant/gene data. Curiously, the `.html` file still contains the expected content. To clarify, the expected content (for us) is what 13.0.0 produced.

This did not happen with version 13.0.0 and started happening with version 13.1.0. It also occurs on 13.2.0.

You can (hopefully) reproduce the issue as follows:
1. Take any analysis `.yml` in the `examples` folder, e.g., `NA19722_601952_AUTOSOMAL_RECESSIVE_POMP_13_29233225_5UTR_38` and comment out the content of `inheritanceModes`.
2. Run Exomiser as usual (`--analysis <the yml file>`)
3. Inspect the generated files (except `.html`) and notice the lack of data

We expected this usecase to be supported according to the comment on https://exomiser.readthedocs.io/en/latest/advanced_analysis.html#inheritancemodes, are we missing something?

Thanks for the work on Exomiser and Genomiser!

**Comment by julesjacobsen** [comment]
Hi! Sorry about the issue and thanks for an easily reproducible bug report! I hope you found a workaround to the issue (adding ANY: 2.0 to the `inheritanceModes`) whilst this was broken.

This will be fixed in the upcoming 13.2.1 release...
