### ISSUE TITLE
ERROR 88104 --- [           main] o.m.e.c.g.j.JannovarDataProtoSerialiser  : Unable to deserialise data

### ISSUE THREAD

**Issue by enricoperez** [exomiser/Exomiser#484]
Dear all,

I am in trouble.
I am trying to process a vcf.gz file through GENOMISER/EXOMISER. I have encounter these errors but I am not sure what it all means.

One of the errors it said that file: "2209_hg38_transcripts_ensembl.ser" (No such file or directory). But I know that it exist because I download it and open the zip file. I tried to search online for the problem and saw that people download the file once again and unzip it from terminal: unzip 2209_hg38.zip, but it did not work for me.

Please, help. What am I doing wrong? What can I do? The path to the directory where the files from 2209_hg38 is marked in the .yml file. The application.properties is also updated to note the changes. They are all attached to this query. I added the .txt to the files to attached them to this query.

Thank you

[the_run.txt](https://github.com/exomiser/Exomiser/files/10949605/the_run.txt)
[application.properties.txt](https://github.com/exomiser/Exomiser/files/10949615/application.properties.txt)
[00_template.yml.txt](https://github.com/exomiser/Exomiser/files/10949642/00_template.yml.txt)

**Comment by damiansm** [comment]
Hi

Config looks correct to me so likely a file access issue? What do you get
when you

ls -l
/Users/the-boss/my_tools/jars/exomiser_genomiser/databases/currently_in_use/data/exomiser-data/2209_hg38/2209_hg38_transcripts_ensembl.ser

from the directory you are running Exomiser from?

Best wishes
Damian

**Comment by enricoperez** [comment]
Thank you Damian for you response.

I just realised that I when I placed the path to the document I used twice /2209_hg38/ to get to the folder. Once I deleted it all went very smooth.

I am sorry this was an easy mistake. I had been trying to work this one for almost two weeks. Not much of computer skills here when it comes to command line.

thank you
