### ISSUE TITLE
Genomad frequency results shown by the exomizer different from gnomad v3.1.2  (hg38)

### ISSUE THREAD

**Issue by naiarabediaga** [exomiser/Exomiser#493]
Hi, 

Thank you so much for this amazing tool. 

I am having a similar issue to #434, ie  gnomad frequency variants in exomiser not being the same as in gnomad v3.1.2 database/brower. I am working with the hg38. I have asked @luceamso (who opened and closed this issue) how he/she solved the issue, but I have thought it may be better to post it as a new issue. I hope this is ok. 

Best,

**Comment by julesjacobsen** [comment]
Hi @naiarabediaga. Exomiser uses gnomAD 2.0.1 data (https://github.com/exomiser/Exomiser/discussions/487). This will be different from gnomAD 3.1.2. We're hoping to update to gnomAD 3 in an upcoming release.
