### ISSUE TITLE
Add new points based ACMG classification

### ISSUE THREAD

**Issue by julesjacobsen** [exomiser/Exomiser#514]
The [ClinGen SVI working group](https://clinicalgenome.org/working-groups/sequence-variant-interpretation/) recommend using a [points based system for calculating ACMG classifications](https://clinicalgenome.org/docs/fitting-a-naturally-scaled-point-system-to-the-acmg-amp-variant-classification-guidelines/)

This is based on their earlier publication [Modeling the ACMG/AMP variant classification gudielines as a Bayesian classification framework](https://clinicalgenome.org/docs/modeling-the-acmg-amp-variant-classification-gudielines-as-a-bayesian-classification-framework/)

Exomiser uses the recommendations for PP3/BP4 scaling based on the REVEL score detailed in [Calibration of computational tools for missense variant pathogenicity classification and ClinGen recommendations for PP3/BP4 criteria](https://clinicalgenome.org/docs/calibration-of-computational-tools-for-missense-variant-pathogenicity-classification-and-clingen-recommendations-for-pp3-bp4-cri/) which crucially allow for BP4_Moderate which was not accounted for in the original ACMG/AMP recommendations. The authors mention:

>A second approach would be to use the Tavtigian et al. framework,[9](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9748256/#bib9) in either its initial iteration (see [supplemental methods](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9748256/#mmc1) for suggested modifications), or in its simplified, points-based iteration,[34](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9748256/#bib34) in which BP4_Moderate evidence would count as −2 points toward variant classification.

Given the changes in strengths from other recommendations e.g. PM2_Supporting (#502) and the required updates to combining rules, it is more robust to simply use the points-based approach and deprecate the other implementations for removal in the next major version.

**Comment by damiansm** [comment]
This is all based on the new ACMG classification that is about to released very soon right? Is it worth waiting for that in case of any last minute tweaks or is that on the website anyway?

**Comment by julesjacobsen** [comment]
No, this is just updating to the current latest recommendations.
