### ISSUE TITLE
integrate alphamissense

### ISSUE THREAD

**Issue by cmungall** [exomiser/Exomiser#520]
https://github.com/deepmind/alphamissense

https://www.science.org/doi/10.1126/science.adg7492

**Comment by damiansm** [comment]
Done already ;-) Or in progress at least

**Comment by Bioinf-usr** [comment]
Hi,

This is great, look forward to working with alphamissense :)
On a similar note is there a possibility to include our own pathogenicity scores instead of the existing ones such as REVEL, MVP etc.,?

Thank you.

**Comment by julesjacobsen** [comment]
Also worth looking at [Genome-wide prediction of disease variant effects with a deep protein language model ](https://www.nature.com/articles/s41588-023-01465-0)

**Comment by Bioinf-usr** [comment]
> Also worth looking at [Genome-wide prediction of disease variant effects with a deep protein language model ](https://www.nature.com/articles/s41588-023-01465-0)

Indeed it is also very interesting. Would be great to provide an option to incorporate such novel scoring mechanisms.

**Comment by julesjacobsen** [comment]
Will be present in 2402 data release
