### ISSUE TITLE
Some conflicting ClinVar interpretations could be displayed with better information

### ISSUE THREAD

**Issue by pnrobinson** [exomiser/Exomiser#535]
For instance, the following combination of interpretations means that we can probably discard the variant from furhter consideration, but the current Exomiser displays "conflicting interpretations", which necessitates opening the CLinVar page
```
Uncertain significance(1); Benign(3); Likely benign(2) 
```

It would be better to show something like
```
Conflicting interpretations: VUS(1);B(3);LB(2)
```

**Comment by julesjacobsen** [comment]
You're in luck - I'm working on updating some of the ClinVar stuff right now. Also, as luck would have it the ClinVar VCF file has the following `INFO` field 

```
##INFO=<ID=CLNSIGCONF,Number=.,Type=String,Description="Conflicting clinical significance for this single variant; multiple values are separated by a vertical bar">
```
which appears when CLNSIG/CLNREVSTAT list conflicting interpretations e.g. (trimming out unwanted fields)

```
1       930200  1043045 G       A       .       .       CLNREVSTAT=criteria_provided,_conflicting_interpretations;CLNSIG=Conflicting_interpretations_of_pathogenicity;CLNSIGCONF=Uncertain_significance(1)|Likely_benign(1);
1       930201  2012623 C       T       .       .       CLNREVSTAT=criteria_provided,_single_submitter;CLNSIG=Uncertain_significance;
1       930203  972363  C       T       .       .       CLNREVSTAT=criteria_provided,_multiple_submitters,_no_conflicts;CLNSIG=Uncertain_significance
```

So, yes. This is a good idea and not so hard to achieve. I'd originally though this would require collating all this from the XML dump which would have led to a more negative response!
