### ISSUE TITLE
Data for REMM is not configured

### ISSUE THREAD

**Issue by HongyuanChu** [exomiser/Exomiser#538]
![1707126329954](https://github.com/exomiser/Exomiser/assets/158466423/813182f4-6b77-4d0e-97bc-b181f40b5a5d)
**This appeared while performing** "java -Xmx6g -jar ~/exomiser-cli-13.3.0/exomiser-cli-13.3.0.jar --analysis examples/NA19722_601952_AUTOSOMAL_RECESSIVE_POMP_13_29233225_5UTR_38.yml --spring.config.location=/data/chuhy/exomiser-cli-13.3.0/application.properties --assembly hg38"
**The application.properties is as follows**
#exomiser.data-directory=data
exomiser.data-directory=/data/chuhy/exomiser-cli-13.3.0/data
exomiser.hg19.data-version=2309
exomiser.hg38.data-version=2309
exomiser.hg19.variant-white-list-path=2309_hg19_clinvar_whitelist.tsv.gz
exomiser.hg38.variant-white-list-path=2309_hg38_clinvar_whitelist.tsv.gz
exomiser.phenotype.data-version=2309
exomiser.hg38.remm-path=ReMM.v0.4.hg38.tsv.gz

**Comment by lpsyy** [comment]
I think you should put the full path of the in the application properties, for example mnt/f/exomiser/exomiser-cli-13.3.0/data/2309_hg38/remm........

**Comment by julesjacobsen** [comment]
@HongyuanChu, as @Ipsyy said, you need to use the full path to the `ReMM.v0.4.hg38.tsv.gz` file.
