### ISSUE TITLE
RPPR stats from grainyhead?

### ISSUE THREAD

**Issue by matentzn** [exomiser/Exomiser#539]
From 2023-04-01 to 2024-03-31

| Event | Total | Internal | Internal (%) | External | External (%) |
| -------- | -------- | -------- | -------- | -------- | -------- |
| Contributors | 30 | 0 |  0.00 | 30 |  100.00 |
| Issues opened | 45 | 0 |  0.00 | 45 |  100.00 |
| Issues closed | 41 | 0 |  0.00 | 41 |  100.00 |
| Pull requests opened | 1 | 0 |  0.00 | 1 |  100.00 |
| Pull requests closed | 0 | 0 |  0.00 | 0 |  0.00 |
| Pull requests merged | 0 | 0 |  0.00 | 0 |  0.00 |
| Comments | 106 | 0 |  0.00 | 106 |  100.00 |
| Commits | 30 | 0 |  0.00 | 30 |  100.00 |
| Releases | 2 | 0 |  0.00 | 2 |  100.00 |

See Email discussion about this. The internal/external only works if you give me a link to a github team that has the core team in it.

**Comment by julesjacobsen** [comment]
Thanks @matentzn
