### ISSUE TITLE
Links need to updated

### ISSUE THREAD

**Issue by Bioinf-usr** [exomiser/Exomiser#545]
Hi,

I am trying to download the latest version of exomiser along with the data. However, the latest data is not updated in the FTP site. Please check.

wget https://data.monarchinitiative.org/exomiser/latest/exomiser-cli-14.0.0-distribution.zip
wget https://data.monarchinitiative.org/exomiser/latest/2402_hg19.zip
wget https://data.monarchinitiative.org/exomiser/latest/2402_hg38.zip
wget https://data.monarchinitiative.org/exomiser/latest/2402_phenotype.zip

Thank you.

**Comment by julesjacobsen** [comment]
Oops. In the meantime, you can get the latest from the releases page and the links in the discussions about the data release:

Application: https://github.com/exomiser/Exomiser/releases/tag/14.0.0
Data: https://github.com/exomiser/Exomiser/discussions/543

**Comment by julesjacobsen** [comment]
These are now live.
