### ISSUE TITLE
SpliceAI in exomiser-14

### ISSUE THREAD

**Issue by massiddamt** [exomiser/Exomiser#546]
Hi, I'm trying to prioritize with exomiser with the following patosources: 
pathogenicitySources: [POLYPHEN, SIFT, CADD, SPLICE_AI]
but no annotation for SPLICE_AI was retrieved.
Could you please help me?

**Comment by VincenzoRallo** [comment]
Likewise, I'm trying to get the spliceai score in output files (both tsv and html), using it for variant priotization in pathogenicity data, but can't understand how to do it. Maybe I need to set it in application.properties? From which database is it retrieved? Thanks

**Comment by julesjacobsen** [comment]
Looks like the SpliceAI scores never made it into the database! Sorry about that. They should have come from the gnomAD annotations. @VincenzoRallo you just need to include it in the `pathogenicitySources: [POLYPHEN, SIFT, CADD, SPLICE_AI]` in the `analysis.yml` file used to configure the analysis for Exomiser.

**Comment by AlistairNWard** [comment]
Can I ask for a clarification? Do you mean that SpliceAI scores are not used in prioritizing variants at all (if the scores are not in the database, then I would assume they can't be used in the algorithm)? Or is it just that the SpliceAI scores are not included in the output files?

**Comment by julesjacobsen** [comment]
@AlistairNWard to clarify, this means that the scores are not present in the database. This means they can't be used at all so the presence of `SPLICE_AI` in the `pathogenicitySources` will make no difference to the pathogenicity score calculations.

**Comment by AlistairNWard** [comment]
Thanks @julesjacobsen, that was what we thought. We'll keep our eyes open for when there is an update to the database!

**Comment by VincenzoRallo** [comment]
Thanks all for the clarification! So if we modify the database by including the spliceAI scores, will Exomiser automatically be able to use this information in the prioritisation algorithm?

**Comment by ShrutiMarwaha** [comment]
@julesjacobsen Do you know if SpliceAI scores will be incorporated into Variant score in the next version of exomiser? Any estimated date for it? SpliceAI scores have proved to be highly useful.

**Comment by julesjacobsen** [comment]
These are now released in #562

**Comment by julesjacobsen** [comment]
A bit more info:

If you include SPLICE_AI, any SNP with a delta score >= 0.1 will be displayed and used. For synonymous variants this will likely give a better score than without SpliceAI, splice region missense variant scores will depend on how the other missense scores behave but will likely be lower than these. Intronic splice region SNPs (non-canonical splice sites) will benefit from these scores the most.
