### ISSUE TITLE
Usage of alphamissense

### ISSUE THREAD

**Issue by Bioinf-usr** [exomiser/Exomiser#552]
Hi,

Should we use alphamissense in combination with any of the other existing score or should it be used as standalone. In one of the documents it was mentioned to use either (POLYPHEN, MUTATION_TASTER, SIFT) or (REVEL, MVP). I have similar questions for CADD, REMM and spliceAI as well. So, just wondering what is the best approach here. Also, if there are any benchmarks available that would be great.

Thank you.

**Comment by MattWellie** [comment]
@Bioinf-usr I'm not part of this dev team, though I am a user and I've spoken with some senior people here. I'm paraphrasing, so feel free to ignore or take this with a pinch of salt:

- [REVEL, MVP] is the best combination for coding region work. If you're using version 14.0.0 and the latest data release (**2402**) you can also add AlphaMissense to that, making [**REVEL, MVP, AlphaMissense**] the best performing combination
- CADD **_or_** REMM will be useful if you also intend to branch out into non-coding regions, though they've not tried both together.
- SpliceAI annotations are going to be in an upcoming release, but these annotations will mostly impact intronic variants, so if you're focused on coding regions (and use the recommended config settings which filter to coding variants) this might not have much impact.

**Comment by julesjacobsen** [comment]
Thanks for commenting @MattWellie, this is correct. The actual required input for specifying AlphaMissense is: `[REVEL, MVP, ALPHA_MISSENSE]` as described in the `preset-exome-analysis.yml` or `test-analysis-exome.yml` files in the `examples` directory of the CLI distribution.

**Comment by Bioinf-usr** [comment]
Thanks a lot @MattWellie @julesjacobsen. That was helpful. Would try to get some benchmarks internally as well.

**Comment by julesjacobsen** [comment]
SpliceAI are now included in https://github.com/exomiser/Exomiser/discussions/562. Note we've also updated our recommendations to include ALPHA_MISSENSE along with REVEL and MVP.
