### ISSUE TITLE
Broken URLs in tutorials

### ISSUE THREAD

**Issue by matentzn** [exomiser/Exomiser#554]
I am doing https://oboacademy.github.io/obook/tutorial/exomiser-tutorial/

It seems the URL to the phenotype and variant databases dont work anymore:

2302_phenotype.zip is mentioned, but seems only 2402_phenotype.zip exists.

https://data.monarchinitiative.org/exomiser/latest/index.html

Can you fix the URLs in the tutorial? Either

1. Do not use `latest`
2. Provide a stable URL that will always work, e.g. `https://data.monarchinitiative.org/exomiser/latest/phenotype.zip` (using an htaccess alias).

cc @yaseminbridges

**Comment by nlharris** [comment]
Did this get fixed?

**Comment by julesjacobsen** [comment]
The data is all in the https://data.monarchinitiative.org/exomiser/data/index.html directory, the binaries are in https://data.monarchinitiative.org/exomiser/index.html and https://data.monarchinitiative.org/exomiser/latest/index.html contains the latest versions of all these. So, just link directly to the version you want for the tutorial would be simplest and won't break anyone's existing workflows.
