### ISSUE TITLE
Add custom pathogenicity score source

### ISSUE THREAD

**Issue by davidfstein** [exomiser/Exomiser#567]
My group has developed a variant effect prediction (VEP) method that we have seen to outperform other VEP methods (REVEL, AlphaMissense, etc.) for the prioritization of causal variants in sequencing data when these methods are employed as standalone filters. We were curious how our method would compare with other VEPs when incorporated in Exomiser. Is there a process for including novel VEP scores as sources in the Exomiser pipeline?

**Comment by julesjacobsen** [comment]
Hi @davidfstein This sounds exciting! Yes, you can add a single external data source by adding a `TEST` pathogenicity source e.g. 

```yaml
# just add 'TEST' here plus all the other default settings we recommend.
  pathogenicitySources: [TEST, ALPHA_MISSENSE, REVEL, MVP]
```

The file should be defined as tab-delimited lines in 'VCF-lite' format with the corresponding requirements e.g.:
```
#CHR   POS REF ALT SCORE
10      123279555       G       A       0.947294473648071
10      123279555       G       C       0.993917524814606
10      123279555       G       T       0.980554223060608
```
Where:
`#` is the comment character - lines starting with this will be ignored
`CHR` - Chromosomes must be in the form [1-22,X,Y,M].
`POS` - Positions must be 1-based.
`ALT` - alternate allele column must only contain one allele per line.
`SCORE` - Scores must be normalised to the range 0.0-1.0 such that 0.0 is considered benign and 1.0 pathogenic.

Files can be created using the commands:
`bgzip file > file.gz`
`tabix -s1 -b2 -e2 -c# file.gz`

Then in the `application.properties` file:

```properties
exomiser.hg19.test-pathogenicity-score-path=full/path/to/scores.tsv
exomiser.hg38.test-pathogenicity-score-path=full/path/to/scores.tsv
```

Let me know how this goes and/or if you'd like to collaborate on some testing data.

**Comment by davidfstein** [comment]
Thank you! It would be great to collaborate on this, I will follow up via email
